### ISSUE TITLE
failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by alokranjan1234** [openai/baselines#10]
I got the following error while training the cart pole example:

failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
[screen.txt](https://github.com/openai/baselines/files/1031431/screen.txt)

There is no issue with my cuda driver as I have verified the installation by running some for the cuda sample codes

I guess the issue can be resolved by making the following changes in the code:
https://stackoverflow.com/questions/41117740/tensorflow-crashes-with-cublas-status-alloc-failed

**Comment by siemanko** [comment]
Try making sure that the tensorflow is working for you, before using baselines. Also you way want to install non-GPU version of Tensorflow if you just want to check out the cartpole example.
