### ISSUE TITLE
Not train with vectorized environment for APIs you don't have control over?

### ISSUE THREAD

**Issue by zergy** [openai/baselines#1006]
Is there a way to not use vectorized environment to train PPO and A2C for APIs that you can't really wrap with a DummyVecEnv? and not have to use either "Box" or "Discrete" for action/obs space?

for environments that don't really have control over the code? such as starcraft2 or other non-self-created games? (don't believe pysc2 provides vec envs, nor are action/obs in box/discrete format)

**Comment by christopherhesse** [comment]
If you want the algorithms in baselines to work without modification with a custom environment, it will need to adhere to the gym interface.  If it uses that interface, you can use the DummyVecEnv wrapper to convert it.

If the environment doesn't currently have the gym interface, you will either need to create a python object that meets the interface or else change the baselines code to handle this new type of environment.
