### ISSUE TITLE
Mismatch between plotted iterations and actual iterations

### ISSUE THREAD

**Issue by RyanRizzo96** [openai/baselines#1020]
I am training HER on FetchReach for 10k iterations:

`
python3 -m baselines.run --alg=her --env=FetchReach-v1 --num_timesteps=10000 --save_path=~/models/testRum_HER_reach_10k --log_path=~/logs/HER/test_10k
`

I then use the information [here](https://github.com/openai/baselines/blob/master/docs/viz/viz.ipynb) to visualize the results. I present my code below. AS can be seen the plotted result shows 20k iterations whereas the actual number of iterations is 10k. Any idea why this happens?

```

from baselines.common import plot_util as plot
import matplotlib.pyplot as plt
import numpy as np

results = plot.load_results('~/logs/HER')
print(results)
r = results[0]
plt.plot(np.cumsum(r.monitor.l), plot.smooth(r.monitor.r, radius=10))  # radius to smoother
plt.xlabel('Iterations')
plt.ylabel('Reward')
plt.show()

```

![image](https://user-images.githubusercontent.com/31866965/66938360-56202b00-f041-11e9-9aed-b62835f15d5a.png)

**Comment by christopherhesse** [comment]
`num_timesteps` often means `num_timesteps_per_process` or something like that.  How many monitor files do you have in your log path, and what is the sum of the `l` column in each of those?

**Comment by RyanRizzo96** [comment]
@christopherhesse , thanks for getting back on this issue. I have 1 monitor file in the log path, and the sum of `l` column is 20,000 as indicated in the plot.

**Comment by christopherhesse** [comment]
I ran the program and it looks like if you don't specify an eval env, it uses the main env, so for each training rollout you also do an eval rollout and so the total number of steps is twice what you specified.

You should specify a separate eval env with its own monitor file, which may not be supported currently by baselines.run.  Sorry for the confusion!
