### ISSUE TITLE
Python crashes when starting baselines or pytest

### ISSUE THREAD

**Issue by Phantomb** [openai/baselines#1023]
See the image. 
![image](https://user-images.githubusercontent.com/5164642/67768102-19493080-fa52-11e9-804d-4bdbeccfd21f.png)

What exactly causes this, and what can I do about it?

**Comment by JiyueWang** [comment]
Seems you should upgrade pip like the yellow words said

**Comment by Phantomb** [comment]
Allright it seems I managed to fix it. It was not due to the pip version, but it did push me in the right direction.

Apparently, the pip I was using was the general pip, not the pip of my (conda) environment. So fixing that, it appeared that some of the packages that were found and installed were also installed into the incorrect version or pip path.

However, after reinstalling baselines into a new, clean env, it seems gym is not automatically installed in the baselines installation. That might be something to fix.

After installing gym (0.15.3) seperately using pip, I now get the pytest errors that ```ImportError: Could not find 'cudart64_100.dll'.``` which came from the fact that I had an older CUDA installation than version 10 (I was using version 9 before).

After fixing that, it was complaining there were no modules named `cv2`, `matplotlib` and `pandas` installed, so I had to `conda install opencv` and pip install the others as they were apparently not added when installing baselines into the environment...

**Now**, it works, but I get `F`'s and `S`'s for the tests (see image below). Is that to be expected?

![image](https://user-images.githubusercontent.com/5164642/67860000-2f6ff300-fb1d-11e9-9d8f-e3b7744086c2.png)

**Comment by christopherhesse** [comment]
Some of those packages are definitely required by the baselines install, so it might be you did not install it correctly: https://github.com/openai/baselines/blob/master/setup.py#L34

The tests pass on linux, but that doesn't mean they will work on windows, please run baselines inside a docker container if you want to get the tests to work: https://travis-ci.org/openai/baselines/builds/608473602?utm_source=github_status&utm_medium=notification

**Comment by christopherhesse** [comment]
This dockerfile is used for tests so it should be sufficient: https://github.com/openai/baselines/blob/master/Dockerfile
