### ISSUE TITLE
mpi4py dependent algorithms broken in commit 3f676f7d1e16a0880cb7fed5850bc00efba413d6

### ISSUE THREAD

**Issue by KeirSimmons** [openai/baselines#108]
After a lot of testing with the recent commit introducing A2C and ACKTR, I found that all algorithms using mpi4py did not work (exited with error status 1). Reverting to commit 882251878f04e1eb1ac9da965772eca9c1ab272a solved this issue. Something changed in the common directory must have affected this.

**Comment by joschu** [comment]
I can't reproduce this error. However, we've changed the code as of the last commit and now you should call mpirun directly on the command line. Does this fix your problem?
