### ISSUE TITLE
Manually reset the environment?

### ISSUE THREAD

**Issue by andrewliao11** [openai/baselines#109]
I just view the a2c and ACKTR code and I found that the author did not reset the environment when ```done==True```. I'm not sure if the ```env``` has some wrapper that automatically do this (at least I didn't find it.)

e.g. for a2c, in [line128 at a2c.py](https://github.com/openai/baselines/blob/master/baselines/a2c/a2c.py#L128) should we add ```env[n].reset()```?

**Comment by joschu** [comment]
The SuprocessVecEnv class resets it automatically.
