### ISSUE TITLE
SubprocVecEnv not treated as VecEnv by PPO2

### ISSUE THREAD

**Issue by allenanie** [openai/baselines#1090]
I'm trying to train a CNN-LSTM policy using PPO2 on a custom game environment.

```python
from baselines.common.vec_env.subproc_vec_env import SubprocVecEnv

class BounceVecEnv(SubprocVecEnv):
    def __init__(self, env_maker, num_envs):
        self.metadata = {'render.modes': []}
        self.reward_range = (-5, 5)

        env_fns = [env_maker.make for _ in range(num_envs)]

        super().__init__(env_fns)
        self.dummy_info = [{} for _ in range(num_envs)]
```

Then in the main code:

```python
env = BounceVecEnv(env_maker, num_envs=2)
print(isinstance(env, VecEnv))
# True
model = PPO2('CnnLstmPolicy', env, nminibatches=args.nminibatches, verbose=1)
model.learn(5)
# Wrapping the env in a DummyVecEnv
```

PPO2 will always wrap my environment in a `DummyVecEnv` even though my environment was already wrapped in `SubprocVecEnv`. This leads to a shape mismatch issue.

Can anyone maybe let me know how to debug this issue and why it's happening?

**Comment by allenanie** [comment]
Actually, I know what happened now.
I shouldn't have inherited from `SubprocVecEnv`, should just directly instantiate it.

**Comment by beerzzaaa** [comment]
i don't know how to play

but i need play with open ai1vs1 SF

i need youtube learn to join open ai

ในวันที่ ศ. 13 มี.ค. 2020 เวลา 03:05 Allen Nie <notifications@github.com>
เขียนว่า:
