### ISSUE TITLE
baselines/baselines/trpo_mpi/run_atari.py   Bug about bench.Monitor

### ISSUE THREAD

**Issue by jxwjasonborne** [openai/baselines#110]
Hi:

when running at this line
 **env = bench.Monitor(env, osp.join(logger.get_dir(), "%i.monitor.json"%rank))**

there always reports bug "TypeError: join() argument must be str or bytes, not 'NoneType' "

If I comment this line, the program still runs normally.

I know what the error means, but I don't know why this bug happens here. 

Thank you !

**Comment by joschu** [comment]
Fixed
