### ISSUE TITLE
ImportError: cannot import name FlattenObservation

### ISSUE THREAD

**Issue by ryanmaxwell96** [openai/baselines#1116]
Hey,

I know someone else created an issue with this error, but I have not seen any resolve so creating my own to bring it back up again. I'm getting this error "ImportError: cannot import name FlattenObservation" with gym 0.15.4. Any help would be greatly appreciated!

Thanks

**Comment by zhihaocheng** [comment]
Actually, this problem is related to the version of Gym. FlattenObservation is defined in Gym wrappers, and I guess the version 0.15.4 Gym is to new to support FlattenObservation.

**Comment by ryanmaxwell96** [comment]
I was finally able to get it to work, though with gym 0.15.3 not 0.15.4. Also, I had to remove two underscores in the run.py.
