### ISSUE TITLE
fatal error: mpi.h: No such file or directory

### ISSUE THREAD

**Issue by guotong1988** [openai/baselines#114]
_configtest.c:2:17: fatal error: mpi.h: No such file or directory
     #include <mpi.h>
                     ^
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    error: Cannot compile MPI programs. Check your configuration!!!

**Comment by nikoliazekter** [comment]
Try `sudo apt install libopenmpi-dev`

**Comment by JasonHanG** [comment]
Same error and I'm using mac.
Try `brew install openmpi  ` 
In case homebrew can't  successfully download  the files  for you ,  use a  vpn or  [manual brew Install](http://mygeekdaddy.net/2014/12/05/how-to-install-a-local-file-in-homebrew/) it.

**Comment by 17760875908** [comment]
mac `brew install mpich` ,I do this setup successfully

**Comment by rasmh66** [comment]
On Ubuntu:
 sudo apt install linuxbrew-wrapper
 brew install openmpi
 sudo apt-get install build-essential
 PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
 brew install openmpi

**Comment by Xiangju** [comment]
For those who needs to install software on remote/HPC server, to solve the error, you just need to load MPI library / package before installing the software.
For instance, installing mpi4py for python require MPI library, do the following before installing:
```
module avail MPI
module load name_of_MPI_library
pip install --user mpi4py # install mpi4py to user's own local directory
```

**Comment by mimoralea** [comment]
For RedHat and CentOS:

```
yum install openmpi-devel
export CC=/usr/lib64/openmpi/bin/mpicc
pip install mpi4py
```
Source: https://stackoverflow.com/a/51053324/786279

**Comment by straightjacket** [comment]
> mac `brew install mpich` ,I do this setup successfully

Glad I found this thread this worked for me!

**Comment by milosjovanov** [comment]
On Amazon Linux 2023, try this:

```
sudo dnf install openmpi openmpi-develz
export PATH=$PATH:/usr/lib64/openmpi/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/openmpi/lib
pip3 install mpi4py
```
