### ISSUE TITLE
Missing Benchmark Scripts for PPO

### ISSUE THREAD

**Issue by Breakend** [openai/baselines#118]
Hi @joschu 

You added the benchmark code, but missed the script:

https://github.com/openai/baselines/blob/master/baselines/bench/benchmarks.py#L80

Using the run_mujoco script with the default parameters i can't even get half of the reward published in the ppo paper, so I'm wondering if there are different settings in this ppo2 script that go with the ppo publication. 

Thanks

**Comment by joschu** [comment]
The ppo2 code isn't released yet
However I fixed pposgd_simple.py in the last commit -- the vf clipping was causing a major problem.
