### ISSUE TITLE
Fail to return sum of priority [segment_tree.py ]

### ISSUE THREAD

**Issue by RLWithME** [openai/baselines#1195]
From the code: https://github.com/openai/baselines/blob/master/baselines/common/segment_tree.py
The "sum" method in SumSegmentTree class should return arr[start] + ... + arr[end] but, seems it returns arr[start] +... + arr[end-1]

    def sum(self, start=0, end=None):
        """Returns arr[start] + ... + arr[end]"""
        return super(SumSegmentTree, self).reduce(start, end)

---------------------------------------------------------------------------
**[my test code]**
capacity = 16

ss_tree = SumSegmentTree(capacity)
ss_tree[0] = 3
ss_tree[1] = 2
ss_tree[2] = 5
ss_tree[3] = 4

print('sum of elements:', ss_tree.sum(start=0, end=3))

**[result]**
sum of elements: 10

**Comment by mkhlyzov** [comment]
It seems to be a typo in code comments (which reappears several times). Judging from implementation, functionality is supposed to mimic slicing logic: ```start <= idx < end```
```
def reduce(self, start=0, end=None):
        if end is None:
            end = self._capacity
        if end < 0:
            end += self._capacity
        end -= 1
        return self._reduce_helper(start, end, 1, 0, self._capacity - 1)
```
Calling ```sum``` with no arguments executes tree-wise operation ```sum(0, self._capacity - 1)``` for example.

**Comment by RLWithME** [comment]
Then,  I think below code:
(from: https://github.com/openai/baselines/blob/master/baselines/deepq/replay_buffer.py)

![image](https://user-images.githubusercontent.com/93563862/166244769-819709ea-cb51-44c1-9871-40ab1a5a557a.png)

has to be fixed:
len(self._storage - 1) -> len(self._storage)

right?

**Comment by mkhlyzov** [comment]
Yeah, you are right.
Either `len(self._storage)` or calling with no arguments.
That's a very old bug, judging from opened issues. Goes back to year 2017.
https://github.com/openai/baselines/issues?q=prioritized
https://github.com/openai/baselines/issues?q=is%3Aissue+is%3Aopen+tree
I _think_ some developer claimed to fix it almost immediately, but his brunch _probably_ got lost in time.
 If you are interested in implementing prioritised replay for your own project, good news is segment_tree seems to be implemented correctly (besides the thing that executing reduce method on empty tree causes infinite recursion).
This issue https://github.com/openai/baselines/issues/1158 gives some useful insights about segment_tree

**Comment by RLWithME** [comment]
Ah, okay I got it. thank you for your attention!
