### ISSUE TITLE
Replicating PPO result

### ISSUE THREAD

**Issue by a7b23** [openai/baselines#126]
To compute target value using TD(lambda) estimator why is - 
seg["tdlamret"] = seg["adv"] + seg["vpred"]
Should it not be only seg["adv"] going by the paper...

**Comment by Breakend** [comment]
tdlamret is the target for the value function approximator. I think the idea is if you expand this term, it *should* be equivalent to discounted returns.

**Comment by a7b23** [comment]
The discounted return is given by seg["adv"] term only . The other term which is the predicted value of states is the extra term that has been added and so i am confused about it

**Comment by a7b23** [comment]
@Breakend .. i was making a mistake earlier .. I thought that the tdlamert is the target for the advantage function . The target for the advantage function , which is seg["adv"] is the same as mentioned in the paper but i still can't figure out as to how expanding tdalmert gives the discounted returns . I expanded the term and i think there will be some additional terms too.

**Comment by andyljones** [comment]
This caught my eye too. Both [the PPO paper](https://arxiv.org/pdf/1506.02438.pdf) and [SpinningUp](https://github.com/openai/spinningup/blob/master/spinup/algos/ppo/ppo.py#L66) use the discounted sum of future returns as the value target. Baselines meanwhile seems to use a weird TD-1 error with added advantage term. It shows up in both [PPO1](https://github.com/openai/baselines/blob/master/baselines/ppo1/pposgd_simple.py#L78) and [PPO2](https://github.com/openai/baselines/blob/master/baselines/ppo2/runner.py#L65) so I don't think it's a bug.
