### ISSUE TITLE
python 2.7 can't support iterbatches in dataset.py

### ISSUE THREAD

**Issue by XHUJOY** [openai/baselines#134]
python 2.7 can't support  iterbatches in dataset.py.
https://github.com/openai/baselines/blob/master/baselines/common/dataset.py#L50

**Comment by bkj** [comment]
Why is this closed?  Is there a Python 3 vs Python2.7 disclaimer in the README somewhere?

**Comment by xhujoy** [comment]
this is only supported by python 3.
https://github.com/openai/baselines/blob/master/setup.py#L4

**Comment by timkpaine** [comment]
I have a fork for python2 with tests passing [here](https://github.com/timkpaine/baselines), but its ugly (I.e. forcing named arguments). I will keep it in-sync for a little while, but as python2.7 is EOL anyway its not worth doing a PR.
