### ISSUE TITLE
Unknown MS Compiler version 1900

### ISSUE THREAD

**Issue by egg-west** [openai/baselines#139]
I've tried to install baselines with command
pip install -e .
but there shows some error when it runs,
finally I can't import baselines
the trouble is Unknown MS Compiler version 1900
Thank you for helping me.
I've had VS2015 on my Window 10.

**Comment by nikoliazekter** [comment]
Did you clone the repo before running pip install?

**Comment by egg-west** [comment]
Of course ,btw I lost all my computer path recenctly.

**Comment by olegklimov** [comment]
Hi @egg-west . We don't support Windows officially. If it works, that's great, if someone post a PR fixing it to work better on Windows, that's even better.
