### ISSUE TITLE
PPO Atari performance

### ISSUE THREAD

**Issue by Seungyul-Han** [openai/baselines#140]
For atari training,
i run ppo as mpirun -np 8 python -m baslines.ppo1.run_atari or simply run run_atari.py and
I see the result by average 100 episode reward mean
whether i changed clippling reward or vf clipping as old version, or not,
the score of atari game do not increase like paper, so why they are different?

How do i get same atari results in ppo?

**Comment by joschu** [comment]
The printouts are reporting the clipped reward, which might not be the same as the actual reward. look at the monitor.csv files instead.
