### ISSUE TITLE
Nan in PPO1 lossandgrad function

### ISSUE THREAD

**Issue by sky4star** [openai/baselines#142]
Hi everyone,

While using PPO1 in my environment, i notice training begin to return nan after hundreds of iterations. It happened quite randomly, even after i call set_global_seeds at very beginning.

After some debugging, i found it happens in function lossandgrad.  Code `U.flatgrad(total_loss, var_list)` causes almost all variables become nan. And after `adam.update`, everything become nan. 

The following is some debugging infos, we can see all input and medial variables are correct except var_mean which is np.mean(g). 

ob [[ 0.0027  1.3759 -0.0069 ...,  0.      0.      0.    ]
 [ 0.0027  1.9821  0.064  ...,  0.      0.      0.    ]
 [ 0.0027  1.0407  0.0622 ...,  0.      0.      0.    ]
 ..., 
 [ 0.0027  1.0851  0.0669 ...,  0.      0.      0.    ]
 [ 0.0027  0.5134  0.0675 ...,  0.      0.      0.    ]
 [ 0.0027  1.5774  0.0453 ...,  0.      0.      0.    ]] ac [22  7  7 38 29  7  7 38  7 29  7 29 38 29  7 38  7  7  7 38  7 38 29  7  7
  7 38  7 38  7 38 38  7  7  7  7 38 29  7  7  7  7 38  7 38 38 29 29  7  7
 38  7 22 38  7  7  7  7  7 38 38 38 38  7] atarg [ 1.12318552 -0.67943805 -1.01294196 -1.03427052  2.14921665 -0.85447145
 -0.93667883 -0.35739261 -0.21336575  0.02881504  1.07411468 -0.69137764
  1.02904773  1.33760941 -0.63198256  0.13088499 -0.06968116  0.97442305
 -2.43799257 -1.03363037  0.98555201  0.43409169  1.00224149 -0.74469745
 -0.66689521  1.83901632 -0.98348093  0.80633247  1.01622546 -0.41460404
  0.42909643 -1.07131553 -0.15991424  0.24631344 -0.5587799  -1.12394345
  0.75114334  0.91409922 -0.10816446 -0.5611096  -0.40340242  1.71488225
 -1.02157712 -0.67243004 -1.11016846  0.34691596  1.9300015   0.27394876
 -1.20318902 -0.03391408  0.17830259  1.23505545  0.30376387 -0.74852663
 -0.67437881  0.80403894  2.06672692 -2.28275466 -0.54343557 -1.0313015
  0.30700505  0.32140076  0.94269991 -0.62494278] vtarg [ -8.58019447 -10.03150845  -9.51259232 -11.01313496  -9.31116867
  -9.29969978  -9.4032402  -10.15354061  -9.42228317 -10.91253471
  -8.63656998 -11.01703167  -9.84621811  -9.63038635 -10.12339401
 -10.02165031  -9.25692844 -10.11578941  -9.66532135 -10.88745689
  -8.66513538 -10.07250786 -10.85014439  -9.93760586  -9.74904251
  -9.24131298 -10.05650997  -8.61236095  -9.85989857  -9.58564758
 -10.04710674 -10.29377842  -9.36331558  -8.66187096  -8.8085928
  -9.15998936 -10.07834721 -10.853652    -9.30824566  -8.88369465
  -9.65874004 -10.06182098 -10.17300129  -9.84060287 -10.41820431
  -9.93770695  -9.87264919 -11.05830479  -9.27877808  -8.63895416
  -9.97799301  -9.20850658  -8.59892559 -10.52128029  -9.04729366
  -8.62459755  -9.54952145  -9.46625042  -8.73438549 -10.64307499
  -9.90825844  -9.8766346  -11.06212711  -8.9635458 ]
debug_atarg [ 1.12318552 -0.67943805 -1.01294196 -1.03427052  2.14921665 -0.85447145
 -0.93667883 -0.35739261 -0.21336575  0.02881504  1.07411468 -0.69137764
  1.02904773  1.33760941 -0.63198256  0.13088499 -0.06968116  0.97442305
 -2.43799257 -1.03363037  0.98555201  0.43409169  1.00224149 -0.74469745
 -0.66689521  1.83901632 -0.98348093  0.80633247  1.01622546 -0.41460404
  0.42909643 -1.07131553 -0.15991424  0.24631344 -0.5587799  -1.12394345
  0.75114334  0.91409922 -0.10816446 -0.5611096  -0.40340242  1.71488225
 -1.02157712 -0.67243004 -1.11016846  0.34691596  1.9300015   0.27394876
 -1.20318902 -0.03391408  0.17830259  1.23505545  0.30376387 -0.74852663
 -0.67437881  0.80403894  2.06672692 -2.28275466 -0.54343557 -1.0313015
  0.30700505  0.32140076  0.94269991 -0.62494278] pi_ac [-11294.78808594 -11124.45996094 -10031.06933594 -11454.34667969     -0.
 -10018.37890625 -10018.15039062 -11289.58105469 -10969.51953125     -0.
 -11504.63085938     -0.         -12685.74316406     -0.         -11286.43164062
 -11769.71777344 -10984.77929688 -13253.56054688  -8011.28076172
 -11323.94335938 -12219.30859375 -12224.87402344     -0.         -10918.93554688
 -10841.57421875 -13555.62109375 -10430.38867188 -11093.91113281
 -12679.06835938 -10977.67675781 -12186.4765625  -10581.83691406
 -10977.99902344 -10483.05566406  -9596.6328125   -9205.06152344
 -12719.48046875     -0.         -10988.81445312  -9688.39746094
 -11079.69042969 -14255.98828125 -10506.15527344 -10943.00976562
 -10669.1953125  -11999.30664062     -0.             -0.          -9229.14648438
 -10062.9921875  -11781.85742188 -12617.42382812 -10302.42773438
 -11278.91015625  -9716.35058594 -11106.19042969 -14169.56152344
  -8002.61132812  -9524.1015625  -11074.47167969 -11869.46582031
 -11852.69433594 -13921.26367188  -9689.04394531] opi_ac [-11434.25097656 -11123.69824219 -10030.4375     -11453.47558594     -0.
 -10017.75       -10017.52148438 -11288.84960938 -10968.82910156     -0.
 -11504.00976562     -0.         -12684.95605469     -0.         -11285.65722656
 -11768.88476562 -10984.08398438 -13252.65039062  -8010.8046875
 -11323.08007812 -12219.1796875  -12224.06445312     -0.         -10918.18847656
 -10840.76953125 -13555.10644531 -10429.66113281 -11093.15429688
 -12678.28320312 -10976.984375   -12185.66894531 -10581.09570312
 -10977.3046875  -10482.39941406  -9596.05664062  -9204.50390625
 -12718.60449219     -0.         -10988.11914062  -9687.81445312
 -11078.97753906 -14255.41015625 -10505.41992188 -10942.19726562
 -10668.44726562 -11998.44335938     -0.             -0.          -9228.58789062
 -10062.31835938 -11781.02148438 -12616.609375   -10429.57910156 -11278.125
  -9715.76464844 -11105.43164062 -14168.98828125  -8002.13916016
  -9523.53125    -11073.62695312 -11868.62402344 -11851.85351562
 -13920.72558594  -9688.4609375 ] vpred -8.60416 pi_pd -718.229 opi_pd [ -1625.09802246  -2311.84301758  -1857.67687988  -1793.23034668
  -2136.73339844  -2075.8605957   -2317.89282227  -1534.31347656
   -185.11602783  -1851.53076172  -1884.68530273  -1723.97131348
  -1526.62548828   -157.83860779   2160.90063477   -530.41455078
  -1749.25036621   -261.03857422   -942.00054932  -1822.72729492
  -1870.55041504  -1971.4675293   -1415.84155273   1568.7869873
  -1681.95825195   -950.4786377   -1636.75756836  -1123.56494141
  -2747.19775391  10018.40917969  -1674.74328613  -1987.71435547
   3255.13427734   -880.12823486  -1574.16931152  -1190.97753906
  -1445.11486816  -1827.99633789  -1237.04785156   -130.24992371
    429.74005127   -959.8034668     510.55343628   2817.98461914
  -1048.71533203   -325.46896362   -889.20336914   1458.05639648] kl_oldnew 0.0 var_mean nan total_loss 2.38313

I also call `tf.gradients(total_loss, var_list) `manually, and here is the output
[array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]], dtype=float32), array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan], dtype=float32), array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]], dtype=float32), array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan], dtype=float32), array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]], dtype=float32), array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan], dtype=float32), array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]], dtype=float32), array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan], dtype=float32), array([[    0.        ],
       [    0.        ],
       [ 1446.88012695],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 1879.63928223],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 2196.01147461],
       [ 1509.57312012],
       [    0.        ],
       [ 1138.35095215],
       [    0.        ],
       [ 1407.34814453],
       [    0.        ],
       [ 1766.49365234],
       [    0.        ],
       [    0.        ],
       [ 1933.31677246],
       [ 1709.32055664],
       [ 2191.05175781],
       [    0.        ],
       [    0.        ],
       [ 1099.86547852],
       [    0.        ],
       [ 1456.03161621],
       [ 1692.73669434],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 1732.23754883],
       [    0.        ],
       [    0.        ],
       [ 1233.92382812],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 1391.41455078],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 2068.62304688],
       [    0.        ],
       [    0.        ],
       [  892.63079834],
       [    0.        ],
       [ 1436.75830078],
       [ 1269.76086426],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 1940.44494629],
       [ 2062.49853516],
       [ 2081.3190918 ],
       [    0.        ],
       [ 2186.86108398],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 1381.64343262],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 1783.73095703],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 1271.93395996],
       [ 1971.03405762],
       [ 2074.48974609],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 1854.93737793],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 2277.41210938],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [    0.        ],
       [ 1886.60791016],
       [    0.        ],
       [ 1154.06677246],
       [    0.        ],
       [    0.        ],
       [ 1929.79492188],
       [    0.        ],
       [ 1824.59301758],
       [ 1682.57958984],
       [    0.        ],
       [    0.        ],
       [ 1521.48742676],
       [    0.        ],
       [    0.        ],
       [ 1962.93835449],
       [ 1726.97180176],
       [ 1760.04370117],
       [ 1861.9744873 ],
       [    0.        ],
       [    0.        ],
       [ 1364.34765625],
       [ 1516.06970215],
       [    0.        ],
       [ 1316.67663574],
       [    0.        ],
       [    0.        ]], dtype=float32), array([ 3.16057944], dtype=float32)

Not sure if this issue relates with #127 

Thanks in advance!

**Comment by cxxgtxy** [comment]
Atari or mujoco? Does NAN (PPO)still exist If you do as https://github.com/openai/baselines/pull/143,?

**Comment by sky4star** [comment]
Yes, i saw your pull request, will test it soon.
The Nan happens on my own model, which is a simple full connection model.

**Comment by olegklimov** [comment]
143 is fixed, please check again if you have this bug.
