### ISSUE TITLE
MPI not working with python3.6 in mac

### ISSUE THREAD

**Issue by abhigenie92** [openai/baselines#145]
```
 ~/t/b/b/ppo1   master ±  python run_atari.py                                                    (ppo_cont_check)
Traceback (most recent call last):
  File "run_atari.py", line 57, in <module>
    main()
  File "run_atari.py", line 54, in main
    train(args.env, num_frames=40e6, seed=args.seed)
  File "run_atari.py", line 17, in train
    from baselines.ppo1 import pposgd_simple, cnn_policy
  File "/Users/abhishek/test/baselines/baselines/ppo1/pposgd_simple.py", line 6, in <module>
    from baselines.common.mpi_adam import MpiAdam
  File "/Users/abhishek/test/baselines/baselines/common/mpi_adam.py", line 1, in <module>
    from mpi4py import MPI
ImportError: dlopen(/anaconda/envs/ppo_cont_check/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libmpi.1.dylib
  Referenced from: /anaconda/envs/ppo_cont_check/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-darwin.so
  Reason: image not found
 ~/t/b/b/ppo1   master ±  conda list | grep mpi                                                  (ppo_cont_check)
mpi4py                    2.0.0                     <pip>
```

**Comment by abhigenie92** [comment]
Any ideas?

**Comment by stevenschmatz** [comment]
+1 to this issue

**Comment by akblissweb** [comment]
I think I fixed this problem with:

brew install mpicc
pip3 install mpi4py

but I was using virtualenv, not anaconda, but it might work in the same way

**Comment by olegklimov** [comment]
Right, the problem is python mpi is just a wrapper. You have to install library itself.

**Comment by juanferEspinosa** [comment]
Hi guys, I have the same issue and I do not know how to fix it. I have little experience with python and I need to do a homework about it. This error is shown: ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libmpi.1.dylib
  Referenced from: /anaconda3/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-darwin.so
  Reason: image not found

Thank you so much if you could help me with this.

**Comment by phamvanvung** [comment]
For me, I install `mpich` with this command `conda install mpich`, then it will work.
