### ISSUE TITLE
potential bug in baselines/deepq/build_graph.py line225

### ISSUE THREAD

**Issue by feiwang3311** [openai/baselines#157]
In baselines/deepq/build_graph.py line 225, function 
_def perturb_vars(original_scope, perturbed_scope):_
was defined, but the parameters were not used in the function body.

However in line 245, code:
_perturb_for_adaption = perturb_vars(original_scope="q_func", perturbed_scope="adaptive_q_func")_
tried to assign new scopes to the parameters, which will be useless. 

That looks like a bug! 

Fei

**Comment by matthiasplappert** [comment]
Fixed in https://github.com/openai/baselines/commit/49c1a8ec26f738cef6a4406550bf219299164f25
