### ISSUE TITLE
How to define multi-dimensional action_space for deepq

### ISSUE THREAD

**Issue by kaihuchen** [openai/baselines#159]
I am trying to use the deepq model for training a simulated car in an Unreal environment. My initial goal is to get the car to learn to drive around the given environment autonomously for as long as possible at good speed while avoiding any obstacles. I want to define three possible controls for deepq: throttle, brake, and steering.  However, I found that deepq expects an **n attribute** for its self.action_space variable, which means that I am unable to use multi-discrete or Box for defining self.action_space, which means that I am allowed to define only one control. 

My question here is: is there anyway for me to define more than one control for deepq?

**Comment by Azael05x** [comment]
Same issue here. Can not pass Box element to action space for my environment.

**Comment by unixpickle** [comment]
In its simplest form, Q-learning only works for discrete action spaces. There are some ways to adapt Q-learning to continuous action spaces, but those are currently not implemented in this repository. You are likely to have better results with PPO.

**Comment by unixpickle** [comment]
As a side note: it is often possible to turn your action space into a discrete list of options. For example, if you have a tuple of three discrete action spaces, you could use a cartesian product to turn this into a single discrete action space.
