### ISSUE TITLE
Cannot pip install

### ISSUE THREAD

**Issue by da1z** [openai/baselines#165]
Running pip install -e . with python 3

Getting 
  Could not find a version that satisfies the requirement tensorflow>=1.0.0 (from baselines==0.1.4) (from versions: )
No matching distribution found for tensorflow>=1.0.0 (from baselines==0.1.4)

How to fix this?

Thanks

**Comment by alterEgoOS** [comment]
I found a workaround, make sure you have installed tensorflow installed first,  then to bypass this error, download the source code, edit setup.py,  remove the version limit 
replace 'tensorflow >= 1.0.0',  by 'tensorflow',  try to install again using pip install -e .
it worked for me

**Comment by Lokarno** [comment]
Hi

I already had this, you have to use 64-bit python&pip.
