### ISSUE TITLE
Load act and continue learning

### ISSUE THREAD

**Issue by smasoudn** [openai/baselines#17]
I am trying to save the Q network and **reload** it and **continue improving** it.

This is how I save `act` every few episodes:
```
ActWrapper(act, act_params).save("myfile.pkl")
```

However, when I load it, I get an error saying that some variables are exist. This is how I load a saved `act`:

```
act, train, updated_target, debug = deepq.builld_train(....)
act = ActWrapper.load("myfile.pkl")
```

Any idea would be appreciated.

**Comment by siemanko** [comment]
Hi @smasoudn,

Continuing training is not supported at the moment. The only purpose of load is to load an already trained model returned by `deepq.learn`. If you wish to train with proper checkpointing support you will need to implement it by yourself. You may want to check out Atari code which already does this but probably in more convoluted way than necessary. In addition, I think it should be possible to modify `simple.py` to do checkpointing, as most of the code is already there. I would gladly accept a pull request if it includes a test. Thanks!

**Comment by siemanko** [comment]
Closing for now.
