### ISSUE TITLE
Can't install baselines on Windows

### ISSUE THREAD

**Issue by Lukasas** [openai/baselines#173]
I've been trying to install baselines on Windows 10 x64 for now like 4 hours
This is my pip install -e . output:

`Obtaining file:///I:/ML/baselines
Requirement already satisfied: gym[atari,classic_control,mujoco] in c:\programy\python\python36\lib\site-packages (from baselines==0.1.4)
Collecting scipy (from baselines==0.1.4)
  Using cached scipy-0.19.1.tar.gz
Requirement already satisfied: tqdm in c:\programy\python\python36\lib\site-packages (from baselines==0.1.4)
Collecting joblib (from baselines==0.1.4)
  Using cached joblib-0.11-py2.py3-none-any.whl
Collecting zmq (from baselines==0.1.4)
Requirement already satisfied: dill in c:\programy\python\python36\lib\site-packages (from baselines==0.1.4)
Requirement already satisfied: tensorflow>=1.0.0 in c:\programy\python\python36\lib\site-packages (from baselines==0.1.4)
Collecting azure==1.0.3 (from baselines==0.1.4)
Requirement already satisfied: progressbar2 in c:\programy\python\python36\lib\site-packages (from baselines==0.1.4)
Collecting mpi4py (from baselines==0.1.4)
Requirement already satisfied: six in c:\programy\python\python36\lib\site-packages (from gym[atari,classic_control,mujoco]->baselines==0.1.4)
Requirement already satisfied: requests>=2.0 in c:\programy\python\python36\lib\site-packages (from gym[atari,classic_control,mujoco]->baselines==0.1.4)
Requirement already satisfied: pyglet>=1.2.0 in c:\programy\python\python36\lib\site-packages (from gym[atari,classic_control,mujoco]->baselines==0.1.4)
Requirement already satisfied: numpy>=1.10.4 in c:\programy\python\python36\lib\site-packages (from gym[atari,classic_control,mujoco]->baselines==0.1.4)
Collecting atari-py>=0.1.1; extra == "atari" (from gym[atari,classic_control,mujoco]->baselines==0.1.4)
  Using cached atari-py-0.1.1.tar.gz
Collecting PyOpenGL; extra == "atari" (from gym[atari,classic_control,mujoco]->baselines==0.1.4)
Collecting Pillow; extra == "atari" (from gym[atari,classic_control,mujoco]->baselines==0.1.4)
  Using cached Pillow-4.3.0-cp36-cp36m-win_amd64.whl
Collecting imageio; extra == "mujoco" (from gym[atari,classic_control,mujoco]->baselines==0.1.4)
Collecting mujoco-py<1.0.0,>=0.4.3; extra == "mujoco" (from gym[atari,classic_control,mujoco]->baselines==0.1.4)
Collecting pyzmq (from zmq->baselines==0.1.4)
  Using cached pyzmq-16.0.2-cp36-cp36m-win_amd64.whl
Requirement already satisfied: pyreadline>=1.7.1 in c:\programy\python\python36\lib\site-packages (from dill->baselines==0.1.4)
Requirement already satisfied: protobuf>=3.3.0 in c:\programy\python\python36\lib\site-packages (from tensorflow>=1.0.0->baselines==0.1.4)
Requirement already satisfied: wheel>=0.26 in c:\programy\python\python36\lib\site-packages (from tensorflow>=1.0.0->baselines==0.1.4)
Requirement already satisfied: tensorflow-tensorboard<0.2.0,>=0.1.0 in c:\programy\python\python36\lib\site-packages (from tensorflow>=1.0.0->baselines==0.1.4)
Collecting azure-mgmt==0.20.2 (from azure==1.0.3->baselines==0.1.4)
Collecting azure-servicemanagement-legacy==0.20.2 (from azure==1.0.3->baselines==0.1.4)
  Using cached azure_servicemanagement_legacy-0.20.2-py2.py3-none-any.whl
Collecting azure-servicebus==0.20.1 (from azure==1.0.3->baselines==0.1.4)
  Using cached azure_servicebus-0.20.1-py2.py3-none-any.whl
Collecting azure-storage==0.20.3 (from azure==1.0.3->baselines==0.1.4)
  Using cached azure_storage-0.20.3-py3-none-any.whl
Requirement already satisfied: python-utils>=2.1.0 in c:\programy\python\python36\lib\site-packages (from progressbar2->baselines==0.1.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programy\python\python36\lib\site-packages (from requests>=2.0->gym[atari,classic_control,mujoco]->baselines==0.1.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\programy\python\python36\lib\site-packages (from requests>=2.0->gym[atari,classic_control,mujoco]->baselines==0.1.4)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\programy\python\python36\lib\site-packages (from requests>=2.0->gym[atari,classic_control,mujoco]->baselines==0.1.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programy\python\python36\lib\site-packages (from requests>=2.0->gym[atari,classic_control,mujoco]->baselines==0.1.4)
Collecting olefile (from Pillow; extra == "atari"->gym[atari,classic_control,mujoco]->baselines==0.1.4)
Requirement already satisfied: setuptools in c:\programy\python\python36\lib\site-packages (from protobuf>=3.3.0->tensorflow>=1.0.0->baselines==0.1.4)
Requirement already satisfied: werkzeug>=0.11.10 in c:\programy\python\python36\lib\site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow>=1.0.0->baselines==0.1.4)
Requirement already satisfied: markdown>=2.6.8 in c:\programy\python\python36\lib\site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow>=1.0.0->baselines==0.1.4)
Requirement already satisfied: bleach==1.5.0 in c:\programy\python\python36\lib\site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow>=1.0.0->baselines==0.1.4)
Requirement already satisfied: html5lib==0.9999999 in c:\programy\python\python36\lib\site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow>=1.0.0->baselines==0.1.4)
Collecting azure-mgmt-network==0.20.1 (from azure-mgmt==0.20.2->azure==1.0.3->baselines==0.1.4)
  Using cached azure_mgmt_network-0.20.1-py2.py3-none-any.whl
Collecting azure-mgmt-compute==0.20.1 (from azure-mgmt==0.20.2->azure==1.0.3->baselines==0.1.4)
  Using cached azure_mgmt_compute-0.20.1-py2.py3-none-any.whl
Collecting azure-mgmt-resource==0.20.1 (from azure-mgmt==0.20.2->azure==1.0.3->baselines==0.1.4)
  Using cached azure_mgmt_resource-0.20.1-py2.py3-none-any.whl
Collecting azure-mgmt-storage==0.20.0 (from azure-mgmt==0.20.2->azure==1.0.3->baselines==0.1.4)
  Using cached azure_mgmt_storage-0.20.0-py2.py3-none-any.whl
Collecting azure-common (from azure-servicemanagement-legacy==0.20.2->azure==1.0.3->baselines==0.1.4)
  Using cached azure_common-1.1.8-py2.py3-none-any.whl
Collecting azure-nspkg (from azure-storage==0.20.3->azure==1.0.3->baselines==0.1.4)
  Using cached azure_nspkg-2.0.0-py2.py3-none-any.whl
Collecting python-dateutil (from azure-storage==0.20.3->azure==1.0.3->baselines==0.1.4)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting azure-mgmt-common (from azure-mgmt-network==0.20.1->azure-mgmt==0.20.2->azure==1.0.3->baselines==0.1.4)
  Using cached azure_mgmt_common-0.20.0-py2.py3-none-any.whl
Collecting azure-mgmt-nspkg (from azure-mgmt-common->azure-mgmt-network==0.20.1->azure-mgmt==0.20.2->azure==1.0.3->baselines==0.1.4)
  Using cached azure_mgmt_nspkg-2.0.0-py2.py3-none-any.whl
Building wheels for collected packages: scipy, atari-py
  Running setup.py bdist_wheel for scipy: started
  Running setup.py bdist_wheel for scipy: finished with status 'error'
  Complete output from command c:\programy\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\LUK~1\\AppData\\Local\\Temp\\pip-build-ukd93qdj\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\LUK~1\AppData\Local\Temp\tmpsj1idmrqpip-wheel- --python-tag cp36:
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['c:\\programy\\python\\python36\\lib', 'C:\\', 'c:\\programy\\python\\python36\\libs']
    NOT AVAILABLE
  
  openblas_lapack_info:
  c:\programy\python\python36\lib\site-packages\numpy\distutils\system_info.py:655: UserWarning: Specified path c:\opt\64\lib is invalid.
    return self.get_paths(self.section, key)
    libraries libopenblas_v0.2.20_mingwpy not found in []
    NOT AVAILABLE
  
  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas,tatlas not found in c:\programy\python\python36\lib
    libraries lapack_atlas not found in c:\programy\python\python36\lib
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in c:\programy\python\python36\libs
    libraries lapack_atlas not found in c:\programy\python\python36\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE
  
  atlas_3_10_info:
    libraries satlas,satlas not found in c:\programy\python\python36\lib
    libraries lapack_atlas not found in c:\programy\python\python36\lib
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in c:\programy\python\python36\libs
    libraries lapack_atlas not found in c:\programy\python\python36\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE
  
  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in c:\programy\python\python36\lib
    libraries lapack_atlas not found in c:\programy\python\python36\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in c:\programy\python\python36\libs
    libraries lapack_atlas not found in c:\programy\python\python36\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE
  
  atlas_info:
    libraries f77blas,cblas,atlas not found in c:\programy\python\python36\lib
    libraries lapack_atlas not found in c:\programy\python\python36\lib
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in c:\programy\python\python36\libs
    libraries lapack_atlas not found in c:\programy\python\python36\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE
  
  c:\programy\python\python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
    libraries lapack not found in ['c:\\programy\\python\\python36\\lib', 'C:\\', 'c:\\programy\\python\\python36\\libs']
    NOT AVAILABLE
  
  c:\programy\python\python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE
  
  c:\programy\python\python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE
  
  Running from scipy source directory.
  non-existing path in 'scipy\\integrate': 'quadpack.h'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\LUK~1\AppData\Local\Temp\pip-build-ukd93qdj\scipy\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\LUK~1\AppData\Local\Temp\pip-build-ukd93qdj\scipy\setup.py", line 412, in setup_package
      setup(**metadata)
    File "c:\programy\python\python36\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\LUK~1\AppData\Local\Temp\pip-build-ukd93qdj\scipy\setup.py", line 336, in configuration
      config.add_subpackage('scipy')
    File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
  
  ----------------------------------------
  Running setup.py clean for scipy
  Complete output from command c:\programy\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\LUK~1\\AppData\\Local\\Temp\\pip-build-ukd93qdj\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  
  ----------------------------------------
  Running setup.py bdist_wheel for atari-py: started
  Running setup.py bdist_wheel for atari-py: finished with status 'error'
  Complete output from command c:\programy\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\LUK~1\\AppData\\Local\\Temp\\pip-build-ukd93qdj\\atari-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\LUK~1\AppData\Local\Temp\tmpk4bq6q8apip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  Unable to execute 'make build -C atari_py/ale_interface -j 7'. HINT: are you sure `make` is installed?
  error: [WinError 2] Systém nemůže nalézt uvedený soubor
  
  ----------------------------------------
  Running setup.py clean for atari-py
Failed to build scipy atari-py
Installing collected packages: scipy, joblib, pyzmq, zmq, azure-nspkg, azure-common, azure-mgmt-nspkg, azure-mgmt-common, azure-mgmt-network, azure-mgmt-compute, azure-mgmt-resource, azure-mgmt-storage, azure-mgmt, azure-servicemanagement-legacy, azure-servicebus, python-dateutil, azure-storage, azure, mpi4py, baselines, atari-py, PyOpenGL, olefile, Pillow, imageio, mujoco-py
  Running setup.py install for scipy: started
    Running setup.py install for scipy: finished with status 'error'
    Complete output from command c:\programy\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\LUK~1\\AppData\\Local\\Temp\\pip-build-ukd93qdj\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\LUK~1\AppData\Local\Temp\pip-26c6imr7-record\install-record.txt --single-version-externally-managed --compile:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['c:\\programy\\python\\python36\\lib', 'C:\\', 'c:\\programy\\python\\python36\\libs']
      NOT AVAILABLE
    
    openblas_lapack_info:
    c:\programy\python\python36\lib\site-packages\numpy\distutils\system_info.py:655: UserWarning: Specified path c:\opt\64\lib is invalid.
      return self.get_paths(self.section, key)
      libraries libopenblas_v0.2.20_mingwpy not found in []
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in c:\programy\python\python36\lib
      libraries lapack_atlas not found in c:\programy\python\python36\lib
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in c:\programy\python\python36\libs
      libraries lapack_atlas not found in c:\programy\python\python36\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries satlas,satlas not found in c:\programy\python\python36\lib
      libraries lapack_atlas not found in c:\programy\python\python36\lib
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in c:\programy\python\python36\libs
      libraries lapack_atlas not found in c:\programy\python\python36\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in c:\programy\python\python36\lib
      libraries lapack_atlas not found in c:\programy\python\python36\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in c:\programy\python\python36\libs
      libraries lapack_atlas not found in c:\programy\python\python36\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
      libraries f77blas,cblas,atlas not found in c:\programy\python\python36\lib
      libraries lapack_atlas not found in c:\programy\python\python36\lib
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in c:\programy\python\python36\libs
      libraries lapack_atlas not found in c:\programy\python\python36\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    c:\programy\python\python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['c:\\programy\\python\\python36\\lib', 'C:\\', 'c:\\programy\\python\\python36\\libs']
      NOT AVAILABLE
    
    c:\programy\python\python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE
    
    c:\programy\python\python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE
    
    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LUK~1\AppData\Local\Temp\pip-build-ukd93qdj\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\LUK~1\AppData\Local\Temp\pip-build-ukd93qdj\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\programy\python\python36\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\LUK~1\AppData\Local\Temp\pip-build-ukd93qdj\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\programy\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    
    ----------------------------------------

  Failed building wheel for scipy
  Failed cleaning build dir for scipy
  Failed building wheel for atari-py
Command "c:\programy\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\LUK~1\\AppData\\Local\\Temp\\pip-build-ukd93qdj\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\LUK~1\AppData\Local\Temp\pip-26c6imr7-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\LUK~1\AppData\Local\Temp\pip-build-ukd93qdj\scipy\`

I really don't know, what to do, I've been googling and searching for every posible solution but nothing works

**Comment by jmfilipe** [comment]
Most of the dependencies of the baselines module are easier to install (in windows) using anaconda/miniconda.  Go through the dependencies in the setup.py file and try to install one by one.

**Comment by Lukasas** [comment]
Well, I tried that aswell, but there is a thing called atari-py, that I can't get working.

**Comment by jmfilipe** [comment]
I've never installed atari-py on windows. Have you tried this: https://github.com/j8lp/atari-py  ?

**Comment by ikamensh** [comment]
This is a painless way to install atari-py on windows.
https://stackoverflow.com/questions/42605769/openai-gym-atari-on-windows/46739299

**Comment by Onitz** [comment]
Thank you so much @ikamensh !

**Comment by stabilus** [comment]
Why does this have to be such a pain with just about everything one tries to install!! Nothing, really nothing works as advertised. Dependencies over dependencies that depend on each-other and their grand-sons. Really? Nothing is backwards compatible, nothing works therefore with a dependency of a future version. Then nothing works the same on linux the same as on windows. Conda and pip try to fill the gaps by "being aware" of such dependencies and still the result is the same: nothing works until one has spent hours if not days trying to find out what the exact configuration of a given solution was to even be able to replicate it. And then if you try to run it on your environment... puff game over, does not work again. This is so ridiculous and the man hours - years - centuries that go to waste with this setup are unbelievable. I used to hate Windows, but boy is it nice to install something and not to have to deal with dependencies.
