### ISSUE TITLE
FileExistsError when saving models

### ISSUE THREAD

**Issue by borgwang** [openai/baselines#175]
Hi. I am trying to train a CartPole agent. I run the following script
_python -m baselines.deepq.experiments.train_cartpole_
Everything works fine in the training phase. But a FileExistsError raised when saving a model. 

Here is the error info

 

> Saving model due to mean reward increase: None -> 82.4
>  Traceback (most recent call last):
>    File "/usr/local/lib/python3.4/runpy.py", line 171, in _run_module_as_main
>      "__main__", mod_spec)
>    File "/usr/local/lib/python3.4/runpy.py", line 86, in _run_code
>      exec(code, run_globals)
>    File "/home/abbo/workspace/baselines/baselines/deepq/experiments/train_cartpole.py", line 31, in <module>
>      main()
>    File "/home/abbo/workspace/baselines/baselines/deepq/experiments/train_cartpole.py", line 24, in main
>      callback=callback
>    File "/home/abbo/workspace/baselines/baselines/deepq/simple.py", line 282, in learn
>      U.save_state(model_file)
>    File "/home/abbo/workspace/baselines/baselines/common/tf_util.py", line 277, in save_state
>      os.makedirs(os.path.dirname(fname), exist_ok=True)
>    File "/home/abbo/.virtualenvs/cm3/lib/python3.4/os.py", line 244, in makedirs
>      mkdir(name, mode)
>  FileExistsError: [Errno 17] File exists (mode 700 != expected mode 775): '/tmp/tmpr0zw_jrp'
> 

I read through the related code. The tempfile moduel creates a temporary directory, then save_state function in tf_util.py calls os.makedir() to make a directory in the system. But the file mode isn't compatible. 
Is this the case? How can I fix it?

**Comment by olegklimov** [comment]
Works for me. Please reopen if the bug is still there.
