### ISSUE TITLE
Is there any way to run this with python 2.7?

### ISSUE THREAD

**Issue by wonchul-kim** [openai/baselines#177]
I am using python 2.7, so i want to run it fully with python 2.7.

Now, to run this code, i erase logger. Because error came up when i run it with python 2.7.

The error is this:
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from baselines import logger, bench
  File "/usr/local/lib/python2.7/dist-packages/baselines/logger.py", line 139
    def log(*args, level=INFO):
                       ^
SyntaxError: invalid syntax

IS there any way to use this logger with python 2.7?

**Comment by MogicianWu** [comment]
I think the correct version is python3.5

**Comment by wonchul-kim** [comment]
I know.

That's why I asked that there is any way to use it in python 2.7.

2017-10-24 6:07 GMT+09:00 Bruce Wu <notifications@github.com>:

**Comment by unixpickle** [comment]
As far as I know, we do not plan to support Python 2.7.

**Comment by timkpaine** [comment]
I have a fork for python2 with tests passing [here](https://github.com/timkpaine/baselines), but its ugly (I.e. forcing named arguments). I will keep it in-sync for a little while, but as python2.7 is EOL anyway its not worth doing a PR.

**Comment by ZZWang21** [comment]
@wonchul-kim have you found a way?

**Comment by ZZWang21** [comment]
@timkpaine  the link is not available. Do you have the link now? Thanks.
