### ISSUE TITLE
Performance of PPO on Pong

### ISSUE THREAD

**Issue by aaronmly** [openai/baselines#185]
Hello,

I can run_atari.py provided in ppo1 without experiencing any problem. However, the mean episodic reward remains at a level of 20+ after thousands of iterations. May I know what the problem could be? Should I change any hyper-parameter settings?

Thanks.

**Comment by DanielTakeshi** [comment]
With Pong, the maximum score is 21 so things are fine ...

**Comment by aaronmly** [comment]
Many thanks for the quick response. Apologies that I actually provided wrong information. I tried a few times to run pong. Sometimes the performance seems to stay around -20. rather than 20+.

In the latest test (have not completed yet), ppo managed to achieve around 10 in performance after 10000 iterations and since then cannot make further improvement. Should I change any hyper-parameters to improve performance further?

**Comment by aaronmly** [comment]
I also noticed that the given OpenAI Baselines implementation seems to support only one actor to sample state transitions. In the PPO paper, it is suggested that 8 actors will be used to sample state transitions in sequence. Will this affect the learning performance?

**Comment by olegklimov** [comment]
Both ppo1 and ppo2 support multi-CPU (many envs in parallel)
