### ISSUE TITLE
Plotting Results

### ISSUE THREAD

**Issue by arbaazkhan2** [openai/baselines#189]
How do I plot my results ?
(Graph of Rewards vs Iterations)

Is there a tensorboard logdir somewhere ? Is there a way to convert 
progress.csv / monitor.csv to plots while its running ?

**Comment by Kelvinson** [comment]
I am also confused about the tensorboard logger.

**Comment by olegklimov** [comment]
> Is there a tensorboard logdir somewhere ? 

Please configure logger.py to use TensorBoardOutputFormat.

> Is there a way to convert progress.csv / monitor.csv to plots while its running ?

Yes, just replot graphs with whatever software you have for this purpose.
