### ISSUE TITLE
Integration with Rllab

### ISSUE THREAD

**Issue by Breakend** [openai/baselines#19]
One thing that seems a bit redundant is the fact that there is openai/rllab and now openai/baselines implementing RL algorithms. It seems like it may be a worthwhile endeavor to merge the two in some way rather than have two parallel repositories that are supposed to have baseline RL implementations. Are there any plans to do so or any thoughts on this from the openai team?

Thanks.

**Comment by siemanko** [comment]
The plan is for baselines to replace rllab.
