### ISSUE TITLE
Pass pretrained supervised q function in deepq.learn 

### ISSUE THREAD

**Issue by rohitghosh** [openai/baselines#192]
I have a trained a separate supervised model for predicting actions corresponding to states. I want to refine that using deepq. Therefore, I wanted to know that how do I pass a pre-trained supervised q_func to the deepq.learn as a parameter instead of using deep.model function.

**Comment by olegklimov** [comment]
Oh, your pretrained policy must be compatible to load weights. Alternatively, you can fill replay buffer with rollouts that your policy produces. A lot of options here... Anyways, that's not a bug in this repo I believe.
