### ISSUE TITLE
A2C multicore usage is not parallel

### ISSUE THREAD

**Issue by shanlior** [openai/baselines#195]
When running A2C , the envelopes does not run at a parallel manner as can be seen from the ubuntu system monitor.
This hurts the performance, and makes **A3C** an even choice, even while using GTX 1080ti.
I'm using Intel i7-7700 and a dual GTX 1080ti setup.
(I also tried to disable one of the GPU'S with CUDA_VISIBLE_DEVICES)

![image](https://user-images.githubusercontent.com/8818883/32431469-51065ec6-c2dc-11e7-9e75-e3c62ad49771.png)

**Comment by olegklimov** [comment]
Please check again if it is the case. I've found from looking at the code, that `run_atari.py` for a2c uses num_env=16, so you should see 16 python processes using CPU simultaneously. Then a lot of GPU usage, then CPUs again.
