### ISSUE TITLE
PPO2: missing VecNormalize and DummyVecEnv

### ISSUE THREAD

**Issue by ycps** [openai/baselines#209]
The example code of PPO2 at [`baselines/baselines/ppo2/run_mujoco.py`](https://github.com/openai/baselines/blob/master/baselines/ppo2/run_mujoco.py) attempts to import `VecNormalize` and `DummyVecEnv`:
```
[…]
from baselines.common.vec_env.vec_normalize import VecNormalize
[…]
from baselines.common.vec_env.dummy_vec_env import DummyVecEnv
[…]
```
However, these modules are nowhere to be found in [vec_env](https://github.com/openai/baselines/tree/master/baselines/common/vec_env)

**Comment by rylz** [comment]
Similarly, baselines/ppo2/run_atari.py attempts to import VecFrameStack, which does not exist:

```baselines/ppo2/run_atari.py:    from baselines.common.vec_env.vec_frame_stack import VecFrameStack```

**Comment by joschu** [comment]
oops, should be fixed now
