### ISSUE TITLE
Failed building wheel for atari-py

### ISSUE THREAD

**Issue by Matuiss2** [openai/baselines#210]
I'm getting this error while trying to install it in python 3.6.3 - 64 bits on windows, I tried installing it by using pip3 install --upgrade baselines, the method on READ ME and pip install git+https://github.com/openai/baselines 

all of then led to the same error ```Failed building wheel for atari-py```
Any way to solve this?

**Comment by Matuiss2** [comment]
no one?

**Comment by krishpop** [comment]
check [stackoverflow](https://stackoverflow.com/questions/43517664/failed-building-wheel-for-atari-py#43537734)

**Comment by Matuiss2** [comment]
Ah, it says that the atari-py does not support windows and only supports python 2.7 and 3.5 I guess that's the reason. Oh well... you can close it, my bad.
