### ISSUE TITLE
Viewing a model in Tensorboard

### ISSUE THREAD

**Issue by akblissweb** [openai/baselines#217]
I'm using the train_cartpole and enjoy_cartpole examples in the DeepQ section.   How would I view my saved model (.pkl) in Tensorboard.   Is this possible ?

**Comment by olegklimov** [comment]
No it's not possible, you have to save tensorboard stuff after you create the model. It's not really hard to do.  In fact, just looking at the code that creates a model you'll have a better idea of what it does, compared to tensorboard with bubbles and arrows. Hope this helps!
