### ISSUE TITLE
Training time of PPO2

### ISSUE THREAD

**Issue by kkjh0723** [openai/baselines#220]
I run PPO2 mujoco in a system with a GTX1080. I changed nothing except that the environment is replaced to pybullet. 
I run the code with command: `python -m baselines.ppo2.run_mujoco`
However, it was not finished even after 2 or 3 days of learning. I forgot exactly how many steps run but I thought it took too much time and there should be something wrong (hopefully changing environment is not the reason). 

How long it takes to finish learning 1M steps with MLP policy in mujoco environment? (it should be depending on the system though)
And is the code implemented for multi-GPU system?

**Comment by sajattack** [comment]
Here it looks to me like run_atari is supposed to run for 10 million timesteps: https://github.com/openai/baselines/blob/ebb8afff2ebd560ba0edb7ac5bcf1fea18827bef/baselines/common/cmd_util.py#L53
But I've been running for a couple hours and surpassed that value. Perhaps there's a bug preventing it from stopping?

**Comment by olegklimov** [comment]
Hi @kkjh0723 . 

> multi-GPU

For continuous control, using GPU doesn't result in gains in speed. It may be faster on CPU.

For speed, please check out `ncpu = 1` and `DummyVecEnv` in `run_mujoco.py`. This can/should be replaced with SubprocVecEnv.


Hi @sajattack , from looking at the code, ppo2 seems to be using the limit on timesteps. This kind of code:

```
    nupdates = total_timesteps//nbatch
    for update in range(1, nupdates+1):
```
is unlikely to not work really. Please check out if you still have that bug.

**Comment by VVinayak** [comment]
I tried to run the atari file by spawning 8 processors in mpi. Approximately how much time does it take to complete training on a CPU?
