### ISSUE TITLE
A problem on TRPO implementation

### ISSUE THREAD

**Issue by jeasinema** [openai/baselines#222]
https://github.com/openai/baselines/blob/b05be68c55d416f7aa71f745aaf3c2999d83b83c/baselines/trpo_mpi/trpo_mpi.py#L177

I wonder if here we should use `oldpi` to sample trajs instead of using `pi`.

**Comment by BaiGang** [comment]
The trajectory segments are exactly sampled with `oldpi`.

As the assignment op does (
https://github.com/openai/baselines/blob/b05be68c55d416f7aa71f745aaf3c2999d83b83c/baselines/trpo_mpi/trpo_mpi.py#L215)
just after the sampling.
