### ISSUE TITLE
Pre-trained model performance issues?

### ISSUE THREAD

**Issue by donamin** [openai/baselines#228]
Hi
I'm loading the last snapshot of my trained network on hopper environment using this line for ppo2:

`model.load('[...]/baselines/logs/Hopper-v1/checkpoints/00048')`

But for some reason the eprewmean starts from zero as of not-trained networks and then becomes better after 50K timesteps. Shouldn't it start from the last reward mean of the saved model?

**Comment by donamin** [comment]
Update:
In case the question is not clear, here's a screenshot that shows episode reward mean plot for (1) learning from scratch (blue curve) and (2) loading the blue curve network and continuing learning (red curve)
![image](https://user-images.githubusercontent.com/4231500/33881026-2ed85170-df3c-11e7-97d2-b83817c2d259.png)

Can anyone tell me how to fix it? I think the red curve should start from where the blue curve has left off (around 600).

**Comment by olegklimov** [comment]
Hi @donamin . I'm pretty sure you should save and load observation scaling. Start from this line: `    env = VecNormalize(env)`
