### ISSUE TITLE
Inconsistent returns calculation across algorithms

### ISSUE THREAD

**Issue by bjkomer** [openai/baselines#232]
The way returns are calculated are currently different for each algorithm (averaged across different numbers of episodes/batches). This means the same policy will report different results depending on the algorithm. It would be nice if this was more consistent to help facilitate comparisons between algorithms.

PR #231 addresses the difference between ppo and trpo

**Comment by unixpickle** [comment]
The algorithms all spit out monitor files in a standard format with the true returns. The monitors are created by an environment wrapper (e.g. [here](https://github.com/openai/baselines/blob/master/baselines/ppo2/run_atari.py#L31)) so they are consistent across agents.
