### ISSUE TITLE
ImportError: Library "GL" not found

### ISSUE THREAD

**Issue by riyaazs** [openai/baselines#235]
Hi,
I get the following error when trying to run DQN baseline.
I have opengl already installed. and glxgears, glxinfo already work fine.
I am using python 3.5.
can someone please let me know how to fix this?

"python -m baselines.deepq.experiments.enjoy_cartpole"
gym.utils.reraise.ReraisedException: Error occured while running `from pyglet.gl import *`
The original exception was:

ImportError: Library "GL" not found.

**Comment by olegklimov** [comment]
That's not a bug in this library. Please create a test file that contains only `from pyglet.gl import *` and run it to reproduce this error in isolation. Also see dependencies for gym to install what is missing. (some python GL stuff)

**Comment by ziyangli** [comment]
I have the same problem.

```
Python 3.6.3 (default, Oct  6 2017, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyglet.gl import *
>>> gl_lib = pyglet.lib.load_library('GL')
>>> 
>>> 
```

**Comment by Deastan** [comment]
Hi everyone,

I have exactly the same issue as @ziyangli and same error message. Do someone find a solution ?

Kind regards, 
John

**Comment by KONPEITO1205** [comment]
Hi

I have almost same issue with @ziyangli .

If I run just only
from pyglet.gl import *
there's no error.

But if I run above line in rendering.py with gym.Wrapper, there's same import error.
Does anyone know how to fix or improve?

**Comment by ariel415el** [comment]
Thanks @Deastan !
adding **from pyglet.gl import** * in the main scriipt did the trick for me
