### ISSUE TITLE
reset_keywords in bench/monitor.py is non-functional

### ISSUE THREAD

**Issue by william-r-s** [openai/baselines#236]
Seems like reset_keywords in bench/monitor.py is non-functional. If you try to pass keyword arguments into the reset function, it fails with reset_kwargs in bench/monitor.py is non-functional. Looks like this is because the reset method of the Env class does not take keyword arguments (even though Wrapper._reset does take keyword arguments, it is only called through Env.reset)

**Comment by olegklimov** [comment]
Er... I'm not sure what you're trying to say. Wrapper is written with `**kwargs` to be agnostic about parameters. None of the environments have parameters in reset. Ah, I see, there is also `reset_keywords` in Monitor class. That looks like it's a mechanism to put some information into the first line of `.csv`. Well no, it's not supposed to be functional. If you need to pass parameters into your environment, just call any function of `env.unwrapped` or use your own fabric of environments.
