### ISSUE TITLE
warnings in cartpole example

### ISSUE THREAD

**Issue by ngc92** [openai/baselines#24]
The train_cartpole example generates the following warnings:
`  VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02
~/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
~/.local/lib/python3.5/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
`

**Comment by siemanko** [comment]
none of those prevent the code from working. Pull requests welcome! ;-)
