### ISSUE TITLE
Where are the stacking frames?

### ISSUE THREAD

**Issue by zhengwsh** [openai/baselines#243]
I do not found the implement of stacking (four) frames in atari games during training, could someone tell the exact lines in deepq ?

**Comment by phuongho43** [comment]
It's in the atari wrappers: https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers.py
and gets used to wrap the gym environment in the example:
https://github.com/openai/baselines/blob/master/baselines/deepq/experiments/run_atari.py

**Comment by zhengwsh** [comment]
@phuongho43 Thank you, i found it.
