### ISSUE TITLE
Try multiple actions on each step?

### ISSUE THREAD

**Issue by delaaxe** [openai/baselines#244]
I'm trying to use baselines to solve the [Halite 2 challenge](halite.io/learn-programming-challenge/)
At each time step (~200 max per game), you have to order multiple ship to go different planets.
I'd like to be able to receive multiple actions in my environment step() function so I can command instruct multiple ships to move on a single time step.

Is this possible using the Deep Q Learning package? Does it even make sense? Sorry if the question is not appropriate here.

**Comment by phuongho43** [comment]
I'm interested in this issue also. Maybe something like Deepmind's approach to Starcraft 2 (https://arxiv.org/abs/1708.04782) where it's a composite/parametrized function?

**Comment by wjaskowski** [comment]
If each ship has n possible actions and you have m ships, you have n^m
joint actions, which is usually infeasible to deal with directly. Here is a
hint how one could deal with that: https://arxiv.org/abs/1705.05035.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by olegklimov** [comment]
Multiple ships? That means you want to create multiplayer environment (not algorithm)? This repo is about published algorithms. I'd recommend to start with single-player environment if you are learning to do this kind of thing.
