### ISSUE TITLE
Possible memory leak while running DeepQ for Atari games ?

### ISSUE THREAD

**Issue by mathpluscode** [openai/baselines#247]
While running /baselines/deepq/experiments/run_atari.py I have problems of memory.
It keeps increasing until there's no memory left.
Does it normal?

My environment is
Ubuntu 16.04 (8G RAM)
python 3.5 + tensorflow 1.5 under anaconda virtual environment

Thanks in advance.

**Comment by phuongho43** [comment]
Maybe the replay buffer size is too large?

**Comment by olegklimov** [comment]
Hi @mathpluscode -- well 8G of RAM doesn't sound too high. You may have 12Gb of video memory, have you? Just for it to transfer data back and forth it may require memory on the same magnitude, plus the operating system has to reside somewhere... This `deepq` implementation is definitely able to finish its job on machines with more memory.

**Comment by mathpluscode** [comment]
Hi @olegklimov, thanks a lot for the reply. You are true, actually it works on another machine.
