### ISSUE TITLE
A2C stops(crashes?) with no error message after a couple million steps

### ISSUE THREAD

**Issue by zuoanqh** [openai/baselines#249]
Pretty much what the title says. I run the program, it looks fine, i go to sleep and check next day, it's stopped, i check the logs, it went okay for a couple million steps, everything progressing, and the logs just stops -- I tried >"log.txt" 2>&1 & to grab the stderr channel, the logs turned out the same. This happened twice, each ending on a different time. (exact same args)

**Comment by olegklimov** [comment]
Hi @zuoanqh sorry this is too broad to address. A lot of things could go wrong, including hardware issues. I can't remember things happening as you describe, so it's not common for this software to do this.

**Comment by zuoanqh** [comment]
I modified the code a little bit and the problem is gone. No idea why lol.
