### ISSUE TITLE
TypeError in custom_cartpole example

### ISSUE THREAD

**Issue by yconst** [openai/baselines#250]
I've tried running [the custom cartpole example](https://github.com/openai/baselines/blob/8c90f67560920224e466d0389ac1bbf46e00773c/baselines/deepq/experiments/custom_cartpole.py) on my own environment but it raises an exception:

    TypeError: list indices must be integers or slices, not NoneType

The culprit seems to be the expression `obs[None]` in [line 49](https://github.com/openai/baselines/blob/8c90f67560920224e466d0389ac1bbf46e00773c/baselines/deepq/experiments/custom_cartpole.py#L49).

**Comment by sajattack** [comment]
Possibly related to #269

**Comment by olegklimov** [comment]
Please try to force it to be numpy array. The `[None]` trick works only on numpy arrays.
