### ISSUE TITLE
what's the input state to the pre-trained pong agent?

### ISSUE THREAD

**Issue by evanthebouncy** [openai/baselines#253]
Is it only the current-frame of the game rather than the past 2 frames or the diff of the past 2 frames?

I am asking because I am wondering if the trained pong agent has any information on the velocity information (require the past 2 frames) or it is able to still converge to a good policy on a pure positional information (require only the current 1 frame).

thanks

**Comment by evanthebouncy** [comment]
seems like there were some FrameStack wrappers around the original environment to stack the last k frames. So it seems indeed these agents have velocity information.

**Comment by DanielTakeshi** [comment]
It's standard to stack four frames. This is what DeepMind and pretty much everyone else does by default
