### ISSUE TITLE
TRPO bug

### ISSUE THREAD

**Issue by NoListen** [openai/baselines#262]
I noticed that TRPO with `gaussian_fixed_var` didn't work on Ant-v1 while PPO1 could.

It was not reasonable. Thus, I checked the codes and found variable `logstd` was not included in [`var_list`](https://github.com/openai/baselines/blob/master/baselines/trpo_mpi/trpo_mpi.py#L126).

**Comment by NoListen** [comment]
TRPO worked on Ant-v1 when I add `logstd` to `var_list`.

**Comment by joschu** [comment]
Wow, good catch. Fixing

**Comment by joschu** [comment]
Fixed
