### ISSUE TITLE
Adapting to different environments?

### ISSUE THREAD

**Issue by sajattack** [openai/baselines#264]
How would I adapt these algorithms to different environments? I notice the run_mujoco.py files don't appear to have any mujoco-specific code. Is it as simple as specifying a non-mujoco environment with these?

**Comment by phuongho43** [comment]
I think they only work with gym environments but you can turn your environment of choice into a gym environment: https://github.com/openai/gym/tree/master/gym/envs#how-to-create-new-environments-for-gym

**Comment by olegklimov** [comment]
`run_*` files serve as rough approximation of environment needs. Some need convolutional layers, some don't, complexity can be very different and therefore batch sizes and training time.
