### ISSUE TITLE
Running mean-variance during first batches

### ISSUE THREAD

**Issue by timmeinhardt** [openai/baselines#266]
The implementation of the running mean and variance has the following `update` method which was inspired by [this](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Parallel_algorithm):
https://github.com/openai/baselines/blob/b5be53dc928bc19c39bce2a3f8a4e7dd0374f1dd/baselines/common/vec_env/vec_normalize.py#L69
While this works once the `self.count` is not zero as for the very first batch and then large enough compared to `batch_count` for the first number of batches the resulting reward in the `VecNormalize` peaks unnaturally high compared to later updates. Is this behaviour neglectable for the training of an agent or would it make sense to modify the `update` method and apply a different algorithm while `self.count` is not way larger then `batch_count`.

**Comment by olegklimov** [comment]
There are always some problems with scaling reward, or scaling observations. So the answer to your question is yes, that part can be problematic. But also never was a showstopper. Your best bet is to scale rew/obs to the scale known beforehand. (and if you compare it to this automatic scaling, you may assess the severity of the problem.)
