### ISSUE TITLE
Getting information from info doesn't seem to work anymore

### ISSUE THREAD

**Issue by simontudo** [openai/baselines#274]
Hey guys, 

I was trying to train SpaceInvaders by myself and got the following error message
`python -m baselines.deepq.experiments.atari.train --env SpaceInvaders`

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/username/baselines/baselines/baselines/deepq/experiments/atari/train.py", line 244, in <module>
    start_time, start_steps = time.time(), info['steps']
KeyError: 'steps'
```

Is it not possible anymore to access `info` like this? If so, it should be considered rewriting it. 
Has anybody else encountered this problem?

**Comment by zishanahmed08** [comment]
I faced the same issue

**Comment by phuongho43** [comment]
Here's my own version of train.py. I just modified it to keep track of steps and episode rewards like the simpler run_atari.py script. Kind of messy and I removed certain stuff I didn't need like the argparse and azure container but hope this helps as a reference.

[train_dqn_atari.txt](https://github.com/openai/baselines/files/1688046/train_dqn_atari.txt)

**Comment by zishanahmed08** [comment]
You could use the SimpleMonitor wrapper used [here](https://github.com/openai/baselines/blob/ppo-trpo/baselines/deepq/experiments/atari/train.py)

**Comment by cxxgtxy** [comment]
Yes. In fact, train.py is not consistent with the current code. 
You can do as https://github.com/openai/baselines/pull/218 .
If you are interested in Rainbow, please refer to https://github.com/openai/baselines/pull/251
