### ISSUE TITLE
AttributeError: module 'baselines.common.tf_util' has no attribute 'logit_bernoulli_entropy'

### ISSUE THREAD

**Issue by jangirrishabh** [openai/baselines#276]
The latest change to baselines.common.tf_util seems to break some parts of the existing other files.
the new tf_util has missing functions like logit_bernoulli_entropy and dense
Though logit_bernoulli_entropy is now defined in adversary.py it is still being referenced as U.logit....

**Comment by olegklimov** [comment]
OK I've fixed gail to the point it starts to learn something. But I'm not understanding exactly what it does, so I might have done something wrong. @jangirrishabh please feel free to fix more of gail code if you find it useful.
