### ISSUE TITLE
what's the detail means of the available models name?

### ISSUE THREAD

**Issue by chelan** [openai/baselines#29]
Greetings all! I have run "python -m baselines.deepq.experiments.atari.download_model". It listed some available models's name. But I'm in a puzzle about the detail means of model's name. For example, what the differences between "model-atari-alien-1","model-atari-alien-2",and "model-atari-alien-3", are they trained by dqn or double dqn? "model-atari-duel-alien-1" was trained with dueling double dqn or dueling dqn? what the detail about "model-atari-rb100000-test-seaquest-1", and the meaning of rb100000? What's more,how can I know the detail params were used to trained these models? Thanks!

**Comment by siemanko** [comment]
Check out how those results are parsed in: https://github.com/openai/baselines-results This might shed some light on the issue.

**Comment by DanielTakeshi** [comment]
@chelan By default, the models are trained with double DQN, not vanilla DQN. To answer the question about 1, 2, and 3, the notebook doesn't seem to explain explicitly but I'm pretty sure they ran with three random seeds for each setting.
