### ISSUE TITLE
HER requires 'mujoco_py

### ISSUE THREAD

**Issue by watts4speed** [openai/baselines#305]
I'm getting the following error when I try and run HER when RolloutWorker in imported:

ModuleNotFoundError: No module named 'mujoco_py'

I don't own a copy of mujoco.  Is there anyway this dependency could be removed?  I'm wanting to avoid forking out the ~$250 to try out the code.

Thanks,
Peter

**Comment by shauravg** [comment]
+1 from me. I just use the deepq model and this would require additional license + setup. For now I am sticking with 0.14 release, but would like to be able to receive updates in the future without having to install mujoco.

**Comment by DanielTakeshi** [comment]
Another problematic thing is that baselines requires Python 3, whereas the issues tracker over for mujoco_py recommends using a Python 2 version to fix some common installation errors.

**Comment by zacheberhart** [comment]
I'm having this issue as well. I tried removing the mujoco package (I don't think you need it for other environments?) from the code but that only caused additional issues.

**Comment by matthiasplappert** [comment]
You'll need MuJoCo if you want to use HER. If you don't want to use HER, you can safely only install Gym without the mujoco and robotics environments.

**Comment by zacheberhart** [comment]
Why do we need MuJuCo to use HER? Isn't it just a robotics environment? Wouldn't HER work fine on any other environments -- whether in gym, universe, or custom?

**Comment by DanielTakeshi** [comment]
@zacheberhart It should. However, the environments that they use HER for are with sparse goal rewards, and those are in the MuJoCo-style tasks (I assume their robotics environments use MuJoCo).

**Comment by gvgramazio** [comment]
> You'll need MuJoCo if you want to use HER. If you don't want to use HER, you can safely only install Gym without the mujoco and robotics environments.

Why do we need MuJoCo? If it's only for sparse goal rewards there are other environments in this style. Also, OpenAI released roboschool to replicate MuJoCo environments and it's a bit of nonsense that we could use this with MuJoCo but we can't with roboschool.
