### ISSUE TITLE
why subproc_vec reset the env when step returns done=True?

### ISSUE THREAD

**Issue by taochenshh** [openai/baselines#307]
I found out that in
https://github.com/openai/baselines/blob/master/baselines/common/vec_env/subproc_vec_env.py#L13
each process will automatically reset the env if done=True is returned. I am confused by this step. From my point of view, if the env is reset now, then the ob will be changed to the reset value. And (ob, reward, done, info) will not be consistent. Can anyone please explain this? Thanks.

**Comment by JulianoLagana** [comment]
Why is this closed? I believe this is still a problem.
