### ISSUE TITLE
How to set the randomness of the act during enjoy?

### ISSUE THREAD

**Issue by yongduek** [openai/baselines#31]
In the file `enjoy_cartpole.py`, the action is provided by 
``obs, rew, done, _ = env.step(act(obs[None])[0])``

When the outputs of `act(obs[None])[0]` were printed out, it seemed that it did not print out the same action and changed somewhat randomly even though the input sequence was the same.

How can it be set to work as the simple greedy action?
How can the rate of randomness can be controlled?

cheers,

**Comment by yongduek** [comment]
It is found in `deepq/build_graph.py`.
```
======= act ========

    Function to chose an action given an observation

    Parameters
    ----------
    observation: object
        Observation that can be feed into the output of make_obs_ph
    stochastic: bool
        if set to False all the actions are always deterministic (default False)
    update_eps_ph: float
        update epsilon a new value, if negative not update happens
        (default: no update)

    Returns
    -------
    Tensor of dtype tf.int64 and shape (BATCH_SIZE,) with an action to be performed for 
    every element of the batch.
```

* Deterministic action:  
``action = act(obs[None], stochastic=False)``

* `eps=0.5` :
``action = act(obs[None], update_eps=0.5)``

**Comment by siemanko** [comment]
Glad you managed to resolve the issue!
