### ISSUE TITLE
Bug in her.experiment.plot

### ISSUE THREAD

**Issue by JoyChopra1298** [openai/baselines#311]
When is the metadata.json created? I trained the model completely but no metadata.json was created.  And what does the smooth SMOOTH option do?

**Comment by sanjeevanahilan** [comment]
I just tried out HER as well yesterday and ran into this issue. Basically, the json file output is called 'params.json' not 'metadata.json'. If you change "with open(os.path.join(curr_path, 'metadata.json'), 'r')" to "with open(os.path.join(curr_path, 'params.json'), 'r')" and change "env_id = metadata['kwargs']['env_name']" to "env_id = metadata['env_name']", and similarly for replay_strategy, it should work. 

As for smooth, it seems to be a simple convolution which reduces epoch-to-epoch variability in the rewards making the overall trend clearer and hence prettier graphs (I assume). One might argue it's a little misleading perhaps but I imagine it's standard practice...

More worryingly, the training I've done thus far does not seem to replicate the results of Plappert et al., in the DDPG+HER with sparse rewards case (I have not modified any of the parameters). I am completing training on this now for one of the hand tasks by averaging over 5 seeds, and so will wait to see the results before raising an issue (I of course think it's brilliant that OpenAI make both environments and their code so accessible).

**Comment by JoyChopra1298** [comment]
@sanjeevanahilan Thanks for the detailed explanation. I also wasn't able to get good results in FetchPush. Then I realised OpenAI used 19 CPU cores for training while I was using only 1 GPU. So when I increased the number of epochs from 50 to 100, the agent learnt the environment.

**Comment by sanjeevanahilan** [comment]
@JoyChopra1298 No problem, glad I could help. The issue I'm having is when comparing the learning curves on my machine with the ones published on arxiv, so number of cores used shouldn't affect this result. I will open up an issue on this shortly.

Paper: https://arxiv.org/abs/1802.09464

**Comment by matthiasplappert** [comment]
Plotting addressed in https://github.com/openai/baselines/pull/319

For details on the `num_cpu` flag, see https://github.com/openai/baselines/issues/314
