### ISSUE TITLE
PPO for Continuous action space for atari

### ISSUE THREAD

**Issue by zishanahmed08** [openai/baselines#317]
Could someone please point me towards an PPO implementation for Continuous action space for atari(if it exists).
The existing implementation for Atari is for discrete action space.And the one for mujoco does not take images as observation space.basically my requirement is for an **Continuous action space with image as observation space**

I tried modifying the existing code for atari to convert into continous space with the below steps

1. In environment change  self.action_space = spaces.Box(np.array([0, 0]), np.array([+1, +1])) because my action space consists of 2 continuous action space for linear and angular velocity
2. Added a new class CnnPolicyContinous [here](https://github.com/openai/baselines/blob/8b3a6c20519a45a1387c7d23b98b55d5961f3403/baselines/ppo2/policies.py#L100) which takes ac_space.shape[0] as final layer 'pi'

But I get a wrongly shaped **a0 = self.pd.sample()** with shape (1,1) rather then the expected (1,2)

**Comment by nithin127** [comment]
Hi, did you get any implementations?
I'm working on an environment with **continuous action space and image observation space**; any leads, hyperparameters that you used would be great
