### ISSUE TITLE
HER, dealing with overload-allowed in mpirun commands

### ISSUE THREAD

**Issue by DanielTakeshi** [openai/baselines#325]
From this issue (https://github.com/openai/baselines/issues/324) I am successfully running the HER training script with 1-4 CPUs on a single machine (Ubuntu 16.04, Python 3.5.2, TensorFlow 1.5.0, one TitanX GPU). The number of CPUs seems to be 8 as I have a quad-core i7 Intel processor with hyperthreading:

```
(py3-tensorflow) daniel@titan:~/baselines$ ipython
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os, multiprocessing

In [2]: os.cpu_count()
Out[2]: 8

In [3]: multiprocessing.cpu_count()
Out[3]: 8
```

When I run with 5 or more CPUs, I get this message blocking the code from running:

```
(py3-tensorflow) daniel@titan:~/baselines$ python -m baselines.her.experiment.train --num_cpu 5
--------------------------------------------------------------------------
A request was made to bind to that would result in binding more
processes than cpus on a resource:

   Bind to:     CORE
   Node:        titan
   #processes:  2
   #cpus:       1

You can override this protection by adding the "overload-allowed"
option to your binding directive.
--------------------------------------------------------------------------
```

Just to be clear, where do I add `overload-allowed` in the code? I'm not sure where. I know in `baselines/her/util.py` there's a subprocess call to an `mpirun` command, but `mpirun --help` on the command line doesn't reveal `overload-allowed` as a valid argument.

**Comment by JoyChopra1298** [comment]
You can use -oversubscribe option. Refer  [this IBM doc](https://www.ibm.com/support/knowledgecenter/en/SSZTET_10.1.0/smpi02/smpi02_proc_affinity_oversub.html)
My code of `mpirun` in `baselines/her/util.py` looks like this.
```
args = [
            "mpirun",
            "-np",
            str(n),
            "-bind-to",
            "core",
            "-oversubscribe",
            sys.executable
        ]
```

**Comment by matthiasplappert** [comment]
Note that we use `-bind-to core`, which binds each MPI worker to a physical core, of which you only have 4 (your Intel CPU exposes 8 virtual ones but it really only has 4 physical ones).

As mentioned, you can override this but I would expect degraded performance. It may make sense to just get a large machine on a cloud provider like AWS, Azure, or GCE instead since they are really not expensive.
