### ISSUE TITLE
GAIL behavior cloning missing save_state bug

### ISSUE THREAD

**Issue by hzyjerry** [openai/baselines#335]
When running behavior_clone.py in GAIL, I get the following bug

```
File ".../baselines/baselines/gail/behavior_clone.py", line 76, in learn
    U.save_state(savedir_fname, var_list=pi.get_variables())
AttributeError: module 'baselines.common.tf_util' has no attribute 'save_state'
```

`save_state` should be referring to the utility function implemented in DQN

**Comment by hzyjerry** [comment]
A fix is adding this adding these two functions to  `baselines.common.tf_util`:

`def save_state(fname, var_list):
    os.makedirs(os.path.dirname(fname), exist_ok=True)
    saver = tf.train.Saver(var_list=var_list)
    saver.save(tf.get_default_session(), fname)

def load_state(fname, var_list):
    saver = tf.train.Saver(var_list=var_list)
    saver.restore(tf.get_default_session(), fname)
`

**Comment by pzhokhov** [comment]
the save_state and load_state methods will be added to common.tf_util shortly

**Comment by pzhokhov** [comment]
done now
