### ISSUE TITLE
Using multiple CPUs with HER fails

### ISSUE THREAD

**Issue by msieb1** [openai/baselines#336]
First of all, thanks for providing such a comprehensive baseline collection!

I am trying to reproduce the results with HER and I ran into the following error when trying to run it with more than 1 CPU (running it with one CPU works and I am sourcing a virtualenv):

-----

Using DDPG + HER for policy learning
Traceback (most recent call last):
  File "../baselines/baselines/her/experiment/train.py", line 9, in <module>
    from baselines import logger
ImportError: No module named 'baselines'
Traceback (most recent call last):
  File "..//baselines/baselines/her/experiment/train.py", line 9, in <module>
    from baselines import logger
ImportError: No module named 'baselines'

Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[32314,1],0]
  Exit code:    1

----

Is there possible something wrong with the mpicc installation?

**Comment by matthiasplappert** [comment]
The MPI code will launch multiple processes, so possibly your virtualenv is not correctly sourced in those? Maybe add a debug statement somewhere to see what python executable is being used after the MPI fork.
