### ISSUE TITLE
No module named util

### ISSUE THREAD

**Issue by tennenboke** [openai/baselines#343]
I had try many ways to install baselines,however they didn't work.mujoco-py has been installed,I wonder know why there is such mistake.Please share some solutions ,thanks a lot!!!

baselines$ pip install -e .
Obtaining file:///home/zlj/%E4%B8%8B%E8%BD%BD/baselines
Requirement already satisfied: gym[atari,classic_control,mujoco,robotics] in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
  gym 0.9.5 does not provide the extra 'robotics'
Requirement already satisfied: scipy in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: tqdm in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: joblib in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: zmq in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: dill in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: progressbar2 in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: mpi4py in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: cloudpickle in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: tensorflow>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: click in /usr/local/lib/python2.7/dist-packages (from baselines==0.1.5)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python2.7/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python2.7/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: atari_py>=0.1.1 in /usr/local/lib/python2.7/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: Pillow in /usr/local/lib/python2.7/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Requirement already satisfied: PyOpenGL in /usr/local/lib/python2.7/dist-packages (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
Collecting mujoco_py>=1.50 (from gym[atari,classic_control,mujoco,robotics]->baselines==0.1.5)
  Using cached mujoco-py-1.50.1.42.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j8QcDU/mujoco-py/setup.py", line 2, in <module>
        import importlib.util
    ImportError: No module named util
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j8QcDU/mujoco-py/

**Comment by JorgeCP7** [comment]
I have the same problem! I only need Atari environment but I don't know how to install it...

**Comment by qingzhouzhen** [comment]
Use python 3, do not use python2

**Comment by pzhokhov** [comment]
As @qingzhouzhen pointed out, you need to use python3 (specifically, I have tested it with python3.5 and 3.6). For general package sanity, we recommend using a virtualenv (this will also prevent conflicts between python2 and 3 if you are mainly using former on your machine).

To create and activate the virtualenv, run the following commands:

``` 
    pip install virutalenv
    virtualenv env --python=python3 
    . env/bin/activate
    
```
Whether python3 is being used in a current env can be tested by running `python --version`
After that, `pip install -e .` should succeed, and the installation can be tested using pytest runner as follows:

```
    pip install pytest
    pytest
```

Common installation problems include missing cmake, openmpi or (for ubuntu) zlib.
On mac os those can be installed via homebrew (https://brew.sh/) as follows:
```
    brew install cmake openmpi
```
On ubuntu:
```
    apt-get update && apt-get install cmake libopenmpi-dev zlib1g-dev
```

We'll include these instructions in the README as well.

**Comment by timkpaine** [comment]
I have a fork for python2 with tests passing [here](https://github.com/timkpaine/baselines), but its ugly (I.e. forcing named arguments). I will keep it in-sync for a little while, but as python2.7 is EOL anyway its not worth doing a PR.
