### ISSUE TITLE
PrioritizedReplayBuffer - assert alpha > 0?

### ISSUE THREAD

**Issue by RylanSchaeffer** [openai/baselines#345]
I'm confused why the `PrioritizedReplayBuffer` has the following statement:

`assert alpha > 0`

Why is this not `assert alpha >= 0`? I thought `alpha=0` is a permissible value that corresponds to uniform random sampling.

**Comment by pzhokhov** [comment]
@RylanSchaeffer you are right. We have changed the assert to alpha >= 0 and added some tests, closing the issue.
