### ISSUE TITLE
Initial observations are zero in A2C 

### ISSUE THREAD

**Issue by filipemtz** [openai/baselines#357]
In baselines/a2c/a2c.py, lines 98-100 are:
        self.obs = np.zeros((nenv, nh, nw, nc), dtype=np.uint8)
        self.nc = nc        
        obs = env.reset()

Shouldn't them be:
        self.obs = np.zeros((nenv, nh, nw, nc), dtype=np.uint8)
        self.nc = nc        
        self.obs[:] = env.reset()

as in PPO? 

In the current version, the obs variable is local and it's not used anywhere else in the code. 
The effect of this is that the first observation of the first episode will always be zero.

By the way, why are there copies of the same classes across the implementations of different methods? For example, the code above is part of the Runner class which is present in both, A2C and PPO. Is it to simplify the extraction of the code of a method from the rest of the code?

**Comment by unixpickle** [comment]
This does appear to be a bug, which is fixed in PPO.

The code duplication is not ideal (as you can see, since it leads to bug like this).

**Comment by pzhokhov** [comment]
the code duplication should be addressed now, closing the issue
