### ISSUE TITLE
Unable to download all pretrained models

### ISSUE THREAD

**Issue by abhibhav14** [openai/baselines#36]
When I try downloading any model with the dueling architecture, it downloads fine.
However, when I try downloading a model that does not use dueling, the download does not start and gets stuck as N/A.
The command I use is:
python -m baselines.deepq.experiments.atari.download_model --blob model-atari-prior-breakout-1 --model-dir /tmp/models
I have tried it on a couple of computers, and I get the same issue every time.

**Comment by GrachevArtem** [comment]
I use Python 3.6 and have 
`Segmentation fault (core dumped)`
when try use `python -m baselines.deepq.experiments.atari.download_model `

Any idea why?

**Comment by unixpickle** [comment]
this feature has been completely removed (#302)
