### ISSUE TITLE
PPO2 very slow

### ISSUE THREAD

**Issue by yun-long** [openai/baselines#360]
Why is it so slow on my computer when I use PPO2 to solve Mujoco problems? I have a quite good GPU,  GeForce 1070, with 8GB memory. 

trpo_mpi can run quite fast compared to PPO2.

**Comment by unixpickle** [comment]
How slow is it actually running (e.g. how many timesteps per second)?

**Comment by rrmenon10** [comment]
I am not able to find any difference in time taken while running PPO2 on my laptop and on a machine that has a GPU. Is this expected? On my laptop, PPO2 completes about 1M steps in 20-30 minutes.
