### ISSUE TITLE
HER: with --num_cpu 19, still unable to reproduce results from Plappert et al., 2018

### ISSUE THREAD

**Issue by ruizhaogit** [openai/baselines#365]
Hi guys @matthiasplappert @sanjeevanahilan ,

Reopen issue [#314](https://github.com/openai/baselines/issues/314):

I tried to run the script with --num_cpu 19, but it still cannot reproduce the results from Plappert et al., 2018, in the HandManipulateBlockRotateXYZ-v0 environment. While the results in HandManipulateEggFull-v0 get in line with the paper Plappert et al.

The command I use is: python baselines/her/experiment/train.py --num_cpu 19 --env_name HandManipulateBlock-v0 --n_epochs 200 --replay_strategy future

The results are:
![fig_handreach-v0](https://user-images.githubusercontent.com/18663623/38769931-3f7a23de-400b-11e8-8779-ac8b80a24cf3.png)
![fig_handmanipulatepen-v0](https://user-images.githubusercontent.com/18663623/38769932-3f93cd16-400b-11e8-87e2-4a8fdb75f045.png)
![fig_handmanipulateegg-v0](https://user-images.githubusercontent.com/18663623/38769933-3fb11b64-400b-11e8-93af-d738cba314b4.png)
![fig_handmanipulateblock-v0](https://user-images.githubusercontent.com/18663623/38769934-3fcd94ba-400b-11e8-8c20-09c15e19a62e.png)

Anyone gets similar results or know how to solve the problem?
Thank you!

Best,
Rui

**Comment by ruizhaogit** [comment]
Problem is solved using: python baselines/her/experiment/train.py --num_cpu 19 --env_name HandManipulateBlockRotateXYZ-v0 --n_epochs 200 --replay_strategy future

**Comment by Andrewtor** [comment]
I am also trying to reproduce the results. What kind of code version did you use? The gym, baselines, mujoco, mujoco-py, and MPI. Thanks.
