### ISSUE TITLE
PPO1 and A2C

### ISSUE THREAD

**Issue by Ashboy64** [openai/baselines#367]
In the PPO paper, it is detailed that 8 actors were used to generate experience in an A2C style method that was then used by the algorithm to find the optimal policy. Looking at the code in the PPO1 folder, I don't see anything that seems to create multiple workers/ environments and generate experience. Am I missing something obvious? Where's the code that was used to generate the results found in the paper? Thanks in advance for any help.

**Comment by unixpickle** [comment]
PPO1 uses MPI. That means that you should run the program with `mpiexec` or `mpirun`. Those commands create multiple instances of your process, and the processes communicate using methods on `MPI.COMM_WORLD`.
