### ISSUE TITLE
HER multi cpus mpi run error

### ISSUE THREAD

**Issue by Andrewtor** [openai/baselines#368]
Hi, could you provide more information about your MPI configuration in the HER experiments?

I met an error when run with 19 cpus instead of 1 cpus:

> WARNING:tensorflow:From /opt/anaconda/envs/rlkitgym0100/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
[mpiexec@dartrl] match_arg (./utils/args/args.c:122): unrecognized argument bind-to
[mpiexec@dartrl] HYDU_parse_array (./utils/args/args.c:140): argument matching returned error
[mpiexec@dartrl] parse_args (./ui/mpich/utils.c:1387): error parsing input array
[mpiexec@dartrl] HYD_uii_mpx_get_parameters (./ui/mpich/utils.c:1438): unable to parse user arguments
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main()
  File "/opt/anaconda/envs/rl/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda/envs/rl/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda/envs/rl/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda/envs/rl/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 180, in main
    launch(**kwargs)
  File "train.py", line 89, in launch
    whoami = mpi_fork(num_cpu)
  File "/home/xx/Dropbox/scripts/baselines/baselines/her/util.py", line 111, in mpi_fork
    subprocess.check_call(args, env=env)
  File "/opt/anaconda/envs/rl/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '19', '-bind-to', 'core', '/opt/anaconda/envs/rl/bin/python', 'train.py', '--num_cpu', '19']' returned non-zero exit status 255

I have tried install OpenMPI or MPICH

**Comment by ankeshanand** [comment]
Bumping this, I get the `unrecognized argument bind-to` error too!

**Comment by aman-tiwari** [comment]
I fixed the error by install OpenMPI 3.2.1 and changing the command to use the system installed MPI in `/usr/local/bin` instead of the one installed by conda (which is too old)

**Comment by pzhokhov** [comment]
as @aman-tiwari pointed out, the error is most likely old version of OpenMPI. The `--bind-to core` option should be available since OpenMPI 1.4. We are working on adding mpi version checks and defaulting to simpler arguments if `--bind-to core` does not work; however, for sanity sake, @Andrewtor , could you run `mpirun --version` and `mpirun -np 2 --bind-to core python -c "print 'hello world'"` and post here the outputs?

**Comment by pzhokhov** [comment]
in the latest master, if the `mpirun --bind-to core ` fails, the version without `--bind-to core` is tried.

**Comment by lukashermann** [comment]
I had the same problem with openmi 1.6.5-8, changing `--bind-to core` to `--bind-to-core` in `her/util.py` fixed it for me. This also works for newer MPI versions, although it is deprecated and probably won't work in the future.
