### ISSUE TITLE
PPO2 render after loading trained model

### ISSUE THREAD

**Issue by rohit497** [openai/baselines#381]
I tried using `env.render()` in the `learn()` function in `ppo2.py`, but it doesn't let me render an object of type 'DummyVecEnv'. I'm not sure how to just create a gym environment and pass in the outputs of `model.step` into it. Can someone help me with this problem?

Thanks!

**Comment by pzhokhov** [comment]
DummyVecEnv is an env wrapper that does not implement function `render()`, but for now you can get around that by doing `env.envs[0].render()` (assuming `env` is of the type DummyVecEnv`). We'll add forwarding of the render function soon.

**Comment by pzhokhov** [comment]
As for passing outputs of a model.step into environment, the following snippet should do it (observation shape is specific to Reacher-v2):
```
import gym 
    import numpy as np
    env = gym.make('Reacher-v2')
    obs = np.zeros((1,11))
    obs[:] = env.reset()
    while True:
        actions, _, _, _ = model.step(obs)
        obs[:], _, _, _ = env.step(actions)
        env.render()
```

**Comment by pzhokhov** [comment]
Beware, however, that, for instance, ppo2.run_mujoco.py trains the model on the normalized environment, and while such model can be plugged into bare mujoco environment, it will most likely not work correctly; you'll need to wrap up gym environment with VecNormalize and DummyVecEnv just as it is done in ppo2.run_mujoco.py (and for now you'll still need to go through `env.venv.envs[0].render(`) to render it)

**Comment by pzhokhov** [comment]
should be fixed now
