### ISSUE TITLE
[A2C] Bug zeroing out done observations?

### ISSUE THREAD

**Issue by MillionIntegrals** [openai/baselines#383]
In the a2c.py file, around line 118 we zero out observations from the environments that are done:
```python
            for n, done in enumerate(dones):
                if done:
                    self.obs[n] = self.obs[n]*0
```
and soon afterwards we override self.obs (old observations) with obs (new observations):

```python
            self.obs = obs
```

That seems like it's making the previous line a no-op. Were these supposed to go in reverse order, or maybe just the for loop should be deleted?

**Comment by sccrthlt** [comment]
Additionally it seems the dones are not being appended correctly inside the loop:

```def run(self):

mb_obs, mb_rewards, mb_actions, mb_values, mb_dones = [],[],[],[],[]

mb_states = self.states

for n in range(self.nsteps):
    actions, values, states, _ = self.model.step(self.obs, self.states, self.dones)
    mb_obs.append(np.copy(self.obs))
    mb_actions.append(actions)
    mb_values.append(values)
    mb_dones.append(self.dones)
    obs, rewards, dones, _ = self.env.step(actions)
    self.states = states
    self.dones = dones
    for n, done in enumerate(dones):
        if done:
            self.obs[n] = self.obs[n]*0
        self.obs = obs
        mb_rewards.append(rewards)
mb_dones.append(self.dones)```

`mb_dones.append(self.dones)` should be on the performed within the loop, not outside.

**Comment by DanielTakeshi** [comment]
@MillionIntegrals  I am confused about this as well.

In the newer version of the code this is put in the `a2c/runner.py` file.

https://github.com/openai/baselines/blob/master/baselines/a2c/runner.py

They do something similar in `acer/runner.py` which suggests this is quite deliberate.

**Comment by Griffithchiong** [comment]
confused as well...

**Comment by DanielTakeshi** [comment]
@pzhokhov  ? :)

**Comment by pzhokhov** [comment]
https://github.com/openai/baselines/pull/781

**Comment by pzhokhov** [comment]
merged, closing this

**Comment by Griffithchiong** [comment]
you are so cool!!
@pzhokhov @DanielTakeshi @MillionIntegrals
