### ISSUE TITLE
the commit 2 hours ago have issue with importing

### ISSUE THREAD

**Issue by ylyhlh** [openai/baselines#386]
from baselines.common.runners import AbstractEnvRunner
I think this leads to some error:
ImportError: No module named 'baselines.common.runners'

**Comment by henrykmichalewski** [comment]
This affects ppo2, acer and a2c.

**Comment by pzhokhov** [comment]
should be fixed shortly, when PR https://github.com/openai/baselines/pull/389 goes in.
