### ISSUE TITLE
frames vs. step in --num-timestep flag

### ISSUE THREAD

**Issue by shanlior** [openai/baselines#397]
Hi,
In most dqn related papers the graphs are plotted as the current test reward vs. frames seen by the agent.

The full training process is achieved by running for 200M Frames.
In you implementation of deepq, it is not clear whether the number of timesteps given in *--num-timesteps* is the same number as frames (**FRAMES=STEPS**), or if each timestep equals 4 frames (**FRAMES=4xSTEPS**).

The confusion's origin is the different wrappers used for skipframe and frame wrapping and that fact that *train_freq=4* in run_atary.py.

Can you please clarify?

Thanks in advance,
Lior

p.s.
Because DQN is an off-policy algorithm, I've added an online testing process that runs a series of test  epochs every defined number of steps. Tell me if it's needed as a pull request.

**Comment by unixpickle** [comment]
For all of the Atari baselines in this repo, we use the [MaxAndSkipEnv](https://github.com/openai/baselines/blob/9cf95a00542dc87b413e765d8c0fdcf0b1684cdc/baselines/common/atari_wrappers.py#L93) wrapper. This means that every timestep spans four frames. If train_freq=4, then there is an update once every four timesteps, or 16 frames.

As a historical note, at one point we converted the entire repository to use timesteps everywhere. Before that, it was really confusing to keep track of frames vs. timesteps.

Re: your p.s.: usually we don't take pull requests for experimental techniques, only for implementations of well-established algorithms.
