### ISSUE TITLE
HER- fatal error: mjmodel.h: No such file or directory

### ISSUE THREAD

**Issue by harjatinsingh** [openai/baselines#406]
I am using conda with python version 3.5.2 on ubuntu 14.04. I have been able to install baselines and run pytest. It says 9 tests passed. However when i do 

` python -m baselines.her.experiment.train
`
I get the following error. 

```
running build_ext
building 'mujoco_py.cymj' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/frc-
vision/anaconda3/lib/python3.5/site-packages/mujoco_py 
-I/home/frc-vision/.mujoco/mjpro150/include -I/home/frc-vision/anaconda3/lib/python3.5/site-packages/numpy/core/include
 -I/home/frc-vision/anaconda3/lib/python3.5/site-packages/mujoco_py/vendor/egl 
-I/home/frc-vision/anaconda3/include/python3.5m -c /home/frc-vision/anaconda3/lib/python3.5/site-packages/mujoco_py/cymj.c
 -o /home/frc-vision/anaconda3/lib/python3.5/site-packages/mujoco_py/generated/_pyxbld_
1.50.1.56_35_linuxgpuextensionbuilder/temp.linux-x86_64-3.5/home/frc-vision/anaconda3/lib/python3.5/site-packages/mujoco_py/cymj.o 
-fopenmp -w
/home/frc-vision/anaconda3/lib/python3.5/site-packages/mujoco_py/cymj.c:608:21: fatal error: mjmodel.h: No such file or directory
 #include "mjmodel.h"
                     ^
compilation terminated.
```

**Comment by pzhokhov** [comment]
Hi @harjatinsingh! The error message suggests you don't have mujoco installed (more accurately, you probably have mujoco_py python pacakge installed, but not mujoco library itself) You can get it (and a temporary license) from https://www.roboti.us/index.html (version 1.5.0), you'll also need to add $HOME/.mujoco/mjpro150/bin to $LD_LIBRARY_PATH. 
We'll add these instructions to README as well. Please reopen if installing mujoco does not help

**Comment by pzhokhov** [comment]
added the instructions to README
