### ISSUE TITLE
PPO2 value function clipping

### ISSUE THREAD

**Issue by fgvbrt** [openai/baselines#408]
Hello, I would like to ask question about clipping value function in realization of PPO2:
https://github.com/openai/baselines/blob/master/baselines/ppo2/ppo2.py#L32

Could you please explain intuition behind it, I found that in original PPO paper and implementation of PPO no such clipping was used.
Thanks in advance!.

**Comment by lgvaz** [comment]
Same intuition as clipping the policy, it is used to avoid big changes in the value network.
This is good because it helps to avoid overfitting on the most recent batch.
