### ISSUE TITLE
ppo1.run_humanoid RuntimeWarning: invalid value encountered in sqrt

### ISSUE THREAD

**Issue by jiameij** [openai/baselines#434]
hi~
i use ppo1 train Humanoid-v2 via  `mpirun -np 16 python -m baselines.ppo1.run_humanoid`
after 610 iterations, it returns the following error
```
/home/jmj/baselines_new/baselines/baselines/common/mpi_adam.py:35: RuntimeWarning: invalid value encountered in sqrt
  step = (- a) * self.m / (np.sqrt(self.v) + self.epsilon)
```
then it stops running
how can i solve it ?
thank you!

**Comment by jiameij** [comment]
i solved it

**Comment by kirk86** [comment]
it's good to say what you did in case others have the same issue, they can solve it!

**Comment by OhmySallyGarden** [comment]
Can you tell me how you solved it ?  Thanks
