### ISSUE TITLE
Pop-Art implementation ? 

### ISSUE THREAD

**Issue by yuanzhanghu** [openai/baselines#44]
Looks like we've done a clip wrapper for reward, which might be not very good:
```
class ClippedRewardsWrapper(gym.RewardWrapper):
    def _reward(self, reward):
        """Change all the positive rewards to 1, negative to -1 and keep zero."""
        return np.sign(reward)
```
I found this article has done a DDQN without clip operation: 
https://arxiv.org/pdf/1602.07714.pdf
Do we have any plan to implement DDQN based on this article?

**Comment by benelot** [comment]
You could just pull-request a modified version of the original DDQN version? That is how contributions work :)

**Comment by yuanzhanghu** [comment]
Got it.  Thanks much!  I am still new to AI area.  i would contribute when i be able to. :)
