### ISSUE TITLE
Cannot run deepq.experiments.run_atari with gpu?

### ISSUE THREAD

**Issue by pengsun** [openai/baselines#448]
Hi,

I encountered "segmentation fault" when running
```
python -m deepq.experiments.run_atari
```
with tensorflow-gpu==1.8 

However this command goes well with pure cpu tensorflow==1.8

Wondering if it is possible to run deepq experiments with gpu?

**Comment by DanielTakeshi** [comment]
It's definitely possible, I've done it.

**Comment by pengsun** [comment]
Hi thanks for your quick reply! Sorry, this may be caused by the incorrect installation of tensorflow-gpu. I can do it on another machine. closing.
