### ISSUE TITLE
LSTM Model

### ISSUE THREAD

**Issue by Mazecreator** [openai/baselines#45]
Are there any thoughts how an LSTM model could be used with Baselines?  I have some time series data and would love to use an RNN of sorts.  I might be able to work on this project but would appreciate a point in the right direction to properly integrate the "LSTM STATE" and data series.

It seems like there are 2 complexities:
1) LSTM STATE needs to be captured in replace for random playback (might not need playback with LSTM)
2) Time horizon data for BP over time needs to be handled as well

**Comment by siemanko** [comment]
I am sorry, but we cannot assist you on this issue. Good luck in your LSTM adventures!
