### ISSUE TITLE
ppo2: explained variance will decrease  to negative sometimes

### ISSUE THREAD

**Issue by scotthuang1989** [openai/baselines#454]
I run atari with ppo2, I notice that  explained variance is not stable, sometimes **it even decease to negative number which indicate that value function is worse than random guess**.  Even though policy gradient is a stochastic process, it doesn't look good.  Is this a normal behavior or it suggest that we can do better with hyper parameter search? I try some combination of hyper parameters, no changes.

![image](https://user-images.githubusercontent.com/5325686/42025920-5d2adbd0-7af8-11e8-8392-484f65551365.png)

**Comment by andytwigg** [comment]
Try replotting with .rolling(10000).mean()

**Comment by scotthuang1989** [comment]
moving average will certainly become smoother, but what I wonder is why there are some such big regression? I
