### ISSUE TITLE
Fail to load pretrained checkpoints

### ISSUE THREAD

**Issue by LinZichuan** [openai/baselines#46]
Hi,
I try to load a part of variables from download models. But it turns out ```Key Not Found Error```, even though the variables names are same. The only difference is the ':0' in tails, but I think it does not matter since this is added automatically by tensorflow op.

Here is what I read from checkpoints and the Key not found error log.

![keynotfound](https://user-images.githubusercontent.com/10752083/27893720-1f5f42f0-623a-11e7-80f7-e8bf7208729e.PNG)

**Comment by siemanko** [comment]
I think this might be related to your `tensorflow` version.
