### ISSUE TITLE
why every algo reimplements policies that show up in others as well

### ISSUE THREAD

**Issue by kirk86** [openai/baselines#460]
Hi and thank you for this work!. I have noob question. I was wondering why in every algorithm folder there are policies re-implemented. Isn't that a redundancy. Wouldn't it be better to have just one folder with all the policies implemented once and then accordingly use them in every algo, trpo, a2c,..,etc.?

**Comment by araffin** [comment]
Similar to #445 #413 #400

**Comment by pzhokhov** [comment]
@kirk86 you are absolutely right - it is a redundancy, and it is not great. We have recently merged a large refactor that eliminates most of the code duplication in policies and network building.
