### ISSUE TITLE
Running PPO2 on multiple CPU cores 

### ISSUE THREAD

**Issue by akhilsanand** [openai/baselines#463]
hello,
I would like to run the ppo2 implementation on multiple cpu cores. I am able to run it using mpirun command. But I am not sure if it is the right way to do with ppo2. 
what is the right way to run ppo2 on multiple cpu cores?

**Comment by 20chase** [comment]
Hi,

I write a multiple process version ppo2: https://github.com/20chase/baselines/blob/master/baselines/ppo2/run_roboschool.py
 
Hope it can help you :)

**Comment by akhilsanand** [comment]
Hello, thanks for the link. 
This must be very helpful
