### ISSUE TITLE
LSTM policy in ppo2

### ISSUE THREAD

**Issue by tgangwani** [openai/baselines#465]
File - https://github.com/openai/baselines/blob/master/baselines/ppo2/policies.py

In the LstmPolicy class (line 57), nenv is calculated as follows:
`nenv = nbatch // nsteps`

But the constructor could be passed the minibatch-size instead of the batch-size (as is done in line 18, ppo2.py), making the nenv computation incorrect.

**Comment by scotthuang1989** [comment]
I think the meaning of nenv in this context is :  number of environments per mini batch.

**Comment by pzhokhov** [comment]
@scotthuang1989 correct
