### ISSUE TITLE
MaxAndSkipEnv is calculating the max over the last two time steps only

### ISSUE THREAD

**Issue by kashif** [openai/baselines#47]
The MaxAndSkipEnv as it is right now is skipping over the `skip` observations and calculating the total reward properly over all the time steps, but the max over the observations is only calculated over the last 2 observations regardless of skip size. Is this intentional? 

One could move the max_frame line into the loop and then it could use the deque of size 2 to keep track of the max over all the skip time step.

**Comment by siemanko** [comment]
Yes it is, for consistency with original publication.
