### ISSUE TITLE
Baseline code for policy gradient methods?

### ISSUE THREAD

**Issue by miriaford** [openai/baselines#48]
This repo is awesome! It saves me a lot of time implementing DQN myself. It's a real lifesaver. Many thanks to OpenAI! 👍 

When do you plan to release Baseline code for policy gradient methods, like TRPO, A3C, and ACER? It's been almost 2 months since the DQN release. I look forward to the next announcement!

**Comment by siemanko** [comment]
(cc @Newmu @joschu )

**Comment by miriaford** [comment]
@siemanko @Newmu @joschu any follow-up? Thanks!

**Comment by ViktorM** [comment]
Will be happy to know the answer too. Last time, more than a month ago when I asked about DDPG and TRPO updates the reply was that soon there will be some news.

**Comment by miriaford** [comment]
@ViktorM That's a great point. It'd be super nice to have a DDPG baseline too. Thanks for bringing it up.

I desperately need a state-of-the-art A3C implementation now. There are many open-source repos online, but none of them is proven to match or even approach the original paper. It looks like OpenAI Baseline has really high demand. 

Hope the team can reply ASAP. @Newmu @siemanko @joschu

**Comment by joschu** [comment]
General etiquette for open-source software:
feature request = OK. 
repeatedly pinging authors = not OK.

**Comment by joschu** [comment]
We plan to eventually release a set of implementations of policy gradient algorithms, but the exact timing is TBD.
