### ISSUE TITLE
A2C code for MuJoCo

### ISSUE THREAD

**Issue by LinZichuan** [openai/baselines#493]
Hi dear developers, when will A2C code for MuJoCo be available?

**Comment by pzhokhov** [comment]
Hi @LinZichuan ! It is already in PR https://github.com/openai/baselines/pull/490, so you can use it from the branch. Some examples of using A2C with mujoco are here: https://github.com/openai/baselines/blob/peterz_migrate_rlalgs/README.md
Keep in mind that we have not optimized the a2c hyperparamters for mujoco yet, so it may not work all that great out of the box.

**Comment by pzhokhov** [comment]
Should be available in master now. Closing this.
