### ISSUE TITLE
Where is run_atari?

### ISSUE THREAD

**Issue by hellandhansen** [openai/baselines#509]
Am heartwrought as I'm missing some of my dearly beloved files!

1-2 days ago run_atari (along with a spate of other files) disappeared from several of the baseline algorithms; ppo2 and trpo just to name a few.

I guess this is part of an update process?

**Comment by pzhokhov** [comment]
merged the PR, closing this - please reopen if there are more questions about this.

**Comment by hellandhansen** [comment]
Thank you!

I’m impressed with the speed of reply and thoroughness.

And great that you’ve refactored the code so it’s easier to compare algorithms, less fiddling.

Kind regards

Bjørn A. Helland-Hansen


On 17 August 2018 at 02:10:23, pzhokhov (notifications@github.com) wrote:

merged the PR, closing this - please reopen if there are more questions about this.
