### ISSUE TITLE
CompileError GCC - can't run several files

### ISSUE THREAD

**Issue by hellandhansen** [openai/baselines#510]
Hail, all ye coders!

Running

mpirun -np 1 python -m baselines.ppo1.run_atari

Fails: distutils.errors.CompileError: command '/usr/local/bin/gcc-6' failed with exit status 1

To run some other files I had to downgrade from GCC 8 to GCC 6.

How could this error be rectified?

Thanks for all the great work.

**Comment by hellandhansen** [comment]
Hi, pzhokhov!

Have tried out the new refactored commands, and they seem to run well on my computer.

I wonder if you have some input into this situation:

In Python, I’ve made a game that I want the algorithms to run and try to master. Basically, I'm outputting a Numpy array (instead of a screen), and rewards. Input some “keystrokes” that I’m converting into variables.

I guess this is what happens under the hood with Gym and Universe. So it should be simple.

I wrote an alternative make_atari to make this work, but the other components didn’t play nice, even though I provided palatable answers to their function calls.

There must be some easier way to do this?

Looking forward to hearing from you,

kind regards

Bjørn A. Helland-Hansen


On 16 August 2018 at 22:23:30, pzhokhov (notifications@github.com) wrote:

Hi @hellandhansen ! Two things - I'd recommend using ppo2 over ppo1. PPO2 now comes with MPI support, whereas ppo1 will eventually get sunset. To run the same command with ppo2, use
mpirun -np 1 python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 (you can use whatever atari environment you are interested in)
That being said, I am happy to help with your issue :)
Could you provide more info though? Version of python, OS, full stacktrace of the error, output of pip freeze ?

**Comment by pzhokhov** [comment]
Hi @hellandhansen! From what I understand, you are making your own environment (game), which outputs observations as numpy array and takes discrete actions (keystrokes). Yes, you are right, that is pretty much how gym and gym-retro work, however, there are several layers of wrappers to provide various additional functionality (stacks of frames, logging etc). To skip all that complexity and start with something, I'd recommend looking at the unit tests test_identity (https://github.com/openai/baselines/blob/master/baselines/common/tests/test_identity.py) - it tests if the RL algorithm can learn to output the observations,
test_mnist ((https://github.com/openai/baselines/blob/master/baselines/common/tests/test_mnist.py) - and the corresponding test environments in baselines/common/tests/envs (https://github.com/openai/baselines/tree/master/baselines/common/tests/envs) - those are intentionally stripped of all complex parts.
