### ISSUE TITLE
ImportError using run_atari in ACKTR 

### ISSUE THREAD

**Issue by R1ckF** [openai/baselines#511]
Hi all,
When I try to start run_atari.py to train ACKTR I get the following error.

python -m  baselines.acktr.run_atari --env PongNoFrameskip-v4  --num-timesteps 1000000
Error:
baselines/acktr/run_atari.py", line 9, in <module>
    from baselines.common.policies import cnn
ImportError: cannot import name 'cnn'

When I look in baselines/common/policies file there is also not a definition for 'cnn' located in the file.
What am I missing? Thx!

**Comment by pzhokhov** [comment]
Hi @R1ckF ! acktr/run_atari is now obsolete (we'll delete it soon, in the mean time - sorry about the confusion), please use:
`python -m baselines.run --alg=acktr --env PongNoFrameskip-v4 --num_timesteps=1e6`

**Comment by R1ckF** [comment]
thx its working now!
