### ISSUE TITLE
[PPO2] No module named baselines.ppo2.run_mujoco

### ISSUE THREAD

**Issue by DamienLancry** [openai/baselines#512]
Dear OpenAI and Community,

First of all, amazing job with this repository.
Second of all, the implementation of ppo2 seems to have been updated very recently. there used to be a run_mujoco.py, but not anymore. I supposed the file defaults.py is supposed to produce the same results but it is not clear how to use it. 
And the readme file has not been updated and still says to use python -m  baselines.ppo2.run_mujoco which obviously produce the aforementioned error (in the title).
Would be great to have a readme updated or to have run_mujoco.py and run_atari.py back!

Cheers!

**Comment by pzhokhov** [comment]
updated readme's in this PR: https://github.com/openai/baselines/pull/514

**Comment by pzhokhov** [comment]
should be fixed now
