### ISSUE TITLE
There is a clerical error 

### ISSUE THREAD

**Issue by XFFXFF** [openai/baselines#517]
There is a clerical error 
[](https://github.com/openai/baselines/tree/master/baselines/deepq)
command`python -m baselines.run --alg=deepq --env=CartPole-v0 --load_apth=./cartpole_model.pkl --num_timesteps=0 --play`. 
'load_apth' should be 'load_path'

**Comment by DanielTakeshi** [comment]
Easier to do this with a pull request for them

**Comment by pzhokhov** [comment]
should be fixed now
