### ISSUE TITLE
LSTM/RNN code is confusing

### ISSUE THREAD

**Issue by nahrak** [openai/baselines#525]
Hi! I couldn't run an LSTM policy with a custom DummyVecEnv, so I decided to try this:
_python run.py --env SeaquestNoFrameskip-v0 --network cnn_lstm --num_env 1_

Was getting the same error as with a custom env:
_AssertionError: Bad input for recurrent policy: batch size 32 smaller than nsteps 128_

Taking 1 minibatch works with a built-in environment:
_python run.py --env SeaquestNoFrameskip-v0 --network cnn_lstm --num_env 1 --nminibatches=1_

But this doesn't work with a custom DummyVecEnv:
_InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'ppo2_model/pi/Placeholder_2' with dtype float and shape [1]_

The documentation says to look in baselines.common/policies.py/lstm for documentation how to run recurrent policies, but there is nothing about recurrent nets or LSTMs in there.

**Comment by pzhokhov** [comment]
Added extra docs. Closing this, feel free to reopen if some unclarity remains.

**Comment by nahrak** [comment]
Hi!

I believe the number of minibatches should not be linked to the number of environments. Unless minibatches have a special meaning in PPO, a single environment can produce any number of minibatches, because they only serve for aggregating gradients. If PPO has 1024 steps, we may want to feed 16 batches of 64 examples each to the GPU or 32 batches of 32 examples, etc.

**Comment by pzhokhov** [comment]
you are correct; however, in the current implementation the batch of data of the size nenv * nsteps is cannot be split in more than nenv minibatches when recurrent policy is used. In other words,  the slicing along the time axis is not implemented for recurrent policies (for non-recurrent ones the temporal structure does not matter, so it works ok as is). We'll fix that eventually, but it is not very high in priority. On the other hand, if you have a fix and a test, feel free to submit a PR :)
