### ISSUE TITLE
Support for continuous action spaces

### ISSUE THREAD

**Issue by jaredweiss** [openai/baselines#53]
Would love to see DQN for continuous action spaces implemented (https://arxiv.org/pdf/1509.02971.pdf)

**Comment by ngc92** [comment]
I think they are planning on adding DDPG (the algorithm you linked too). For now, depending on your problem, you might get away with just using a discretized version of the action space by wrapping the environment. I have a few useful wrappers here: https://github.com/ngc92/space-wrappers. To make an env usable for DQN you should wrap it like `env = FlattenedActionWrapper(DiscretizedActionWrapper(env, RESOLUTION))`. Be aware that this only works if th dimension of the continuous action is low, as this results in RESOLUTION**DIM many discrete actions.

**Comment by siemanko** [comment]
We will add this in future releases.

**Comment by crizCraig** [comment]
https://github.com/openai/baselines/tree/master/baselines/ddpg
