### ISSUE TITLE
Low GPU usage

### ISSUE THREAD

**Issue by Seraphli** [openai/baselines#54]
When I tried to run `train.py` in the `atari` folder, I found the ETA reached 16 days after a few minutes and the usage of GPU was quite low.

**Comment by kenfehling** [comment]
I'm trying to run with a GPU also. Did you try looking at `nvidia-smi`? Does it show any processes?

**Comment by Seraphli** [comment]
Yes, of course there is a python process.
![image](https://user-images.githubusercontent.com/1586755/28396770-158dafae-6d30-11e7-968a-58f8bf053027.png)
And here is GPU usage.
![image](https://user-images.githubusercontent.com/1586755/28396806-5a5002ae-6d30-11e7-8a57-d23dfd7cace8.png)
And here is ETA after three minutes.
![image](https://user-images.githubusercontent.com/1586755/28396927-07212f58-6d31-11e7-9963-a169b720243c.png)

**Comment by siemanko** [comment]
If do `pip freeze` do you see `tensorflow-gpu` ? If you see both `tensorflow` and `tensorflow-gpu` delete `tensorflow`

**Comment by siemanko** [comment]
Closing as it's mostly a `tensorflow` issue, unlikely baselines.

**Comment by Seraphli** [comment]
I found both `tensorflow` and `tensorflow-gpu` in the environment. I deleted `tensorflow` and the ETA drop down to 3 days.
