### ISSUE TITLE
Integration with Google Cloud ML Engine

### ISSUE THREAD

**Issue by shauravg** [openai/baselines#55]
We are using the deepq.mlp class to implement reinforcement learning and would like to host it on Google Cloud ML engine which requires the model to be exported into SavedModel format. My understanding of it is at a beginner level but I believe that requires us to pass the tf Session and input and output tensors to SavedModel builder. 

I am not sure exactly how to get those from the deepq.mlp class or if there is maybe a much better way to do all this. Any help would be apreciated!

**Comment by siemanko** [comment]
Hi Shauravg,

This kind of use case is supported by `simple.py`. Check out `train_pong.py` and `enjoy_pong.py` for train and restore behavior. If your use case is different, try understanding what those files do and copy the pattern. Alternatively try StackOverflow. 

Good luck!

**Comment by shauravg** [comment]
Using pickle to save/restore vs SavedModel is entirely different but I will try SO. Thanks.
