### ISSUE TITLE
Distributed training discrepancy from original PPO paper

### ISSUE THREAD

**Issue by lancerane** [openai/baselines#550]
The original PPO paper describes aggregating data from multiple workers and optimizing the surrogate loss with minibatch size <= NT, where N is the number of workers and T is the number of timesteps per worker. However, in the baselines implementation, it seems that gradients are calculated on a worker-by-worker basis, and then averaged. One negative consequence of this, as far as I can see, is that the minibatch size must be <= T, which might be problematic in distributed settings where the number of workers is large and so, for data efficiency, T is small. Is this an intentional change from the original paper?

**Comment by pzhokhov** [comment]
In the non-MPI version of PPO data is aggregated across workers, just like you are describing. Specifically, the batch size is set to N * T in the current implementation, here: https://github.com/openai/baselines/blob/bdd4d385a654f65f9cc5b7c43eba3d5f27574a8b/baselines/ppo2/ppo2.py#L224
(nenv is number of environments = number of parallel workers that interact with environment)

In the MPI version, same thing happens, except gradients are also aggregated across the MPI workers (by using MpiAdamOptimizer, herehttps://github.com/openai/baselines/blob/bdd4d385a654f65f9cc5b7c43eba3d5f27574a8b/baselines/ppo2/ppo2.py#L52), so the effective batch size is Nmpi * N * T. 
In either case, the batch size is not limited by T. 

Hope this helps!

**Comment by lancerane** [comment]
Hi @pzhokhov, thanks for your reply.

I had been using, and was referring to PPO1, but I see now that this has been made obsolete. 
I’ll have a look at PPO2.

Thanks, 
Lance
