### ISSUE TITLE
HalfCheetah Benchmark Results for TRPO - Unable to reproduce

### ISSUE THREAD

**Issue by fps7806** [openai/baselines#559]
Hi everyone,

I checked out the same commit from the benchmarking results on the README and was not able to reproduce the results stated for the HalfCheetah-v2 environment for TRPO.

PPO2 got about 5-6k, the highest I was able to get with the TRPO implementation was 20 (I tried a few hyperparameters).

Any insights on what could be causing such a low score after millions of steps?

Thanks,
Felipe

**Comment by fps7806** [comment]
It seems like the TRPO version is returning the discounted/normalized reward instead of real reward while PPO2 extracts the reward from the info['episode']

**Comment by pzhokhov** [comment]
Correct. The logging is different in ppo2 / trpo_mpi (this is something to be fixed), however, you can compare the results between the two by using output of a Monitor environment wrapper (that's how we compared the data in the benchmark results here: https://htmlpreview.github.com/?https://github.com/openai/baselines/blob/master/benchmarks_mujoco1M.htm).
