### ISSUE TITLE
Updates to `deepq ` make it not runnable any more!

### ISSUE THREAD

**Issue by wumo** [openai/baselines#564]
Several updates to module deepq make the `deepq.learn` signature changes and `deepq.load` non-exist. Thus `train_mountaincar.py` and `enjoy_cartpole.py` cannot run anymore (so does `enjoy_mountaincar.py`,`enjoy_pong.py`,`enjoy_retro.py`).

Please fix these bugs.

**Comment by pzhokhov** [comment]
merged, closing this
