### ISSUE TITLE
There is no save model option for DDPG

### ISSUE THREAD

**Issue by Kuppharish** [openai/baselines#566]
I'm using the DDPG API to run my environment. It trains perfectly fine when I use the command:
`python -m baselines.ddpg.main`
But I can't store the progress as the API doesn't have a save option. I tried to edit the code to get the desirable results. I added `tf.train.Saver.save(sess)` at the end of the code and` tf.train.Saver.restore` after the  `with U.single_threaded_session() as sess:` statement which throws out following error:
>> TypeError: restore() missing 1 required positional argument: 'save_path'

Please tell me what is going wrong here, Thanks.

**Comment by iSaran** [comment]
Take a look at #162, it is the same issue.

**Comment by brendenpetersen** [comment]
@Kuppharish Keep in mind that even if you save/restore the policy as in #162, if `normalize_observations=True` (the default value), then the mean/std used for normalization will not be recoverable.
