### ISSUE TITLE
Where can I find the command --play corresponding code definition and analysis

### ISSUE THREAD

**Issue by huangjiancong1** [openai/baselines#577]
Where can I find the command[ --play](https://github.com/openai/baselines/blob/23b2333238e9850a230f0fa3ce95497d4c6c418b/baselines/common/cmd_util.py#L105) corresponding code definition and analysis

**Comment by pzhokhov** [comment]
look into baselines/baselines/run.py file, specifically, here: https://github.com/openai/baselines/blob/1f99a562e3df9eaad96b59d44677006ef54ca1c2/baselines/run.py#L218
