### ISSUE TITLE
Atari wrappers deprecated?

### ISSUE THREAD

**Issue by miriaford** [openai/baselines#58]
Quick question: 

Why are the [atari wrappers](https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers_deprecated.py) deprecated? Do you plan to add the non-deprecated version of wrappers soon?

**Comment by siemanko** [comment]
Likely.

**Comment by miriaford** [comment]
@siemanko Would you mind telling me what's the problem with the current implementation? Is there anything that impacts performance? Thanks!

**Comment by siemanko** [comment]
Both have bad performance.
