### ISSUE TITLE
sum-tree unit test

### ISSUE THREAD

**Issue by miriaford** [openai/baselines#59]
According to the doc, `find_prefixsum_idx` method should return `the highest index i in the array such that sum(arr[0] ... arr[i-1]) <= prefixsum`.

If this is true, shouldn't the test return 4 instead of 3? 
https://github.com/openai/baselines/blob/master/baselines/common/tests/test_segment_tree.py#L44

and here, the test should also return 4 instead of 3
https://github.com/openai/baselines/blob/master/baselines/common/tests/test_segment_tree.py#L60

When `i == 4`, `sum(arr[0]+arr[1]+arr[2]+arr[3] <= 4.0` holds.

**Comment by siemanko** [comment]
I think that's correct. I'd gladly accept a pull request with a fix that makes API and tests consistent.

**Comment by miriaford** [comment]
@siemanko the edge case is a singular case, so I added a simple if statement on top. https://github.com/openai/baselines/pull/69
