### ISSUE TITLE
Two links in readme don't work

### ISSUE THREAD

**Issue by hellandhansen** [openai/baselines#590]
In repo-wide readme, two links lead me to the Tatooine desert. I am a Star Wars fan, but right now I'd like to read... :-)

Example 1. PPO with MuJoCo Humanoid...

See docstrings in **common/models.py** for description of network parameters for each type of model, and docstring for **baselines/ppo2/ppo2.py/learn()** for the description of the ppo2 hyperparamters.

**Comment by pzhokhov** [comment]
thanks! Should be fixed now
