### ISSUE TITLE
Why the her/experiment take so little memory of GPU?

### ISSUE THREAD

**Issue by huangjiancong1** [openai/baselines#594]
command
`python train.py --num_cpu=2`

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P0    N/A /  N/A |    967MiB /  4042MiB |     11%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1150      G   /usr/lib/xorg/Xorg                           452MiB |
|    0      2214      G   compiz                                        94MiB |
|    0      2754      G   ...equest-channel-token=150694301499696969   120MiB |
|    0     21071      C   /home/huang/venv/bin/python                  149MiB |
|    0     21072      C   /home/huang/venv/bin/python                  149MiB |
+-----------------------------------------------------------------------------+

```
I use `ppo2` to train is take my full memory,but `her` take just a little.
How can i use my all memory to learning with `her/experience`?

**Comment by huangjiancong1** [comment]
Means how to make the most of my GPU space to learn

**Comment by DanielTakeshi** [comment]
I don't know if this is the same as when I was using the HER code, but that code is for the CPU, not the GPU.

**Comment by pzhokhov** [comment]
currently, HER code uses small fully-connected nets which would not speed up much from using GPU.
Also HER benefits from aggregating updates over multiple workers (the --num_cpu parameter) which stabilizes updates and helps learning; and mutliple MPI workers with the same GPU is (at least to my experience) something that does not work well. It is probably possible to change HER code to run in the vecenv regime (where multiple processes generate observations, and gradients are computed in the master process, potentially on a GPU) - this way, you can have large enough batch sizes to justify usage of GPU. This is planned in the HER refactor, but I don't have a timeline for that at the moment.
