### ISSUE TITLE
Install Baselines

### ISSUE THREAD

**Issue by Nara0731** [openai/baselines#610]
When I install Baseline,
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-p2poh3ol/mpi4py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zamwt56h/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-p2poh3ol/mpi4py/

**Comment by DanielTakeshi** [comment]
Please give far more information about your machine and setup so that others can reproduce or trace your steps.

**Comment by Nara0731** [comment]
fixed problems,
thanks

**Comment by ruyueshuo** [comment]
new comer here, same problem.how did you fix that?

**Comment by ruyueshuo** [comment]
new comer here, same problem.how did you fix that?

> fixed problems,
> thanks
