### ISSUE TITLE
PPO2:Total reward keep declining over time

### ISSUE THREAD

**Issue by falsemail** [openai/baselines#613]
When training my model with PPO2 in my environment,  my policy my mean total reward(sum reward from episode with gamma) keep declining over time. I can't really figure out how to let it grow. 
my reward is between -12 and 6
using 5 layers fc 
batch size 300 from 10 independent environments， each episode 6000 step

Could it be that I need to run the algorithm for a longer time before the total reward starts growing?

**Comment by pzhokhov** [comment]
Hi @falsemail! 
Could you provide more details? Is that one of the gym environments or your custom environment? What's that observation / action space size ? Batch size 300 from 10 independent environments - does that mean 300 per environment (so total 3000), or 30 per environment? How long do you train it for (total number of timesteps)? Do the average returns grow at all in the beginning (in the beginning, policy behaves pretty much randomly; so after training does it behave better or worse than random)? 
If the action space is continuous (Box), what's the range?

**Comment by falsemail** [comment]
> Hi @falsemail!
> Could you provide more details? Is that one of the gym environments or your custom environment? What's that observation / action space size ? Batch size 300 from 10 independent environments - does that mean 300 per environment (so total 3000), or 30 per environment? How long do you train it for (total number of timesteps)? Do the average returns grow at all in the beginning (in the beginning, policy behaves pretty much randomly; so after training does it behave better or worse than random)?
> If the action space is continuous (Box), what's the range?

Thanks very much. I have find the reason which because of a bug in my custom environment.
