### ISSUE TITLE
PPO2 does not converge on LunarLander-v2

### ISSUE THREAD

**Issue by aliostad** [openai/baselines#627]
Hi,

I am running simple run out of the box on LunarLander but after hours I do not see sign of a convergence, mean reward keeps around -200.

```
python -m baselines.run --alg=ppo2 --env=LunarLander-v2 --network=mlp --num_timesteps=2e7
```

I can supply more information and add to the issue but wondering if this is a known issue.

**Comment by aliostad** [comment]
Sorry, it did. In the end.

**Comment by Fluidy** [comment]
Use "--value_network=copy" so that the value network parameters are not shared with the policy network. This can increase the convergence speed for LunarLander-v2.

**Comment by Fluidy** [comment]
> Hi,
> 
> I am running simple run out of the box on LunarLander but after hours I do not see sign of a convergence, mean reward keeps around -200.
> 
> ```
> python -m baselines.run --alg=ppo2 --env=LunarLander-v2 --network=mlp --num_timesteps=2e7
> ```
> 
> I can supply more information and add to the issue but wondering if this is a known issue.

Use "--value_network=copy" so that the value network parameters are not shared with the policy network. This can increase the convergence speed for LunarLander-v2.
