### ISSUE TITLE
ppo2 atari not converging with policy=mlp 

### ISSUE THREAD

**Issue by andytwigg** [openai/baselines#631]
Using `env=PongNoFrameskip-v4` and ppo2 with `policy=cnn`, it converges as expected. Using `policy=mlp` however it does not appear to make any progress (using same hyperparams). I would have expected it to converge but more slowly (in #steps) than cnn. Have I missed something?

**Comment by pzhokhov** [comment]
atari tasks are image based, and it is notoriously hard to process images with fully-connected layers. It is likely possible to make ppo2 with network=mlp, but will probably require some hyperparameter tuning. First thing I would try is increasing number of timesteps per batch (nsteps).

**Comment by andytwigg** [comment]
Okay. Closing as I'm not going to try to make this work with mlp.
