### ISSUE TITLE
ddpg lose main.py

### ISSUE THREAD

**Issue by SongleChen2015** [openai/baselines#650]
DDPG lose main.py, so it can't run.

**Comment by zhkmxx9302013** [comment]
I have the same question.

**Comment by zhkmxx9302013** [comment]
@SongleChen2015 It can be debugged by using the  `python -m baselines.run --alg=ddpg --env=your_env --network=your_ network`. I think the readme in ddpg is wrong.

**Comment by SongleChen2015** [comment]
@zhkmxx9302013 thank you very much!
