### ISSUE TITLE
Scope issues

### ISSUE THREAD

**Issue by manuel-delverme** [openai/baselines#651]
I'm trying to load several models in the same run but the TF scope is being reused
adding a ```with tf.variable_scope(...)``` was not enough since some of the scopes are hardcoded

this code is enough to crash, i would like to keep both models in memory.
``` 
model1 = baselines.trpo_mpi.trpo_mpi.learn(network='mlp', env=env, total_timesteps=0,)
model2 = baselines.trpo_mpi.trpo_mpi.learn(network='mlp', env=env, total_timesteps=0,)
```
how can i achieve that without modifying the baselines code?

**Comment by manuel-delverme** [comment]
#547 suggests using a new graph but I need both models alive.

**Comment by DanielTakeshi** [comment]
@manuel-delverme I handle loading models in the same run by making different scopes when the models are formed during training time (so basically, it's about ensuring that training is done by wrapping the entire model creation inside a tf scope).

**Comment by pzhokhov** [comment]
Yeah, I could not find the way of doing it in the current implementation. However, with small changes (https://github.com/openai/baselines/pull/655) this can be done as in the follows:

```
import tensorflow as tf
import gym
from baselines.trpo_mpi.trpo_mpi import learn
from baselines.common.tf_util import make_session

env = gym.make('CartPole-v0')
make_session(make_default=True, graph=tf.Graph()); model1 = learn(network='mlp', total_timesteps=0, env=env)
make_session(make_default=True, graph=tf.Graph()); model2 = learn(network='mlp', total_timesteps=0, env=env)

# both models are alive: 
print(model1.step(env.observation_space.sample())
print(model2.step(env.observation_space.sample())
```

**Comment by pzhokhov** [comment]
tested for a2c, acktr, ppo2, trpo_mpi; this will not work for deepq though

**Comment by pzhokhov** [comment]
closing this (but opened a separate issue to enable multiple DQN / DDPG models to be present at the same time: https://github.com/openai/baselines/issues/656)
