### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by GbengaOdesanmi** [openai/baselines#657]
Trying to perform loading and visualizing models after saving but having this error, please help:

~/baselines$ python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=0 --load_path=~/models/pong_20M_ppo2 --play
Logging to /tmp/openai-2018-10-18-09-19-51-290852
Logging to /tmp/openai-2018-10-18-09-19-51-336942
env_type: atari
Training ppo2 on atari:PongNoFrameskip-v4 with arguments 
{'nsteps': 128, 'nminibatches': 4, 'lam': 0.95, 'gamma': 0.99, 'noptepochs': 4, 'log_interval': 1, 'ent_coef': 0.01, 'lr': <function atari.<locals>.<lambda> at 0x7ff1ba0b80d0>, 'cliprange': <function atari.<locals>.<lambda> at 0x7ff18a13e158>, 'load_path': '~/models/pong_20M_ppo2', 'network': 'cnn'}
2018-10-18 09:19:54.366293: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gbenga/baselines/baselines/run.py", line 239, in <module>
    main()
  File "/home/gbenga/baselines/baselines/run.py", line 213, in main
    model, env = train(args, extra_args)
  File "/home/gbenga/baselines/baselines/run.py", line 79, in train
    **alg_kwargs
  File "/home/gbenga/baselines/baselines/ppo2/ppo2.py", line 307, in learn
    model.load(load_path)
  File "/home/gbenga/baselines/baselines/common/tf_util.py", line 349, in load_variables
    loaded_params = joblib.load(os.path.expanduser(load_path))
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 590, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gbenga/models/pong_20M_ppo2'

**Comment by pzhokhov** [comment]
sounds like the model was not saved successfully... could you provide the code / output of the run that was supposed to save the model?

**Comment by GbengaOdesanmi** [comment]
I am just trying to start with openai baseline experiment and i really dont know how to save the training and visualize it, please help

**Comment by pzhokhov** [comment]
If you run the following: 
```
python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=1e5 --save_path=models/pong_100k_ppo2
```
that should train the model using ppo2 for 100k steps and save it to models/pong_100k_ppo2.
Then you can load that model and visualize it playing pong via
```
python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=0 --load_path=models/pong_100k_ppo2 --play
```
(note that after 100k steps it won't be very good, you'll need around a 1M timesteps for it to become about as good as the scripted opponent in Pong, and about 2-3 M to get significantly better)
Hope this helps; please post here if something still does not work for you.

**Comment by GbengaOdesanmi** [comment]
This was what I used that brought the error, meanwhile I tried to create a path and rerun it from the beginning, using the same path i created but now having this error


---------------------------------------
| approxkl           | 2.6987669e-11  |
| clipfrac           | 0.22827148     |
| eplenmean          | 1.65e+03       |
| eprewmean          | 20.9           |
| explained_variance | 0.996          |
| fps                | 194            |
| nupdates           | 19531          |
| policy_entropy     | 0.70607346     |
| policy_loss        | -7.7020377e-07 |
| serial_timesteps   | 2499968        |
| time_elapsed       | 9.81e+04       |
| total_timesteps    | 19999744       |
| value_loss         | 0.00016490358  |
---------------------------------------
(tensorflow) gbenga@gbenga-Lenovo:~/baselines$ python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=0 --save_path=~/home/gbenga/models/pong_20M_ppo2
Logging to /tmp/openai-2018-10-20-10-26-38-325132
Logging to /tmp/openai-2018-10-20-10-26-38-371439
env_type: atari
Training ppo2 on atari:PongNoFrameskip-v4 with arguments 
{'nsteps': 128, 'nminibatches': 4, 'lam': 0.95, 'gamma': 0.99, 'noptepochs': 4, 'log_interval': 1, 'ent_coef': 0.01, 'lr': <function atari.<locals>.<lambda> at 0x7f16f5e47510>, 'cliprange': <function atari.<locals>.<lambda> at 0x7f16c6abf598>, 'network': 'cnn'}
2018-10-20 10:26:41.387868: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

**Comment by GbengaOdesanmi** [comment]
I have solve the above  error but now having this error please help

benga@gbenga-Lenovo:~/baselines$ python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=0 --save_path=~models/pong_20M_ppo2
Logging to /tmp/openai-2018-10-20-14-55-02-182734
Logging to /tmp/openai-2018-10-20-14-55-02-231206
env_type: atari
Training ppo2 on atari:PongNoFrameskip-v4 with arguments 
{'nsteps': 128, 'nminibatches': 4, 'lam': 0.95, 'gamma': 0.99, 'noptepochs': 4, 'log_interval': 1, 'ent_coef': 0.01, 'lr': <function atari.<locals>.<lambda> at 0x7fc485165378>, 'cliprange': <function atari.<locals>.<lambda> at 0x7fc4527360d0>, 'network': 'cnn'}
Traceback (most recent call last):
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gbenga/baselines/baselines/run.py", line 239, in <module>
    main()
  File "/home/gbenga/baselines/baselines/run.py", line 213, in main
    model, env = train(args, extra_args)
  File "/home/gbenga/baselines/baselines/run.py", line 79, in train
    **alg_kwargs
  File "/home/gbenga/baselines/baselines/ppo2/ppo2.py", line 306, in learn
    model = make_model()
  File "/home/gbenga/baselines/baselines/ppo2/ppo2.py", line 305, in <lambda>
    max_grad_norm=max_grad_norm)
  File "/home/gbenga/baselines/baselines/ppo2/ppo2.py", line 37, in __init__
    with tf.variable_scope('ppo2_model', reuse=tf.AUTO_REUSE):
AttributeError: module 'tensorflow' has no attribute 'AUTO_REUSE'

**Comment by pzhokhov** [comment]
@GbengaOdesanmi which version of tensorflow are you using? Could you run `pip freeze | grep tensorflow` and post here the output of that? Looks like AUTO_REUSE was a valid option since at least tf 1.4 (https://www.tensorflow.org/versions/r1.4/api_docs/python/tf/variable_scope), if you are using older version, I would recommend upgrading (in fact, current version of baselines will throw an error if you try to install it with tensorflow that old).

**Comment by GbengaOdesanmi** [comment]
(tensorflow) gbenga@gbenga-Lenovo:~$ pip freeze | grep tensorflow
tensorflow==1.1.0

**Comment by pzhokhov** [comment]
I see... yes, baselines requires tensorflow of version 1.4 or above. You can get the latest version via `pip install tensorflow --upgrade`

**Comment by GbengaOdesanmi** [comment]
Thanks
