### ISSUE TITLE
Arguments 'network' and 'seed' are not documented in the docstring of the `learn` function of deepq.py

### ISSUE THREAD

**Issue by JulianoLagana** [openai/baselines#659]
Both the arguments `network` and `seed` are not documented in the docstring of the [`learn` function](https://github.com/openai/baselines/blob/ef96f3835b34ae59ba6d668ffa3befeed60af6fa/baselines/deepq/deepq.py#L95) of `deepq.py`. Additionally, the function's docstring contains a reference to an inexistent argument `q_func` (outdated).

**Comment by pzhokhov** [comment]
Fixed, thanks!
