### ISSUE TITLE
How to use baselines without proprietary mujoco

### ISSUE THREAD

**Issue by ccarterc** [openai/baselines#662]
Can't install the baselines without purchasing a mujoco license even though I don't want to use physics mujoco algs.

**Comment by pzhokhov** [comment]
should be fixed now: https://github.com/openai/baselines/pull/661

**Comment by saeedmoazami** [comment]
Hi,
I have the same problem,
Can not install baselines, and don't need mujoco

Can you please instruct me to solve this problem?

**Comment by cdyangbo** [comment]
Use source to install, not pip.
1. git clone https://github.com/openai/baselines
2. python setup.py install
