### ISSUE TITLE
Regarding computations of HER transitions.

### ISSUE THREAD

**Issue by abhayraw1** [openai/baselines#668]
What I could understand by reading the HER paper was that computing HER transitions for an episode would be just changing the `desired_goal` value of a particular experience (or memory) by that experience's `achieved_goal`.
This could be easily done by sampling a bunch of transitons from the replay buffer and making their `desired_goal` to be equal to their respective `achieved_goal`.
The implementation however in the file [her.py](https://github.com/openai/baselines/blob/games/master/baselines/her/her.py) is quite complex to understand where the code first samples a bunch experiences (not the whole episode is taken for her as far as I could tell). Then some random experiences are selected, from the ones generated above, to be used for HER. The values for `desired_goal` are then made equal to their respective `achieved_goal` which seems okay. I have the following 2 questions :
1. The `episode_batch['o']` and `episode_batch[`o_2`]` differ in shapes and hence when we sample the experiences from this line of code  [(This line here)](https://github.com/openai/baselines/blob/games/master/baselines/her/her.py#L29) there is a descrepency introduced within the experience. That is to say that `episode_batch['o']`, `episode_batch[`o_2`]`, `episode_batch['ag']` and `episode_batch[`ag_2`]` now don't point the same experiences.     
```python
transitions = {key: episode_batch[key][episode_idxs, t_samples].copy()
                       for key in episode_batch.keys()}
```
Shouldn't it be an issue because the `reward_params` is calculated using the peice of code below, using `ag2` and the `DDPG.store_episode` takes the values of using only the keys `["o", "g", "o_2", "ag"]` and the computations are done using only `["o", "g", "ag"]`? The respective `_2` variables are used for stats only which is stated in the comments but shouldn't values of keys (`"o", "ag"`) be equal to their corresponding `"_2"` counterparts?
2. Wouldn't it be better to just sample once and select the transitions for HER rather than sampling twice from the data: first for the transitions to be used for training and secondly for introducing HER.

**Comment by mehdimashayekhi** [comment]
@abhayraw1 for your second point, I think the idea for current implementation is to have a generalize implementation, meaning if ```replay_k``` is set to zero, we sample as regular we do for ```ddpg```. ```her_indexes``` will be empty. That's why they are separated. 

I agree with your first point though, there is a discrepancy. Also, I don't understand in ```_sample_her_transitions``` here https://github.com/openai/baselines/blob/bcde04e71078d82f9eb989e7198e711b219df2bd/baselines/her/her.py#L52 why are we using ```ag_2```why not ```ag```? Appreciate any response

**Comment by pzhokhov** [comment]
@machinaut @fjwolski @mandrychowicz any thoughts?

**Comment by abhayraw1** [comment]
> @abhayraw1 for your second point, I think the idea for current implementation is to have a generalize implementation, meaning if `replay_k` is set to zero, we sample as regular we do for `ddpg`. `her_indexes` will be empty. That's why they are separated.  

@mehdimashayekhi I think a simple approch would be to take some fraction (`future_p`) of the episode batch for generating HER transitions, which would be zero when `replay_k` is set to zero.
https://github.com/openai/baselines/blob/bcde04e71078d82f9eb989e7198e711b219df2bd/baselines/her/her.py#L15

The only difference that I see is that in the current implementation all the transitions aren't being used from the `episode_batch`  even in the case of `replay_k` being `0`.

Also, the snippet of code below produces transitions in which a particular experience may be repeated many times. This is because there is no dependency between `episode_idxs` and `t_samples`. A simple case would be `episode_idxs = [1, 1, 0]` and `t_samples = [0, 0, 0]`. This would include the first experience from the second rollout to be included in the `transitions` twice. 
https://github.com/openai/baselines/blob/bcde04e71078d82f9eb989e7198e711b219df2bd/baselines/her/her.py#L26-L30

**Comment by lfelipesv** [comment]
You are right @abhayraw1. The problems related in your last answer happens. Did you change something on the implementation?

I also want to add that the future_p variable is also only used to the percentage of transitions that are sampled for generating 'her' transitions and it is kind of unrelated to the 'future' sampling strategy.

It would be also interesting to change the implementation to have a relationship between the transition sample and the related episode. In this way it would be possible to do more interesting strategies to calculate rewards taking into consideration the whole episode in non-markovian tasks and add credit assignment algorithms.

**Comment by abhayraw1** [comment]
@lfelipesv I couldn't understand the complex implementation choice by the authors for generating her transitions, so I went on to

**Comment by abhayraw1** [comment]
@lfelipesv I couldn't understand the reason behind this implementation used by the authors for creating HER transitions. They are also not very clear as to what `future_p` stands for in their publication. 
However, I went on to implement a simple workaround to this. It's not perfect, but if you have any queries, hit me up.
You can find it [here](https://github.com/abhayraw1/DDPG/blob/ddpg-her/ddpg.py#L66-L71)

https://github.com/abhayraw1/DDPG/blob/32be7a2a66e4c5be7801d89ce7e43c1e6c382689/ddpg.py#L66-L71
