### ISSUE TITLE
Could you explain how to execute PPO and TRPO?

### ISSUE THREAD

**Issue by wonchul-kim** [openai/baselines#67]
There is readme explaining all the process to execute deepqn algorithm.

However, there is no such thing for PPO and TRPO....

Could you please explain how to execute PPO and TRPO?

**Comment by ViktorM** [comment]
@wonchul-kim I think a good starting point can be to take a look into run_mujoco.py or run_atari.py
You can see there a number of parameters used. In 
```
def main():
    train('Hopper-v1', num_timesteps=1e6, seed=0)
```
You can write a name of the environment you want to run. Also you can modify train function to add more training parameters into it that later can be exposed to the command line.

To run Atari you should also set num_cpu to 1.

**Comment by wonchul-kim** [comment]
Thanks for your reply!!

I've looked through your code and study... However, I keep getting error messages.. .when i run it...

my computer environment is ubuntu16.04 and python2.7

The error message i got is this:
Traceback (most recent call last):
  File "run_mujoco.py", line 3, in <module>
    from baselines import bench
ImportError: cannot import name bench

when i typed " python run_mujoco.py"


I checked the bench folder and __init__.py ..... I don't think there is a problem... but not sure..

Could you help me...?

**Comment by andrewliao11** [comment]
use python 3, instead

**Comment by wonchul-kim** [comment]
I typed "python3 run_mujoco.py"
then the below came up
 
Traceback (most recent call last):
  File "run_mujoco.py", line 2, in <module>
    from baselines.common import set_global_seeds, tf_util as U
ImportError: No module named 'baselines'

**Comment by andrewliao11** [comment]
not sure about how you install the package, yet maybe try add the baselines into your PYTHONPATH?

**Comment by wonchul-kim** [comment]
What I have done is that I downloaded the entire code and just typed "python run_mujoco.py"
Is there anything that has to be done before running it?

**Comment by shijcnju** [comment]
@wonchul-kim 
`import sys

sys.path.append('your baselines's parent folder')`

**Comment by Amathlog** [comment]
Typical Python2/Python3 conflict. Just use `pip3 install baselines ` or `python3 -m pip install baselines `

`pip install *` install by default for python2

**Comment by wonchul-kim** [comment]
I have already installed baselines by pip install baselines

**Comment by Amathlog** [comment]
> pip install * install by default for python2
You installed it for python2 not python3. Read my reply again

**Comment by wonchul-kim** [comment]
Is baselines based on python3??? 

If not, i want to use it with python2.7, because all of work I've done is by python2.7.

**Comment by Amathlog** [comment]
Located in baselines setup.py:
`if sys.version_info.major != 3:
    print("This Python is only compatible with Python 3, but you are running "
          "Python {}. The installation will likely fail.".format(sys.version_info.major))`

So yes, only python3

**Comment by wonchul-kim** [comment]
Thank you!!  So,,,  version is the problem,,,,  


Sinece you are more experienced than I am, is python3 better than python2??  I am just worried about compatibility things,,,,

**Comment by Amathlog** [comment]
It's an evolution of the language. It is newer and use new things. The first change you'll see is that print is now a function
Python2:
`print "Hello World!`
Python3:
`print("Hello World!")`
but there is a lot more, and it's not really the topic of this thread ^^
See there : https://docs.python.org/3/howto/pyporting.html

**Comment by wonchul-kim** [comment]
Thank you for your advice!!!  

I will try to use it!!   

Thank you!!!

**Comment by wonchul-kim** [comment]
Thank you for your reply...

However, there still came up the same error:
Traceback (most recent call last):
  File "run_mujoco.py", line 3, in <module>
    from baselines import bench
ImportError: cannot import name 'bench'

after i installed with 'sudo python3 install baselines' and typed 'python3
run_mujoco.py'.....

I really.... have no idea....

2017-07-26 23:45 GMT+09:00 Adrien LOGUT <notifications@github.com>:

**Comment by DanielTakeshi** [comment]
@wonchul-kim To avoid worrying about Python2 vs Python3 compatibility issues, make separate virtual environments, one for each version. Alternatively (as I do) make separate conda environments. I have one conda environment which I created specifically for Python 3 and TensorFlow 1.2 material.

**Comment by silverjoda** [comment]
For the 'cannot import name 'bench'' issue you can try adding
export PYTHONPATH="${PYTHONPATH}:/home/<yourpathtobaselines>/baselines" 
to ~/.bashrc and then sourcing bashrc. Worked for me.
Also you should be using python3 for baselines. 
When installing with pip I write "sudo pip3 install xxxx" when installing for python3.
