### ISSUE TITLE
Can not execute PPO and TRPO

### ISSUE THREAD

**Issue by shijcnju** [openai/baselines#68]
Can PPO or TRPO execute? 
I tried my best but failed.
Thank you~

**Comment by jiamings** [comment]
I think you should use the source directly instead of using the pip install command

**Comment by ViktorM** [comment]
I used pip install and it worked for me. @shijcnju, I replied to you in a another issue. If you post an error log our advices can become more precise.

**Comment by shijcnju** [comment]
I met this problem if I used pip  install  @ViktorM 

Traceback (most recent call last):
  File "run_atari.py", line 5, in <module>
    from baselines import bench
ImportError: cannot import name

**Comment by shijcnju** [comment]
Now I can run trpo and ppo from source code, but I'm confused what 'Monitor' do.
`env = bench.Monitor(env, osp.join(logger.get_dir(), "%i.monitor.json" % rank))`
I seems that trpo and ppo can run without this sentence

**Comment by ViktorM** [comment]
@shijcnju I had the error with import bench, but solved it just by adding baselines to pythonpath if I remember correctly. The pip install worked quite well for me and it was the smallest of my issues. for example run_mujoco.py can't be run as Gym hasn't moved yet to the latest mujoco 1.50 version. I've created a Box2d run_bipedal_walker.py script for training bipedal walker and it looks like, according to the reward it behaves and converge well - I've got a reward 210 after 1e6 steps. After more steps it'll be fully solved. But I still haven't managed to find how to enable rendering or get the results saved and loaded.

**Comment by zdx3578** [comment]
no  bench class or def bench。

  File "run_atari.py", line 11, in <module>
    from baselines import bench
ImportError: cannot import name 'bench'

**Comment by silverjoda** [comment]
I also had the bench import issue and resolved it after adding it to pythonpath:
export PYTHONPATH="${PYTHONPATH}:/home/....../baselines"

**Comment by joschu** [comment]
I think I fixed these issues in a recent commit.
