### ISSUE TITLE
pkg_resources.get_distribution('tensorflow') isn't strict

### ISSUE THREAD

**Issue by JEdward7777** [openai/baselines#686]
On commit c0fa11a3a730dcf987040ea131461ccd74e7da7b setup.py changes from checking tensorflow version number by checking 
`tensorflow.__version__`
which is 1.12.0-rc1
to checking
`pkg_resources.get_distribution('tensorflow').version`
which is 1.12.0rc1
which fails StrictVersion regular expression check because the rc strip operation misses the suffix without the dash.
Execute the following in Google's colab notebook to see this problem:

```
#tensorflow.__version__ works
from distutils.version import StrictVersion
import tensorflow, re
print( tensorflow.__version__ )
print( StrictVersion(re.sub(r'-rc\d+$', '', tensorflow.__version__) ) )

#pkg_resources.get_distribution('tensorflow').version blows up
import pkg_resources
tf_pkg_name = 'tensorflow'
tf_pkg = pkg_resources.get_distribution(tf_pkg_name)
print( tf_pkg.version )
print( StrictVersion(re.sub(r'-rc\d+$', '', tf_pkg.version)) )
```

With this error baseline no longer installs in a Google colab notebook.

**Comment by JEdward7777** [comment]
Ok, I found a solution.  If the dash in the sub is followed by a question mark, then the sub can still strip off the rc# on the end even with the dash missing.

**Comment by JEdward7777** [comment]
Here is a patch expressing the suggested edit.  I haven't tested it yet.  Finagling things into colab is tricky.  But making the dash optional in the rc suffix stripper doesn't look like it could cause any harm.
[strictversion-fix.txt](https://github.com/openai/baselines/files/2522043/strictversion-fix.txt)

**Comment by pzhokhov** [comment]
confirmed, should be fixed now (google colab notebooks also have a problem of missing mpi, I am working on separating MPI from dependencies)
