### ISSUE TITLE
normalize_observations=True not working with MPI-parallelized PPO2

### ISSUE THREAD

**Issue by brendenpetersen** [openai/baselines#695]
First of all, I'm very glad to see the unified algorithm/policy API, as I've been able to successfully create my own callback function that works across all algorithms, with minimal changes to the code (adding a `callback` argument to each algorithm's `learn` function, and `if callback: callback(locals(), globals())` in the code.

It seems that when `normalize_observations=True` (one of the `network_kwargs` parameters), the MPI-parallelized versions of PPO2 don't work. It's important I use the MPI-parallelized and not `SubprocVecEnv` version due to my custom environment.

Here are simple reproducible examples using CartPole-v1:

Works:
```
python -m baselines.run --alg=ppo2 --env=CartPole-v1 --normalize_observations=True
python -m baselines.run --alg=ppo2 --env=CartPole-v1 --normalize_observations=True --num_env=2
mpirun -n 1 python -m baselines.run --alg=ppo2 --env=CartPole-v1 --normalize_observations=True
mpirun - n 2 python -m baselines.run --alg=ppo2 --env=CartPole-v1 --normalize_observations=False
```

Doesn't work:
```
mpirun -n 2 python -m baselines.run --alg=ppo2 --env=CartPole-v1 --normalize_observations=True
mpirun -n 2 python -m baselines.run --alg=ppo2 --env=CartPole-v1 --normalize_observations=True --num_env=2
```

To summarize, normalize_observations=True works for all non-MPI cases and fails for all MPI cases except the trivial one in which there is only 1 worker. Looks like the issue is on a `comm.Bcast` call in `mpi_utils.py`'s `sync_from_root`.

Traceback:
```
(venv) name:baselines name$ mpirun -n 2 python -m baselines.run --alg=ppo2 --env=CartPole-v1 --normalize_observations=True
Logging to /var/folders/3q/vr2qmgq17y59wnv9qrn2l2m4001spw/T/openai-2018-10-31-15-03-18-260956
Logging to /var/folders/3q/vr2qmgq17y59wnv9qrn2l2m4001spw/T/openai-2018-10-31-15-03-18-261338
env_type: classic_control
Logging to /var/folders/3q/vr2qmgq17y59wnv9qrn2l2m4001spw/T/openai-2018-10-31-15-03-18-458159
env_type: classic_control
Training ppo2 on classic_control:CartPole-v1 with arguments 
Training ppo2 on classic_control:CartPole-v1 with arguments 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/petersen33/repositories/baselines/baselines/run.py", line 221, in <module>
    main()
  File "/Users/petersen33/repositories/baselines/baselines/run.py", line 195, in main
    model, env = train(args, extra_args)
  File "/Users/petersen33/repositories/baselines/baselines/run.py", line 78, in train
    **alg_kwargs
  File "/Users/petersen33/repositories/baselines/baselines/ppo2/ppo2.py", line 305, in learn
    model = make_model()
  File "/Users/petersen33/repositories/baselines/baselines/ppo2/ppo2.py", line 304, in <lambda>
    max_grad_norm=max_grad_norm)
  File "/Users/petersen33/repositories/baselines/baselines/ppo2/ppo2.py", line 142, in __init__
    sync_from_root(sess, global_variables) #pylint: disable=E1101
  File "/Users/petersen33/repositories/baselines/baselines/common/mpi_util.py", line 23, in sync_from_root
    comm.Bcast(returned_var)
  File "mpi4py/MPI/Comm.pyx", line 579, in mpi4py.MPI.Comm.Bcast
mpi4py.MPI.Exception: MPI_ERR_TRUNCATE: message truncated
```

**Comment by pzhokhov** [comment]
Hi @brendenpetersen ! The short answer is this - do not use normalize_observations with ppo2 :) 
even if we were to make it work, normalize_observations requires algorithm to call rms.update() (where rms RunningMeanStd object), which ppo2 does not. Instead, ppo2 can use VecNormalize environment wrapper for observation normalization (VecNormalize does not use MPI at the moment). Eventually, we'll unify observation and reward normalization; but I am not sure which way will it go (environment wrapper or an normalization object within algorithm). Closing this, also creating a separate issue about unifying observation normalization: https://github.com/openai/baselines/issues/698
