### ISSUE TITLE
Requirements not clearly stated

### ISSUE THREAD

**Issue by alapite** [openai/baselines#7]
The document doesn't state upfront that the code requires Python 3 to run; I only realized this when I got an error about `no module named builtins`. 

In addition, the `requires.txt` file doesn't state `gym` as a requirement. I realise most people who install this will probably have that module anyway, but in cases where they don't, the earliest they'll realize something is wrong is when they try to execute the `python -m baselines.deepq.experiments.train_cartpole` example and fail.

**Comment by yuke93** [comment]
Yes, I think module `gym` and `future` are required.

**Comment by siemanko** [comment]
I added `gym` and a warning to setup.py about Python 2.
