### ISSUE TITLE
Parallel Environments 

### ISSUE THREAD

**Issue by slerman12** [openai/baselines#709]
I am new to implementing RL algorithms and would like to use the VecEnv methods shared here to parallelize steps across multiple environments. I see this method used in specific model implementations, but it would be helpful if some documentation could be provided. Something brief would be fine, just enough that I would know how to set up one environment multiple times in parallel. Are there better open source implementations for this concern specifically? I have seen some that do not even take advantage of multiple processors or threads. It seems that here at least this parallelism is included. Is my understanding correct? Any guidance on how to set up a multi-environment using the code available here would help me a lot! Thank you.

**Comment by DanielTakeshi** [comment]
To use parallelism look at the `build_env` method in `run.py`. If you build with several CPUs then you get a single `env` object in which taking `env.step(action)` will take one step in all the parallel envs. (For this you need `action` to be a vector matching the number of CPUs, at least in the discrete action case.)

**Comment by pzhokhov** [comment]
@slerman12 to enable parallel steps across multiple environments, use SubprocVecEnv (https://github.com/openai/baselines/blob/52255beda5f5c8760b0ae1f676aa656bb1a61f80/baselines/common/vec_env/subproc_vec_env.py#L34) or ShmemVecEnv (https://github.com/openai/baselines/blob/52255beda5f5c8760b0ae1f676aa656bb1a61f80/baselines/common/vec_env/shmem_vec_env.py#L20). Both of them run copies of the environments in sub-processes, the former communicates observations via pipes whereas latter - via shared memory. At the moment, the most available documentation is docstrings in vec_env module (https://github.com/openai/baselines/blob/52255beda5f5c8760b0ae1f676aa656bb1a61f80/baselines/common/vec_env/__init__.py#L26) 
To see the example usage, as @DanielTakeshi said, look into build_env method (https://github.com/openai/baselines/blob/52255beda5f5c8760b0ae1f676aa656bb1a61f80/baselines/run.py#L87); also here (https://github.com/openai/baselines/blob/52255beda5f5c8760b0ae1f676aa656bb1a61f80/baselines/common/cmd_util.py#L21). Hope this helps and closing this issue, please re-open if you have further questions on it.

**Comment by Agoniii** [comment]
hi @pzhokhov  I am a little bit confused about when the head process is updating neural net, are subprocesses still running `env.step` ?

**Comment by pzhokhov** [comment]
Hi @Agoniii ! While running nn update in parallel with env.step (if env is an instance of SubprocVecEnv or ShmemVecEnv) is possible in principle (both VecEnv subclasses expose method step_async that initiates step but does not wait for it to complete), to my knowledge none of the algorithms in baselines take advantage of it (at the moment). In other words, gradient computation and nn weight updates are not parallelized with env.step.

**Comment by YijiongLin** [comment]
@pzhokhov
Hello!
Recently I tried to run the multiple thread environment, but it kept failing. And I proposed this issue in [here](https://github.com/openai/baselines/issues/998). Could you please take a look? Any feedback is really appreciated!
