### ISSUE TITLE
Multi thread to run on Mujoco?

### ISSUE THREAD

**Issue by andrewliao11** [openai/baselines#71]
Hi, I found that the current implementation of  ```pposgd/run_mujoco.py``` using only single thread. Is it possible to modify it into multi-thread like [this](https://github.com/openai/baselines/blob/master/baselines/pposgd/run_atari.py#L17-L38)? Not sure if it will arouse bugs 😢

**Comment by olegklimov** [comment]
Both ppo1 and ppo2 support several CPUs.
