### ISSUE TITLE
Do is possible use DQN in Vectorized Environment ?

### ISSUE THREAD

**Issue by icaro56** [openai/baselines#711]
My observations are a vector list.

**Comment by pzhokhov** [comment]
at the moment DQN does not support vecenvs, it is on our TODO list to make that happen. From RL perspective, vecenvs do not help learning performance in DQN - unlike in policy gradient-based methods, where vecenvs provide more diverse experience, in DQN data goes through replay buffer anyways, so the only benefit of vecenvs is faster stepping.

**Comment by DanielTakeshi** [comment]
@icaro56  You can do it. I've modified my personal DQN to use it, though I've had to adjust my hyperparameters a bit and I haven't settled on a good set yet.

**Comment by Unimax** [comment]
@DanielTakeshi you mean https://github.com/DanielTakeshi/dqn ? else please guide me to the code you are talking about.

**Comment by DanielTakeshi** [comment]
@Unimax  no that was a random package I had forked.

I was talking about another code base. Unfortunately it's private since I'm using it for research now.
