### ISSUE TITLE
DDPG cannot work on the robotics environment.

### ISSUE THREAD

**Issue by WuXinyang2012** [openai/baselines#717]
Hi, I am doing a project on the robotics environment, which is in continuous space, so I am trying to use DDPG in the FetchReach-v1 environment:

```bash
python -m baselines.run --alg=ddpg --env=FetchReach-v1 --num_timesteps=1e6
```
it tells me:
```bash
TypeError: can only concatenate tuple (not "NoneType") to tuple
```

It seems that this problem is because the robotics environments have a dictionary-based observation space.

It would be much better if someone can fix this bug and make the baselines.run a really general method for all the gym environments.

Thanks in advance!

**Comment by Sohojoe** [comment]
FetchReach-v1 is a GoalEnv which are designed to work with HER. The observations are a dictionary as the algorithm needs additional data to construction the reward for actual targets.

**Comment by pzhokhov** [comment]
should be fixed in this PR: https://github.com/openai/baselines/pull/767, closing this issue

**Comment by wsgdrfz** [comment]
How can I train the agent with DDPG without her to compare the result? Didn't see that in her part.
