### ISSUE TITLE
[Question] Default hyperparameter choice for Prioritized Experience Replay

### ISSUE THREAD

**Issue by cli0** [openai/baselines#718]
Your PER implementation is rank-based and the default hyperparameter values (alpha=0.6, beta=0.4) that you have written down are actually the "ideal" combination for proportional PER and not rank-based. At least according to the original paper for PER https://arxiv.org/pdf/1511.05952.pdf , if I'm not mistaken. Is this an oversight or is your PER proportional somehow?

**Comment by DanielTakeshi** [comment]
The hyperparameters OpenAI used are not exactly the same as the paper, but as you pointed out they are close. In any case they aren't using the same exact implementation of the data structures, etc., so there are going to be differences in implementation anyway. I have found that OpenAI's default parameters for PER are fine.

**Comment by cli0** [comment]
I understand. But at least just for reassurance, the default implementation of PER here is rank-based not proportional, right?

**Comment by DanielTakeshi** [comment]
From looking at the code it is the proportional one. @pzhokhov can confirm

**Comment by pzhokhov** [comment]
confirming, the prioritized experience replay in baselines/deepq is proportional, not rank-based one - note that we are passing tderrors directly into update_priorities method: 
https://github.com/openai/baselines/blob/d3fed181b57f61013698521f4e940594364253e9/baselines/deepq/deepq.py#L303
also see the implementation of update_priorities here: 
https://github.com/openai/baselines/blob/d3fed181b57f61013698521f4e940594364253e9/baselines/deepq/replay_buffer.py#L169.
Closing this.

**Comment by cli0** [comment]
I have one more question regarding the implementation (I hope it's okay I reopen this same issue). Can you please explain exactly how you calculate/define the td-errors? I understand td-error is one value and yet you have a vector of errors that you use to calculate priorities. Where do the dimensions come from? What do the dimensions refer to?

**Comment by DanielTakeshi** [comment]
@cli0 It sounds like the vector you refer to are the batch size index. The batch size is in the leading axis so the vector should be of shape (B,).
