### ISSUE TITLE
best hardware combination for deep-RL

### ISSUE THREAD

**Issue by akhilsanand** [openai/baselines#726]
Hi,
I am looking for the best possible hardware combination for performing deep reinforcement learning on highly complex MuJoCo environments. Please suggest the best CPU-GPU combination possible.

Thanks,
Akhil

**Comment by pzhokhov** [comment]
I have too little experience with different hardware combinations. Redirecting to @machinaut @cberner @esigler for expert opinions.

**Comment by machinaut** [comment]
I don't think there's a single best combo for that.

It's often useful to have a GPU to speed up neural network training, but that isn't even required, especially when doing reinforcement learning where you have to take many physics simulation steps per optimization step.

I think its good to start first with whatever machine you already have, and then figure out your needs based on what experiments you're running.

I know this is a bit of a non-answer, but at least for getting started, the specific differences between CPUs and GPUs don't matter much.

As a generic solution, if you use cloud computing / rented computing resources, you can change what kind and how much compute you're using based on your experimental needs.

Hope this helps!
