### ISSUE TITLE
MPI with PPO2 broken

### ISSUE THREAD

**Issue by brendenpetersen** [openai/baselines#727]
A recent commit seems to have broken MPI for PPO2. Minimal example with fresh clone:

```
$ python baselines/run.py --env=CartPole-v1 --alg=ppo2 # Works
$ mpirun -n 2 python baselines/run.py --env=CartPole-v1 --alg=ppo2 # Hangs on sync_from_root
```

The cause is that `sync_from_root` (which is only called by rank > 0) is waiting for a Bcast of `global_variables`, which doesn't exist in rank 0.

Bug (ppo2/model: L125):

```
if MPI is None or MPI.COMM_WORLD.Get_rank() == 0:
    initialize()
else:
    global_variables = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope="")
    sync_from_root(sess, global_variables) #pylint: disable=E1101
```

Fix:

```
if MPI is None or MPI.COMM_WORLD.Get_rank() == 0:
    initialize()
global_variables = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope="")
if MPI is not None:            
    sync_from_root(sess, global_variables) #pylint: disable=E1101
```

I will submit a PR to fix this issue.

(Future question: Should I submit both issue+PR when I both identify+fix a bug, or just submit a PR?)

**Comment by pzhokhov** [comment]
@brendenpetersen confirmed; fix is coming shortly. As for issues + PRs vs just PR's - either works, as long as you provide sufficient description of the problem in the PR.

**Comment by pzhokhov** [comment]
Here's the PR that fixes it: https://github.com/openai/baselines/pull/735

**Comment by pzhokhov** [comment]
should be fixed in master, closing this
