### ISSUE TITLE
Unable to debug the PPO2 algorithm with VSCode

### ISSUE THREAD

**Issue by davidhopper2003** [openai/baselines#739]
I used VSCode to debug the PPO2 algorithm. When debugging to line 58 of the file `baselines/common/vec_env/subproc_vec_env.py`:

```python
observation_space, action_space = self.remotes[0].recv()
```

the program has no response and the debugging process cannot continue (As shown below). 
![ppo2_debug_1](https://user-images.githubusercontent.com/31435476/49197695-c8a4ff80-f3ca-11e8-87f0-468bb47250c2.png)
![ppo2_debug_2](https://user-images.githubusercontent.com/31435476/49197696-c8a4ff80-f3ca-11e8-84a0-6297ab5f8868.png)
![ppo2_debug_3](https://user-images.githubusercontent.com/31435476/49197697-c8a4ff80-f3ca-11e8-989e-2ecbba52c6b1.png)

My configuration file `.vscode/launch.json` is shown as follows:

```
{

    // Use IntelliSense to learn about possible attributes.

    // Hover to view descriptions of existing attributes.

    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387

    "version": "0.2.0",

    "configurations": [

        {

            "name": "Python: Module",

            "type": "python",

            "request": "launch",

            "module": "baselines.run",

            "console": "integratedTerminal",

            "args": [

                "--alg",

                "ppo2",

                "--env",

                "PongNoFrameskip-v4",

                "--num_timesteps",

                "2e7",

                "--save_path",

                "~/models/pong_20M_ppo2"

            ],

        },

        {

            "name": "Python: Current File (Integrated Terminal)",

            "type": "python",

            "request": "launch",

            "program": "${workspaceFolder}/baselines/run.py",

            "console": "integratedTerminal", 

            "args": [

                "--alg",

                "ppo2",

                "--env",

                "PongNoFrameskip-v4",

                "--num_timesteps",

                "2e7",

                "--save_path",

                "~/models/pong_20M_ppo2"

            ],

        }

    ]

}
```

When I used the command line 

`python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=2e7 --save_path=~/models/pong_20M_ppo2` 

to run the program in a terminal, there is no problem. 

Any helpful suggestions will be highly appreciated. Thank you.

**Comment by davidhopper2003** [comment]
I've figured it out. See another issue I wrote: [subprocess: Support for fork in subprocess debugging](https://github.com/Microsoft/ptvsd/issues/943).

**Comment by pzhokhov** [comment]
Let me close this and move discussion to the PR.
