### ISSUE TITLE
confirm if my understanding of mpi usage is right

### ISSUE THREAD

**Issue by scotthuang1989** [openai/baselines#741]
I have read the code and did some experiment about running basline with openmpi. I want to confirm if I am right before I run large scale experiments.

There are 2 parallel machenism:

**1. environment parallel:**  

   this is specified by the` --num_env` , it is done by create multiple process and run 1 environment in each process.

**2. mpi parallel:** 

I can run baseline with following command:

`mpirun -np 2 python -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4  --num_env  3`

this will create 2 mpi processes and
each mpi process will crate 4 child processes(1 main process  and 3 subprocess for environment) independently. 

this command will crate  8 processes in total. 

during training 
each mpi process will calculate gradient independently and 
`MpiAdamOptimizer `will  calculate average gradient from these 2 mpi process and then apply to variables in all 2 mpi process.

please correct me if I am wrong. it will save tons of my time. thanks.

**Comment by pzhokhov** [comment]
Yes all of the above is correct.
