### ISSUE TITLE
Reward and Length Buffer

### ISSUE THREAD

**Issue by ecada** [openai/baselines#743]
Regarding the lines in ppo1/pposgd_simple.py:
lenbuffer = deque(maxlen=100) # rolling buffer for episode lengths
rewbuffer = deque(maxlen=100) # rolling buffer for episode rewards

When graphing the learning curves on tensorboard, I guess the episode rewards are calculated for the last 100 timesteps of the 2048 timesteps horizon. Is this a valid evaluation when compared to 2048 timesteps case with plot.py and why is it the default? Thank you so much for this wonderful repository by the way!  😄

**Comment by pzhokhov** [comment]
Hi @ecada! The len buffer and rew buffer are for the lengths and returns of last 100 episodes, not last 100 timesteps, so depending on the episode length the number of steps taken into account may vary. 
The roundness of the number 100 suggests that is not very principled :)The idea is to report approximate performance at the point of logging, however, if we were to just report the return / length of the last episode, it would be very noisy. Averaging over last 100 episodes provides a more smooth estimate, but also somewhat delayed. Hope this helps!
