### ISSUE TITLE
DDPG never converge

### ISSUE THREAD

**Issue by iswaverly** [openai/baselines#764]
I trained DDPG with command refered in README, which is "python -m baselines.run --alg=ddpg --env=HalfCheetah-v2 --num_timesteps=1e6".
After 1000000 steps, the reward is still negative.
I tried other games, such as "popper", none of this can I get the correct result.

I use the master branch with latest code, and my tensorflow-gpu version is 1.8.0.

Have anyone train DDPG success?

**Comment by iswaverly** [comment]
fix it

**Comment by Yeosangho** [comment]
Can you share your solution with us? I have same prorblem like you. TT

**Comment by sayomakinwa** [comment]
I have a similar situation with DDPG on Humanoid-v2 environment; it doesn't converge. Suggestions will be highly appreciated

**Comment by DennisWangCW** [comment]
I meet with the same situation. Hope for solution.

**Comment by DennisWangCW** [comment]
> fix it

hi, could you share with us how you fix it?

**Comment by fangchuan** [comment]
HI, I have same problems when I implement my agent based on baselines.ddpg, counld you tell us how you fix the unconverged problem? I really appreciate that.
