### ISSUE TITLE
Please expose size, number and activation function parameters for DDPG  actor and critic

### ISSUE THREAD

**Issue by ViktorM** [openai/baselines#77]
Great work with adding DDPG with parameter space noise, thank!

Can you also expose additional command line parameters in main.py like sizes of the layers, their numbers and activation functions for DDPG actor and critic. Currently they can only be set in models.py

**Comment by xmanatee** [comment]
Yeah! That would be a great practice in other models too to be able to adjust all the parameters for actor and critic without rewriting the code out of the main scope.

**Comment by olegklimov** [comment]
Hi there. Thanks for your interest, part of usefulness of this project is a small and hackable code. Changing the model is pretty straightforward now, but parsing and branching is not helping the code to be simple.
