### ISSUE TITLE
PPO2: Epsilon exploration?

### ISSUE THREAD

**Issue by Ploppz** [openai/baselines#771]
I tried to train `Acrobot-v1` using your PPO implementation (`ppo2`). But it performs really bad - virtually never reaches the goal. I ran it for 200 episodes (100000 time steps) but it only reached the goal once after 495 timesteps (environment resets at 500 timestep, so this is rather useless).

I wonder if epsilon exploration would make this better (note that Acrobot has very sparse rewards). However I could not find any way to add epsilon exploration. If I could somehow just **wrap or modify the action-taking function or class**, that would help.

Here is my code:

```
from baselines.common.vec_env.dummy_vec_env import DummyVecEnv
from baselines.ppo2.ppo2 import learn
import baselines.common.models as models

import gym
from matplotlib import pyplot as plt


class Env:
    def __init__(self, inner_env):
        self.rewards = []
        self.reward = 0
        self.env = inner_env
        self.observation_space = inner_env.observation_space
        self.action_space = inner_env.action_space

        self.ob_dim = inner_env.observation_space.shape[0]

    def step(self, action):
        state_next, r, terminal, info = self.env.step(action)
        self.reward += r
        if terminal:
            self.rewards.append(self.reward)
            self.reward = 0
        return state_next, r, terminal, info

    def reset(self):
        state = self.env.reset()
        return state

    def render(self):
        return self.env.render()

if __name__ == '__main__':
    from baselines import logger
    logger.set_level(logger.DISABLED)

    ENV_NAME = "Acrobot-v1"
    env = DummyVecEnv([lambda: Env(gym.make(ENV_NAME))] * 4)

    network = models.mlp(2, 15)
    learn(network=network, env=env, total_timesteps=100000, nsteps=12)
    rewards = [val for tup in zip(*[e.rewards for e in env.envs]) for val in tup]
    plt.plot(rewards)
    plt.savefig("result.png")
```

The reason I added an `Env` class (just a wrapper around OpenAI env) was to be able to accumulate reward so that I could plot it and inspect it. (any advice how to do that without this 'hack' would also be welcome).

**Comment by pzhokhov** [comment]
Hi @Ploppz ! Regarding the wrapper accumulating the rewards - Monitor wrapper does essentially that (in baselines/bench/monitor.py) - whenever the episode is terminal, it records total reward of the episode and the episode length, returns them in info dictionary (the fourth return value of env.step), and optionally saves that in a csv file in logger directory. 
Regarding epsilon-exploration - there simplest way to achieve that for all policy gradient methods is to increase entropy coefficient (this would force action distribution to become wider). No code changes needed, however, that's not quite the same as epsilon-exploration. If you specifically would like to try epsilon-exploration, code in Runner class (responsible for rollouts) needs to be modified (for instance, for ppo2, here: https://github.com/openai/baselines/blob/6c44fb28fecdb666182e2951b7b1cbe9cf198ff1/baselines/ppo2/runner.py#L29 - replace actions sampled from policy with random actions with probability epsilon). Note, however, that ppo2 is on-policy (or at least quasi-on policy) method. Replacing the actions sampled from the action distribution with random actions will lead to a biased gradient estimate (although for small epsilon that's probably not a big deal). 
Performance on Acrobot - I don't have, unfortunately, much experience with training Acrobot with ppo2, so I don't know if a hyperparameter setting that would perform well; my intuition is that there should be at least somewhat decently performing one though.

**Comment by pzhokhov** [comment]
Closing this, please reopen if Monitor wrapper is not quite what you were looking for

**Comment by Ploppz** [comment]
Thank you for your extremely useful reply! I have enough to make it work then I think. I will definitely try to tune hyper parameters. And thanks for pointing out the limitation of on-policy methods.
