### ISSUE TITLE
Last command line fails

### ISSUE THREAD

**Issue by ampnirvana** [openai/baselines#8]
Running the visualise command line fails with version incompatibility:
`    raise error.DeprecatedEnv('Env {} not found (valid versions include {})'.format(id, matching_envs))
gym.error.DeprecatedEnv: Env BreakoutNoFrameskip-v3 not found (valid versions include ['BreakoutNoFrameskip-v4', 'BreakoutNoFrameskip-v0'])
`

 Commandline used: 
`python -m baselines.deepq.experiments.atari.enjoy --model-dir /tmp/models/model-atari-prior-duel-breakout-1 --env Breakout --dueling
`

**Comment by vincentsohjh** [comment]
I have the same error too. This was tested on python 2 and 3. Anyone has ideas on how to solve this?

**Comment by siemanko** [comment]
should be fixed now.

**Comment by ROZBEH** [comment]
I still have the same problem. I just installed the package.
