### ISSUE TITLE
run behavior_clone.py ，get error   X11/Xlib.h: No such file or directory #include <X11/Xlib.h> and  ‘gnu-cc’  failed with exit status 1

### ISSUE THREAD

**Issue by sxwgit** [openai/baselines#803]
Hello,

When running the behavior_clone.py on the conda environment，i get the following error

> running build_ext
building 'mujoco_py.cymj' extension
/home/songxw/anaconda3/envs/mujoco-py/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -I/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py -I/home/songxw/.mujoco/mjpro150/include -I/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/numpy/core/include -I/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/vendor/egl -I/home/songxw/anaconda3/envs/mujoco-py/include/python3.5m -c /home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/cymj.c -o /home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/generated/_pyxbld_1.50.1.68_35_linuxgpuextensionbuilder/temp.linux-x86_64-3.5/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/cymj.o -fopenmp -w
/home/songxw/anaconda3/envs/mujoco-py/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -I/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py -I/home/songxw/.mujoco/mjpro150/include -I/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/numpy/core/include -I/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/vendor/egl -I/home/songxw/anaconda3/envs/mujoco-py/include/python3.5m -c /home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/gl/eglshim.c -o /home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/generated/_pyxbld_1.50.1.68_35_linuxgpuextensionbuilder/temp.linux-x86_64-3.5/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/gl/eglshim.o -fopenmp -w
In file included from /home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/gl/egl.h:39:0,
from /home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/gl/eglshim.c:2:
/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/gl/eglplatform.h:99:10: fatal error: X11/Xlib.h: No such file or directory
#include <X11/Xlib.h>
^~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
File "/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
extra_postargs)
File "/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
spawn(cmd, dry_run=self.dry_run)
File "/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/distutils/spawn.py", line 36, in spawn
_spawn_posix(cmd, search_path, dry_run=dry_run)
File "/home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
% (cmd, exit_status))
distutils.errors.DistutilsExecError: command '/home/songxw/anaconda3/envs/mujoco-py/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1

my conda environment 

> active env location : /home/songxw/anaconda3/envs/mujoco-py
shell level : 2
user config file : /home/songxw/.condarc
populated config files :
conda version : 4.5.12
conda-build version : 3.17.6
python version : 3.7.1.final.0
base environment : /home/songxw/anaconda3 (writable)
channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/free/linux-64
https://repo.anaconda.com/pkgs/free/noarch
https://repo.anaconda.com/pkgs/r/linux-64
https://repo.anaconda.com/pkgs/r/noarch
https://repo.anaconda.com/pkgs/pro/linux-64
https://repo.anaconda.com/pkgs/pro/noarch
package cache : /home/songxw/anaconda3/pkgs
/home/songxw/.conda/pkgs
envs directories : /home/songxw/anaconda3/envs
/home/songxw/.conda/envs
platform : linux-64
user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.15.0-29-generic ubuntu/16.04 glibc/2.23
UID:GID : 1000:1000
netrc file : None
offline mode : False

I have tried many methods, including conda install gcc, (but i get another issue like [this ](https://github.com/ContinuumIO/anaconda-issues/issues/1392) ，and that answer doesnt  work,)sad.
what should i do to solve this problem ( ‘gnu-cc’ failed with exit status 1)
Best regards,

**Comment by sxwgit** [comment]
>

**Comment by sxwgit** [comment]
I tried the following two methods，but  they have not changed anything , still have the same issue
1. like [issue/336](https://github.com/openai/mujoco-py/issues/336),i copy the X11 from /usr/lib/ to /sysroot/usr/include which a new path i created。

> songxw@songxw-pc:~/sysroot/usr/include$ ls
> X11  Xlib.h
> songxw@songxw-pc:~/sysroot/usr/include$ pwd
> /home/songxw/sysroot/usr/include
> songxw@songxw-pc:~/sysroot/usr/include$

perhaps i  I misunderstood the meaning of the sysroot path， It refers to another path？

2. i copy the X11 from /usr/lib to /home/songxw/anaconda3/envs/mujoco-py/lib/python3.5/site-packages/mujoco_py/gl/

**Comment by sxwgit** [comment]
oh ，i solved the first problem in a very violent way, I modified all the header files, that <xx.h> -> "xx.h"
so it can  find related files from the current directory now. But i still have the second problem,anyone know how to solve it? HELP!

**Comment by pzhokhov** [comment]
Hi @sxwgit ! If you have X11 with headers installed (if not, try `sudo apt-get install libx11-dev`), then likely the easiest way to fix this is to add location of X11 to CPATH environment variable (which tells gcc where else to look for include files). For instance, if the path to your Xlib.h is /usr/lib/X11/Xlib.h, the following should fix it: `export CPATH=/usr/lib:$CPATH` (and then try re-running the behavior cloning code, or any code that uses mujoco). Here's a reference on how is gcc affected by environment variables: https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html

**Comment by sxwgit** [comment]
@pzhokhov  Thank you!  It do works, I tried to reinstall the relevant configuration and added the path, finally ，I succeeded， the code can run !

**Comment by pzhokhov** [comment]
Cool :) Closing this then
