### ISSUE TITLE
Memory Leak when --num_env > 1

### ISSUE THREAD

**Issue by MatPoliquin** [openai/baselines#804]
repro:
python3 -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=2e7 --num_env=2

Observations:

- The memory usage of the two python env processes increases at about 30MB per minute until it OOM.
- If I run with --num_env=1 there is no leak
- cifar10 runs with no leaks
- If I use other algos such as --alg=acer, it also leaks
- If I use retro env (as opposed to atari env in the command above) it also leaks

I tried to track down the memory leak with **pympler**.

In:
def worker(remote, parent_remote, env_fn_wrapper),  **subproc_vec_env.py**
I used:
```
from pympler import tracker
tr = tracker.SummaryTracker()

[...]
if cmd == 'step':
     ob, reward, done, info = env.step(data)
      if done:
          **tr.print_diff()**
          ob = env.reset()
```

This is the output I got:

                            types |                       # objects |         total size
==================================== | =========== | ============
  <class 'numpy.ndarray |                               911 |    113.88 KB
  <class 'builtin_function_or_method |           911 |     64.05 KB
  <class 'float |                                                  53 |     1.24 KB
   <class 'list |                                                     0 |    928     B
   <class 'int |                                                      1 |     28     B

**Seems the ob, reward, done and info variable are leaking.**
I tried to use del on these variables but the garbage collector doesn't get rid of them, even if I manually call it  with "gc.collect(2)"

Software:
Ubuntu 18.04
Tensorflow 1.12
Python 3.6.7
latest baselines (no modifications)

Hardware:
2x 2680v2
64MB ddr3
gtx 1060

**Comment by pzhokhov** [comment]
@MatPoliquin does upgrading to numpy 1.16.1, as suggested in the referenced issue, solve this?

**Comment by MatPoliquin** [comment]
@pzhokhov Seems to be the cause, since I don't have the leak anymore. Thanks!

**Comment by pzhokhov** [comment]
Cool, let me close this then
