### ISSUE TITLE
Storing results in csv

### ISSUE THREAD

**Issue by Riashat** [openai/baselines#81]
Is there a way to store the training and evaluation results directly in csv using logger?

In what format are the results usually stored? eval_env_state.pkl? Instead of this, can we store results directly in csv by specifying the directory as an argument (as done in openai/rllab)?

**Comment by joschu** [comment]
See logger.py, with `LOG_OUTPUT_FORMATS = ['stdout', 'log', 'json']`. You can modify this file and create a csv logger like the json one.
