### ISSUE TITLE
PPO2 globalseeds

### ISSUE THREAD

**Issue by ecada** [openai/baselines#822]
Hello,
I've been experimenting with the PPO2 algorithm using DummyVecEnv where the number of environments is set to 16. I've realized that in the learn method set_global_seeds use a single seed for every 16 environments.

https://github.com/openai/baselines/blob/5b41c926c7a852df3f0928afdf2429f96a3965cb/baselines/ppo2/ppo2.py#L80

Doesn't that lead to sampling the same actions for each environment when using 1 process and hinder the exploration in parallel sampling? 

Also I can't figure out why PPO1's episode rewards are 10.1 after one gradient step whereas PPO2's (run using DummyVecEnv where the number of environments is set to 16) is approximately 100. Why is there a striking difference?

Thank you so much for this wonderful library as always, it is the most essential repository for deep reinforcement learning research.

**Comment by scotthuang1989** [comment]
sampling action is not done in environment.

**Comment by ecada** [comment]
Sorry, I've put it wrongly. What I meant was carrying out the sampled action (where the sampling was done using the same seed that was set in set_global_seeds(seed)) in each environment. In contrast, in PPO1 the seed used in "set_global_seeds(seed)" line is different for every process.

**Comment by scotthuang1989** [comment]
if you are talking about the stochastics whihin a enviroment.  there are a **seed** function in every  gym enviroment.

**Comment by ecada** [comment]
> if you are talking about the stochastics whihin a enviroment. there are a **seed** function in every gym enviroment.

I'm referring to the seed used for action sampling from the probability distribution as seen in these lines below.

https://github.com/openai/baselines/blob/5b41c926c7a852df3f0928afdf2429f96a3965cb/baselines/common/policies.py#L52

https://github.com/openai/baselines/blob/5b41c926c7a852df3f0928afdf2429f96a3965cb/baselines/common/distributions.py#L247
