### ISSUE TITLE
Where does the ppo2 reset the env?

### ISSUE THREAD

**Issue by HitLyn** [openai/baselines#829]
In ppo1, when the env.step() gets done which means the mission has been achieved, the env will be reset by env.set(),then the training continue:
https://github.com/openai/baselines/blob/5b41c926c7a852df3f0928afdf2429f96a3965cb/baselines/ppo1/pposgd_simple.py#L61
But I can't find where ppo2 reset the env, or do I misunderstand something?

**Comment by andytwigg** [comment]
ppo2 uses vectorized environments, so the reset is done inside the vecenv -
see for example
https://github.com/openai/baselines/blob/master/baselines/common/vec_env/dummy_vec_env.py#L54

**Comment by HitLyn** [comment]
@andytwigg Thanks for the explain, problem solved.

**Comment by BTickell** [comment]
@andytwigg sorry to beat a dead horse but it seems like ppo2.runner does not explicitly call `env.reset()` outside of `__init__()`. This also isn't done in the ppo2 training code so I am unsure where this is actually being done.

**Comment by andytwigg** [comment]
The reset is done inside the vectorized env - see eg
https://github.com/openai/baselines/blob/master/baselines/common/vec_env/dummy_vec_env.py#L53

The runner keeps calling vecenv.step() which resets the underlying envs as
necessary

**Comment by BTickell** [comment]
I see, this seems to require the environment to explicitly set the done flag to `True` when desiring a reset? For some tasks this may not be desirable but it can be worked around.

**Comment by andytwigg** [comment]
It uses the reset flag that is returned from the call to env.step

**Comment by BTickell** [comment]
This seems like an odd requirement for the runner to work correctly since even it seems quite a few environments in gym (i.e reacher, pusher, etc.) do not set the done flag to `True` at any point during training.

**Comment by andytwigg** [comment]
I'm not that familiar with the mujoco envs. Perhaps they set the flag to
true after a certain number of steps or when a goal is achieved.

**Comment by BTickell** [comment]
It's pretty inconsistent between environment since some tasks have a good notion of "doneness" and others don't. As far as I know there is no built in counter for mujoco envs. For some jobs it would make sense to reset the environment after sampling but I can see in some cases that wouldn't be desired
