### ISSUE TITLE
Error about import folders and files

### ISSUE THREAD

**Issue by wonchul-kim** [openai/baselines#83]
for example, 

from baselines.pposgd import mlp_policy, pposgd_simple 

ImportError: cannot import name 'pposgd'

Or, from baselines import bench
Traceback (most recent call last):
File "run_atari.py", line 4, in
from baselines import bench
ImportError: cannot import name 'bench'

So, I moved all the dependent and related files(.py) to the pposgd folders where the run_mujoco.py is at.
Then, it runs well...

I don't know why the 'import' and 'from' can't work.....

Ironically, when i run deepqn, it worked... without any change....

COuld you please solve this problme?

My environment is Ubuntu 16.04, python3.5.... and i also installed baselines...

**Comment by joschu** [comment]
Fixed
