### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by JackieTseng** [openai/baselines#84]
```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from baselines.common.mpi_fork import mpi_fork
ImportError: No module named mpi_fork
```

How can I fix this problem? THX.

**Comment by Amathlog** [comment]
Install from source 
Clone the repo, move into it and do `pip install -e .`

**Comment by JackieTseng** [comment]
@Amathlog Thx, it works.
But I met another problem when running code when importing mpi_fork as following,
```
Traceback (most recent call last):
  File "main2.py", line 10, in <module>
    from baselines.common.mpi_fork import mpi_fork
  File "/home/jackie/code/baselines/baselines/common/__init__.py", line 2, in <module>
    from baselines.common.dataset import Dataset
  File "/home/jackie/code/baselines/baselines/common/dataset.py", line 50
    def iterbatches(arrays, *, num_batches=None, batch_size=None, shuffle=True, include_final_partial_batch=True):
                             ^
SyntaxError: invalid syntax
```
Is it a problem in source code? How can I fix it? THX

**Comment by VSNanditha** [comment]
I've tried installing from source. Used Virtual env and tried using the same process on Mac and Ubuntu. Error occured only on Ubuntu. Using Python version 3.4.

Any other reason for the error?

**Comment by pzhokhov** [comment]
Hi @VSNanditha! Could you post the full stacktrace of the error here? Thanks!

**Comment by VSNanditha** [comment]
This trace is when I run train_cartpole from the sample experiments of deepq. 

    $ python train_cartpole.py 
    Traceback (most recent call last):
        File "train_cartpole.py", line 3, in <module>
            from baselines import deepq
    ImportError: No module named 'baselines'

I think i need to make changes to __init__.py but I did the same steps in my Mac and it works fine without any changes to the __init__ files.
