### ISSUE TITLE
Is DDPG cod all right??

### ISSUE THREAD

**Issue by wonchul-kim** [openai/baselines#85]
I just read through the DDPG code, especially training.py.

First, I am curious about the relationship between roll_out, step, and episode.

and I think that the episode_reward should be initialized at every start of the new episode....

Could you explain, please?

**Comment by Breakend** [comment]
I think this is a similar issue to: https://github.com/openai/baselines/issues/117

**Comment by unixpickle** [comment]
As far as I can tell, `episode_reward` is initialized at the start of every episode: https://github.com/openai/baselines/blob/8c90f67560920224e466d0389ac1bbf46e00773c/baselines/ddpg/training.py#L99

Could you clarify what you mean by `roll_out`, `step`, and `episode`, perhaps by linking to specific line numbers?

**Comment by olegklimov** [comment]
Let's close this for lack of activity.
