### ISSUE TITLE
Cannot find commit cbd21ef mentioned by benchmark page

### ISSUE THREAD

**Issue by ktlichkid** [openai/baselines#869]
Hi,

I am trying to reproduce the benchmark curve in this page (noted as Benchmarks in Readme): http://htmlpreview.github.io/?https://github.com/openai/baselines/blob/master/benchmarks_atari10M.htm

According to the link above, it seems the benchmark curves were produced with commit `cbd21ef`. However I failed to find a commit with that revision number in this project. 

How could I find the correct version to reproduce the benchmark curves? Any hint will be appreciated!

**Comment by pzhokhov** [comment]
Hi @ktlichkid! Sorry about that, the commit there corresponds to the one in our internal fork of baselines. Here's the mirrored public commit: https://github.com/openai/baselines/commit/7bfbcf177eca8f46c0c0bfbb378e044539f5e061. In fact, let me update those html's

**Comment by pzhokhov** [comment]
updated, closing this

**Comment by ktlichkid** [comment]
Hi @pzhokhov.  Thank you so much for your quick fix! Really appreciate it.
However the page now still seems to be weird to me -- the data recorded in table `Atari10M Comparison` doesn't match the learning curves plotted below if I interpreted it correctly.

For example, for breakout environment, the learning curve is like this:
![image](https://user-images.githubusercontent.com/11657533/55699001-9f911d00-5a03-11e9-8647-4c205301ee64.png)
We may tell that most of the algorithms could receive a reward above 200.

However in the table, none of the algorithm could get a reward of more than 200 on breakout:
![image](https://user-images.githubusercontent.com/11657533/55699073-f72f8880-5a03-11e9-9689-f4c5653d210d.png)
(Both the curve and the table are screenshotted from benchmark page http://htmlpreview.github.io/?https://github.com/openai/baselines/blob/master/benchmarks_atari10M.htm)
On other environments there could observe similar phenomenon too.

Do you have any hints on it? Am I making mistakes in understanding the table and the curves?
I really appreciate your help.

**Comment by pzhokhov** [comment]
The value reported in the table is the mean score throughout the entire training (not the final score), hence the discrepancy... The reason we report mean score is so that the algorithms that train faster but achieve the same final score get higher mean score. But I can see how that's somewhat confusing. Ideally, I'd like to make a public interactive webpage with this data; unfortunately, I don't have a timeline for that just yet.

**Comment by pzhokhov** [comment]
Another thing to note is that curves plotted are average values over 6 seeds, and the shaded regions correspond to the error estimate of the average value (that is, standard deviation / sqrt(N=6)).

**Comment by ktlichkid** [comment]
OK, thanks a lot for your kind response!
