### ISSUE TITLE
Is the old-policy updated at each epoch? 

### ISSUE THREAD

**Issue by alexis-jacq** [openai/baselines#87]
Hi, I am trying to implement PPO with clip using Pytorch: https://github.com/alexis-jacq/Pytorch-DPPO/blob/master/ppo.py

But reading the paper, I could not figure out if the old policy should be updated at each epoch or just once for the K epoch steps. 

Also, it seems that with my implementation, using or not the clipping of the loss may not change the performance (which is quite bad). I assume I am misunderstanding an important detail, but I can't find which one.

**Comment by olegklimov** [comment]
Er... There is no old/new policy in PPO. OK sorry there is in ppo1, but it is not a requirement, you only need neglogprob of the previous policy. So yeah, answer to your question is: old policy is policy that has produced the rollouts in your buffer.

**Comment by alexis-jacq** [comment]
Thank you so much, it was just that: adding the log probabilities in the memory (instead of the prob from the previous update). Now my implementation seems to work properly.
