### ISSUE TITLE
NoFrameskip?

### ISSUE THREAD

**Issue by abhigenie92** [openai/baselines#89]
```
assert 'NoFrameskip' in env.spec.id  # required for DeepMind-style skip
AssertionError
```
Why this check? Is necessary for all atari environments? Is 'NoFrameskip' offered for all environments?
There is no CartPole NoFrameskip version available.

**Comment by Eric-Wallace** [comment]
Deepmind typically only acts ever 4 frames in areas like Atari. This doesn't reduce the effectiveness of your agents, but it will allow the emulator to run at a much faster speed (roughly 4x) faster. Though for other environments like CartPole, you do not want to skip frames.

**Comment by olegklimov** [comment]
The check is for deepmind-style to be deepmind style. Of course you can create whatever wrappers you want or need, but that would not be deepmind-style. Hope this helps.
