### ISSUE TITLE
Memory problem in using LazyFrames

### ISSUE THREAD

**Issue by NaiveRed** [openai/baselines#896]
Hi~
I am trying **atari_wrappers.py** in other place and I checked the usage in **deepq.py** and **replay_buffer.py**.

https://github.com/openai/baselines/blob/3301089b48c42b87b396e246ea3f56fa4bfc9678/baselines/deepq/deepq.py#L279-L284

https://github.com/openai/baselines/blob/3301089b48c42b87b396e246ea3f56fa4bfc9678/baselines/deepq/replay_buffer.py#L36-L41

It seems the memory(RAM) will still increase fast when I use **LazyFrames**.
Does it need to make a deep copy on the Lazyframes object before convert it to the numpy array? Or the replay buffer will store the **LazyFrames** whose **`self._out`** has been concatenating several numpy arrays. (more RAM)

https://github.com/openai/baselines/blob/3301089b48c42b87b396e246ea3f56fa4bfc9678/baselines/common/atari_wrappers.py#L208-L212

Like this:
```python
action = act(np.array(copy.deepcopy(obs))[None], update_eps=update_eps, **kwargs)[0]
```
and
```python
obses_t.append(np.array(copy.deepcopy(obs_t), copy=False))
obses_tp1.append(np.array(copy.deepcopy(obs_tp1), copy=False))
```

**Comment by p-christ** [comment]
I would also like to know the answer to this if anyone knows?

**Comment by NaiveRed** [comment]
I think it can simply solve by just using `out` instead of `self._out` if you don't really need it.
