### ISSUE TITLE
Expanding the documentation

### ISSUE THREAD

**Issue by benibienz** [openai/baselines#90]
Are there any plans to write more documentation for using this API? Going through the code there's a lot of useful stuff in here but only the occasional comment to help you use it. I've noticed comments such as "See README.md for a description of the logging API." on logger.py, but I can't find any reference to logging on any of the README files. The new PPO/TRPO stuff has zero documentation supplied with it. It is possible to work it all out from the code but a little more description would make baselines hugely more accessible, especially for people newer to python and/or RL.

**Comment by Bleyddyn** [comment]
There is test code in logger.py, which I love, but it doesn't work and there is a lack of comments. Not sure if I should open a new issue just for this, though. Without more comments in there I can't figure out what that 'with session' statement is supposed to be, although it doesn't seem to be necessary. 

baselines is up-to-date with the github repo.

Mac OS X 10.9.5

$ python3 --version
Python 3.6.2

$ python3 ./logger.py
hi
should appear
Traceback (most recent call last):
  File "./logger.py", line 309, in <module>
    _demo()
  File "./logger.py", line 292, in _demo
    with session(dir=dir):
NameError: name 'session' is not defined

**Comment by olegklimov** [comment]
`logger.py` -- tests works for me. 

More comments -- surely useful, but small code you can scroll through is useful as well.
