### ISSUE TITLE
baselines/baselines/pposgd/pposgd_simple.py- clipping causing no gradient?

### ISSUE THREAD

**Issue by lezhang-thu** [openai/baselines#92]
```
    surr1 = ratio * atarg # surrogate from conservative policy iteration
    surr2 = U.clip(ratio, 1.0 - clip_param, 1.0 + clip_param) * atarg #
    pol_surr = - U.mean(tf.minimum(surr1, surr2)) # PPO's pessimistic surrogate (L^CLIP)
```

`atarg` is just a `tf.placeholder`. So when the ratio term deviates from 1.0 by too much, isn't it causing the gradient to be zero? Because I think both `1.0 - clip_param` and `1.0 + clip_param` are not `tf.Variable`s.

**Comment by CosmosShadow** [comment]
I think gradient being zero is the purpose. for ratio(`ratio > 1-clip` then `atarg > 0`, `ratio < 1 - clip` then `atarg < 0`) being enough, no need to optimize.

**Comment by lezhang-thu** [comment]
@CosmosShadow Thanks!
But I still do not understand. You are explainig the meaning of the `- U.mean(tf.minimum(surr1, surr2))`.
I know that, of course, say if `atarg > 0`, and `ratio > 1.0 + clip_param`, then `ratio` will be clipped, and of course, the objective cannot be optimized anymore, because the objective would be a constant.
My question does not lie on whether the objective can be optimized or not. Rather I just want to ask why is **this** form of the objective? Is it normal? Doesn't it cause the gradient to be zero for some cases, and hence this form is okay? Because it would bring the fact of gradient being zero, so I question its properness.
But anyway, thanks a lot for your analysis. ^_^

**Comment by yueyang130** [comment]
@lezhang-thu  I think it's exactly what the trust region means. When the change belows the upper bound 1+epsilon (when A > 0), we think this change beyond the trust region so we don't adpot this data (therefore the gradient is zero and parameters is not updated).
