### ISSUE TITLE
Deepq Favoring Action 0 in Discrete Action Space

### ISSUE THREAD

**Issue by Jyosua** [openai/baselines#926]
We've written our own environment and are trying to run the deepq algorithm with a discrete action space of 7 actions. However, regardless of how we construct our rewards, we're noticing that when we run using

`python3 -m baselines.run --alg=deepq --env=custom_env-v0 --num_timesteps=1e5 --save_path=~/simplemodel`

the agent seems to heavily favor action 0 of the 7 actions available. It initially seems to have a fairly even distribution for the first 6 episodes, but then you can see a much large number of action 0 being picked after that point and this disparity continues to grow as more episodes are completed; in later episodes, it rarely seems to pick the other actions at all.

When we noticed this behavior, we decided to remove everything in our environment that provides a reward and just return a reward of 0, but still saw the same result. Is this a bug or is there something we should be doing to avoid this?

Here's some generic environment code that produces the issue:
```python
import gym
import random
import numpy as np
from gym import spaces
import os

MAX_TIMESTEP = 365

# Mapping of value change to action states
ACTION_MEANING = {
    0: 50,
    1: 25,
    2: 5,
    3: 0,
    4: -5,
    5: -25,
    6: -50,
}

class ExampleEnv(gym.Env):
  metadata = {'render.modes': ['human']}
  def __init__(self):
    # rows and columns for the observation space 
    self.cols = 8
    self.rows = 30
    self.episodeNumber = 0

    self.actionCounts = {
        0: 0,
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
        6: 0,
    }

    # gym environment declarations
    self.action_space = spaces.Discrete(7)
    high_array = [4000]
    high_array = high_array + ([1]*((self.cols*self.rows)))
    self.observation_space = spaces.Box(low=np.array([0] * ((self.cols * self.rows) + 1)), high=np.array(high_array))

  def step(self, action):
    self.actionCounts[action] += 1
    reward = 0
    self.currentValue = max(self.currentValue + ACTION_MEANING[action], 0)
    self.currentValue = min(self.currentValue + ACTION_MEANING[action], 4000)
    self.t += 1

    if self.t == MAX_TIMESTEP:
      print(f"Episode {self.episodeNumber} completed")
      self.episodeNumber += 1
      print(f"Action Count{self.actionCounts}")

    return self.getObservation(), reward, False, {}
  
  def reset(self):
    self.t = 0
    self.currentValue = 2000
  
  def render(self, mode='human', close=False):
    pass

  def getObservation(self):
    observation_array = [self.currentValue]
    observation_array = observation_array + ([0]*((self.cols*self.rows)))
    
    return np.array(observation_array)
```

**Comment by Jyosua** [comment]
We also tried this with PPO today and are seeing the same behavior.

**Comment by sritee** [comment]
When you remove all the rewards, the q values of all actions would be similar, so perhaps the max operator picks the first index?

**Comment by Jyosua** [comment]
Maybe? Here's an example of the choices it made when I gave it a reward of 1000 every time it picked the action at index 4:

`Episode 0 completed
Action Count{0: 111, 1: 47, 2: 47, 3: 44, 4: 34, 5: 43, 6: 39}
Episode 1 completed
Action Count{0: 323, 1: 78, 2: 70, 3: 69, 4: 62, 5: 66, 6: 62}
Episode 2 completed
Action Count{0: 561, 1: 86, 2: 74, 3: 75, 4: 160, 5: 73, 6: 66}
Episode 3 completed
Action Count{0: 562, 1: 87, 2: 76, 3: 76, 4: 518, 5: 74, 6: 67}
Episode 4 completed
Action Count{0: 562, 1: 87, 2: 78, 3: 79, 4: 876, 5: 75, 6: 68}
Episode 5 completed
Action Count{0: 562, 1: 88, 2: 79, 3: 79, 4: 1237, 5: 75, 6: 70}
Episode 6 completed
Action Count{0: 562, 1: 90, 2: 80, 3: 81, 4: 1597, 5: 75, 6: 70}
Episode 7 completed
Action Count{0: 562, 1: 93, 2: 82, 3: 82, 4: 1954, 5: 76, 6: 71}
Episode 8 completed
Action Count{0: 564, 1: 93, 2: 82, 3: 82, 4: 2314, 5: 78, 6: 72}
Episode 9 completed
Action Count{0: 564, 1: 94, 2: 84, 3: 84, 4: 2671, 5: 80, 6: 73}
Episode 10 completed
Action Count{0: 565, 1: 94, 2: 84, 3: 87, 4: 3030, 5: 81, 6: 74}
Episode 11 completed
Action Count{0: 567, 1: 94, 2: 86, 3: 89, 4: 3388, 5: 82, 6: 74}`

This is from training a fresh model. It seems like in the first few episodes, even though it was only getting rewards from action 4, it was still heavily weighing action 0. That didn't appear to change until episode 4.

For our real environment code, this is a problem for us because if all the actions being a similar reward early on bias it to pick action 0 rather than to randomly pick from the actions, then our environment can't work. We're trying to train it on an environment that has a specific CHANCE of receiving a reward depending on the actions and state. Our goal is to get it to learn how to maximize average reward based on this probability, despite the chance of getting 0 reward at a specific timestep just because the RNG roll didn't turn out well. This behavior seems to be preventing it from giving other actions enough tries for it to properly weigh that behavior.

**Comment by sritee** [comment]
Are these during evaluation or training, since exploration will be happening during training. Also note that with default parameters, first 1000 timesteps no learning occurs - (https://github.com/openai/baselines/blob/master/baselines/deepq/deepq.py) Gamma is also set to 1, which is gonna be problematic with such high magnitude rewards, I would suggest a max reward of 1.

**Comment by Jyosua** [comment]
Ah, so with this information, we were able to increase the timestep at which learning starts and also scaled our rewards to be less than 1 and, in the simplest example, we able to get it to correctly learn to pick a specific set of actions given constant rewards.

With our actual custom environment, we were not quite as lucky, but making similar changes there did result in it not picking the same options over and over, even if it still appears to be having trouble learning the right thing to do. I'm going to mark this closed for now, as I think this is a step towards the real solution for us.
