### ISSUE TITLE
DQN documentation

### ISSUE THREAD

**Issue by gaperez64** [openai/baselines#945]
I do not understand the details of many of the parameters used to call DQN (like buffer_size, exploration_fraction, exploration_final_eps, train_freq, print_freq, prioritized_replay parameters, callback, param_noise etc.) and how they affect the learning process. 

Could you point me to a paper / link that explains these parameters and the learning algorithm?

**Comment by DanielTakeshi** [comment]
Have you read the original DQN paper from DeepMind?

**Comment by gaperez64** [comment]
This one?

https://www.nature.com/articles/nature14236
