### ISSUE TITLE
Definition of custom environments when using PPO2

### ISSUE THREAD

**Issue by RogerFrigola** [openai/baselines#959]
I'm using a custom environment which attempts to adhere to the `gym` specification in:

[https://gym.openai.com/docs/](https://gym.openai.com/docs/)

However, PPO2 fails because it requires that the `info` dictionary returned by `env.step(...)` has the key `'episode'`. 

As far as I can see, there is no documentation specifying what keys should the `info` dictionary have for the learning algorithms to work.

Does `baselines` require `gym` environments with extra features? Any clarification would be most welcome.

**Comment by RogerFrigola** [comment]
I tried using my custom `gym` environment on the fork `stable-baselines` and it worked straight away! Really recommended: 
https://github.com/hill-a/stable-baselines

**Comment by andytwigg** [comment]
You need to wrap your env in a Monitor object.
