### ISSUE TITLE
'Box' object has no attribute 'n'

### ISSUE THREAD

**Issue by Usmaniatech** [openai/baselines#965]
Does deepq support multi agent. I am trying to train Tennis example without the parallel training, but it's generating error.

![error](https://user-images.githubusercontent.com/14370981/61784283-e1af6480-ae22-11e9-92df-527e8e1b7db0.PNG)

**Comment by TTitcombe** [comment]
DQN needs a discrete action space. The env you're trying to use has a continuous action space, so isn't directly compatible with DQN.

**Comment by christopherhesse** [comment]
Thanks for answering this @TTitcombe
