### ISSUE TITLE
AttributeError: entry_point variable broken in run.py

### ISSUE THREAD

**Issue by NicoBach** [openai/baselines#966]
Hello!
With a recent commit in openai gym (https://github.com/openai/gym/commit/dc91f434f83f3ad612ff353cbf2c1afc4788896b) the entry_point variable was changed from private to public, thus breaking baselines/baselines/run.py script.
Updating baselines/run.py in lines 35 and 129 from
`env_type = env._entry_point.split(':')[0].split('.')[-1]`
to 
`env_type = env.entry_point.split(':')[0].split('.')[-1]`
fixes this problem. I hope, this can be useful.

Best regards,
Nico Bach

**Comment by guikarist** [comment]
I think you should create a pull request for `run.py` and `requirements.txt`.

**Comment by NicoBach** [comment]
Thanks for the advice!

**Comment by guikarist** [comment]
Due to merged #970, this issue should be closed.

**Comment by YijiongLin** [comment]
Hello! @guikarist 
Recently I tried to run the multiple thread environment, but it kept failing. And I proposed this issue in  [here](https://github.com/openai/baselines/issues/998). Could you please take a look? Any feedback is really appreciated!

**Comment by guikarist** [comment]
@YijiongLin Sorry I have never run a multiple threaded env.

**Comment by YijiongLin** [comment]
@guikarist Never mind, thanks for reply! Have a nice day.
