### ISSUE TITLE
Saving a Model

### ISSUE THREAD

**Issue by ThomasZav** [openai/baselines#973]
When we run this command,

python -m baselines.run --alg=....

It saves the model as one file. How can we save the model in the following format?
.ckpt.meta
ckpt.index
.ckpt.data
checkpoint

Or can we decompose that one file into checkpoint files?

**Comment by christopherhesse** [comment]
I'm afraid that each baselines algorithm will produce it's own save files, and may not be tensorflow model checkpoint files :/
