### ISSUE TITLE
DDPG doesn't work in mujoco

### ISSUE THREAD

**Issue by Kchu** [openai/baselines#981]
I recently tested the baselines' DDPG algorithm, but unexpectedly, DDPG failed to get great scroes and to converge.  I can't get the ideal results in many mujoco environments.
I use the download source installation, the command line runned is below: 
python -m baselines.run --alg=ddpg --env=HalfCheetah-v2 --num_timesteps=1e6

**Comment by dut09** [comment]
#938 This might be helpful?

**Comment by christopherhesse** [comment]
Closing in favor of https://github.com/openai/baselines/issues/938
