### ISSUE TITLE
Qeustion about DDPG algorithm

### ISSUE THREAD

**Issue by wonchul-kim** [openai/baselines#99]
For halfcheetah simulation,

No need to break when 'done' becomes true (if done:)?????

For example, when i did simulation with Pendulum-v0 i always put 'break' as 'done' gets 'True'.

**Comment by unixpickle** [comment]
When `done` is true, that means the episode has ended. At this point, you can either stop using the environment, or you can call `reset()` to start another episode. DDPG does the latter in order to run episodes.
