### ISSUE TITLE
I found out in Fetch Env, the action space is the linear velocity of grip, instead of grip position described in the paper

### ISSUE THREAD

**Issue by YijiongLin** [openai/baselines#991]
Today I found out in Fetch Env, the action space is the linear velocity of grip, instead of grip position described in the paper.

Because when I whether set the action always to [1,0,0,0] or [0.001,0,0,0], the grip always go to the same furthest place in the X axis positive direction. But with different velocity to get to there.

So I have a confusion about this, what exactly is the action space in the code, does it correspond to the paper Plappert et al. (2018) and Hindsight Experience Replay?

**Comment by huiwenzhang** [comment]
The action space of the Fetch env does stand for position commands (pos of gripper + gripper angle).  But it is the relative position w.r.t. to the last time step. That is the reason why you giving [1, 0, 0, 0]  and the arm keeps moving to the target where is 1 meters (actually 0.05m) away from the current pos in the X direction.

**Comment by YijiongLin** [comment]
@huiwenzhang 
Thanks for your elaborate explanation, it makes sense.

But I get confused about your last sentence. What do you mean "1 meters (actually 0.05m) away from the current pos in the X direction" ?  Do you mean the unit of the [x,y,z,grip_state] is 0.05m? Or what's the unit of the action space? Same as the one in observation or not?

Thanks again for replying.

**Comment by huiwenzhang** [comment]
The unit is meter. If you look at the source code of the fetch env, you will know that the action is scaled down by a factor 0.05 before feeding into the controller. That is where the 0.05 comes from.

**Comment by YijiongLin** [comment]
@huiwenzhang Thanks a lot.

**Comment by YijiongLin** [comment]
@huiwenzhang 
Hello!
Recently I tried to run the multiple thread environment, but it kept failing. And I proposed this issue in  [here](https://github.com/openai/baselines/issues/998). Could you please take a look? Any feedback is really appreciated!
