### ISSUE TITLE
why `step_model` and `train_model` instead of one?

### ISSUE THREAD

**Issue by breezedeus** [openai/baselines#994]
Hi, I am reading the code of `a2c.py`, but confused about the design of `step_model` and `train_model`. As I read, both of them share parameters. So, why are two models used instead of one? Thanks.

```python
            # step_model is used for sampling
            step_model = policy(nenvs, 1, sess)

            # train_model is used to train our network
            train_model = policy(nbatch, nsteps, sess)
```

**Comment by christopherhesse** [comment]
For a recurrent policy, the training model should take in `num_envs * nsteps` observations in a batch for each forward pass.  When you're taking individual steps though, you only have `nsteps=1`  (1 per environment) observations, not a batch of them, so in that case, your model is slightly different.

Ideally you could use the same model object for both (like the model dynamically just uses whatever `nsteps` you happen to have for some data) so it's possible that tensorflow has some limitation making this hard to do.
